from hx_tools.test_cases_service import export_test_case_template, run_all_test_cases, export_test_case_results

import os
import shutil
import pandas as pd
import numpy as np

# Compare against existing results
# Results that have been previously verified
# Policy results
saved_results_policy_filepath = "/workspace/editing/test_cases/saved_results.csv"
saved_results_policy = pd.read_csv(saved_results_policy_filepath).to_dict("records")

###
# Delete and recreate all generated test_inputs and test_outputs
# This will account for changes in Rating, Data Schema or Example Data since the last time the tests were run

# Delete all files within 'test_inputs' and 'test_outputs' folders found within test_cases
for filename in os.listdir("editing/test_cases/"):
    if filename in ("test_inputs", "test_outputs"):
        print(f"Removing editing/test_cases/{filename}")
        shutil.rmtree(f"editing/test_cases/{filename}")

# Create test case template files inside folder: editing/test_cases/_template_YYYYMMDD_hhmmss
export_test_case_template()

# Rename this exported and timestamped folder to test_inputs
for filename in os.listdir("editing/test_cases/"):
    if filename.startswith("_template_"):
        org_fp = os.path.join("editing/test_cases/", filename)
        new_fp = os.path.join("editing/test_cases/", "test_inputs")
        os.rename(org_fp, new_fp)

# Run test cases and save the results of running the test cases to folder: editing/test_cases/_results_YYYYMMDD_hhmmss
results = run_all_test_cases("test_inputs")

export_test_case_results(results)

# Rename this exported and timestamped folder to test_outputs
for filename in os.listdir("editing/test_cases/"):
    if filename.startswith("_results_"):
        org_fp = os.path.join("editing/test_cases/", filename)
        new_fp = os.path.join("editing/test_cases/", "test_outputs")
        os.rename(org_fp, new_fp)

# Filepath for results that are generated by test cases
generated_results_filepath = "/workspace/editing/test_cases/test_outputs/root.csv"
generated_results = pd.read_csv(generated_results_filepath).to_dict("records")

# Test by matching on assured - this should not change even if the test ids do
# The developer should replace this with some unique identifier field within their own Data Schema
unique_id_field = "insured"

# List of policy level fields to test
policy_test_fields = [
    "hx_core.model_premium", 
    "hx_core.charged_premium"
]

# All saved results should be tested
# There may be additional example datasets that are not testable
# Iterate through saved results, compare to the appropriate generate results set for each test field

test_pass = True

# Policy level testing
for saved_test_row in saved_results_policy:
    # Get assured to test
    test_id = saved_test_row.get(unique_id_field)

    # Filter generated tests on this assured
    gen_test_row = [gen_row for gen_row in generated_results if gen_row.get(unique_id_field) == test_id]

    if not gen_test_row:
        # The test case does not exist in the generated results
        print(f"ID {test_id} not found")
        test_pass = False
    else:
        if len(gen_test_row) > 1: # Multiple matches on same assured found
            print(f"Multiple matches on {test_id} found")
            test_pass = False
            break

        gen_test_dict = gen_test_row[0]

        for test_field in policy_test_fields:
            # Compare values for each field
            # Tolerance set at 0.001%
            print(gen_test_dict.get(test_field), saved_test_row.get(test_field))

            # If one item is nan and the other is zero then that is considered a pass
            # This can happen when a test case does not include all fields and we are testing for a coverage specific field that does not exist
            if (np.isnan(gen_test_dict.get(test_field)) and not saved_test_row.get(test_field)):
                print(f"Match - ID {test_id} {test_field} 0.0 match 0.0")
            elif (np.isnan(gen_test_dict.get(test_field)) and np.isnan(saved_test_row.get(test_field))):
                print(f"Match - ID {test_id} {test_field} nan match nan")
            elif not np.isclose(gen_test_dict.get(test_field), saved_test_row.get(test_field), rtol=1e-04):
                print(f"No match - ID {test_id} {test_field} {gen_test_dict.get(test_field)} does not match {saved_test_row.get(test_field)}")
                test_pass = False
            else:
                print(f"Match - ID {test_id} {test_field} {gen_test_dict.get(test_field)} match {saved_test_row.get(test_field)}")

# Results
if test_pass:
    print("Tests passed")
else:
    print("Tests failed")