import hx_data_schema as hx
import data_schema.sch_utilities as utils
from data_schema.sch_utilities import thousands_format, percent_format, integer_format



def sch_exposure_management_api(cds):
    cds.extend_node_rater_defined("cds", {
        "exposure_management_api": hx.Structure(children={
            "limit_results": hx.Int(mode="input", default=10, optionality="optional", view={"label": "Rows to Return"}, async_input=["search_exposure_management_data_task"]),
            "inputs": hx.Structure(children={
            "binder_reference": hx.Str(mode="output", view={"label": "Binder Reference"}),
                  
            "binder_name": hx.Str(mode="output", view={"label": "Binder Name"})
            }),
            "binder_reference_to_search": hx.Str(mode="output", async_output=["search_exposure_management_data_task"],view={"label": "Binder Reference to search"}),


            

            "search_fetch_status": hx.Str(mode="output", async_output=["search_exposure_management_data_task"], view={"label": "Exposure Management API Status"}),
            "search_results": hx.List(mode="input", async_input=["pull_in_exposure_management_data_task"], async_output=["search_exposure_management_data_task"], children={
                "binder_date": hx.Date(mode="input", optionality="optional",default=None, async_input=["pull_in_exposure_management_data_task"], async_output=["search_exposure_management_data_task"], view={"label": "Binder Date", "read_only":True}),
                "binder_reference": hx.Str(mode="input",optionality="optional", default=None,async_input=["pull_in_exposure_management_data_task"], async_output=["search_exposure_management_data_task"], view={"label": "Binder Reference", "read_only":True}),
                "binder_name": hx.Str(mode="input",optionality="optional",default=None, async_input=["pull_in_exposure_management_data_task"], async_output=["search_exposure_management_data_task"], view={"label": "Binder Name", "read_only":True}),
                "num_locs": hx.Str(mode="input", optionality="optional",default=None,async_input=["pull_in_exposure_management_data_task"], async_output=["search_exposure_management_data_task"], view={"label": "Loc Count", "read_only":True}),
                "selected": hx.Bool(mode="input", async_input=["pull_in_exposure_management_data_task"], default=False, view={"label": "Import"})
            }),
            "location_fetch_status": hx.Str(mode="output", async_output=["pull_in_exposure_management_data_task"], view={"label": "Exposure Management API Status"}),
            # For simulation ELT search
            "simulation_fetch_status": hx.Str(mode="output", async_output=["run_simulation_task"], view={"label": "Simulation Status"}),

            "agg_search_results": hx.List(mode="input", async_input=["clear_binder_list_task", "select_binders_for_em_pull_task", "pull_in_exposure_management_data_task"], async_output=["clear_binder_list_task", {"task": "select_binders_for_em_pull_task", "reset": False}], children={
                "binder_reference": hx.Str(mode="output", async_input=["clear_binder_list_task", "select_binders_for_em_pull_task", "pull_in_exposure_management_data_task"], async_output=["clear_binder_list_task", {"task": "select_binders_for_em_pull_task", "reset": False}], view={"label": "Binder Reference"}),
                "binder_name": hx.Str(mode="output", async_input=["clear_binder_list_task", "select_binders_for_em_pull_task", "pull_in_exposure_management_data_task"], async_output=["clear_binder_list_task", {"task": "select_binders_for_em_pull_task", "reset": False}], view={"label": "Binder Name"}),
                "num_locs": hx.Str(mode="output", async_input=["clear_binder_list_task", "select_binders_for_em_pull_task", "pull_in_exposure_management_data_task"], async_output=["clear_binder_list_task", {"task": "select_binders_for_em_pull_task", "reset": False}], view={"label": "Loc Count"}),
            }),
        })
    })


def sch_bi_data(cds):
        
    # Extending cds nodes for RMS
    cds.extend_node_rater_defined("cds", {

        "bi_data": hx.Structure(children={
            "fetch_clm_and_mvmt_detail_task_status"     : hx.Str(mode="input",optionality="optional",default=None,              view={"label": "Status - Load Historic Claims", "read_only": True},                                                                                                                                                                      async_output=["start_renewal_task","bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task"]),
            "fetch_facility_detail_task_status"         : hx.Str(mode="output",                 view={"label": "Status - Load Historic Binders"},                                                                                                                                                                     async_output=["bi_facility_fetch_task","start_renewal_task"]),
            "include_all_facility_references"           : hx.Bool(mode="input",  default=True,  view={"label": "Include all binder references?"},                                                                              async_input=["bi_facility_fetch_task", "bi_clm_and_mvmt_inc_triangles_fetch_task","start_renewal_task"]),
            "triangles_loaded"                          : hx.Bool(mode="output",                view={"label": "Triangles Loaded"},                                                                                                                                                                                   async_output=["bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task"]),

            # listing of individual facilities (technically section references)
            "facility_detail"                           : hx.List(mode="input", async_output=["bi_facility_fetch_task"], children={
                "include"                               : hx.Bool(mode="input", default=False,                          view={"label": "Include?"},                                                         async_input=["bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task","start_renewal_task"],                           async_output=["bi_facility_fetch_task", "bi_facility_include_all_task", "bi_facility_exclude_all_task","start_renewal_task"]),
                "date_extracted"                        : hx.Date(mode="input", default=None,   optionality="optional", view={"label": "CreatedTimeStamp"},                                                                    async_input=["bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task"], async_output=["bi_facility_fetch_task","start_renewal_task"]),
                "section_reference"                     : hx.Str(mode="input",  default=None,   optionality="optional", view={"label": "Section Reference"},                                                                   async_input=["bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task"], async_output=["bi_facility_fetch_task","start_renewal_task"]),
                "insured_party"                         : hx.Str(mode="input",  default=None,   optionality="optional", view={"label": "Insured Party"},                                                                       async_input=["bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task"], async_output=["bi_facility_fetch_task","start_renewal_task"]),
                "inception_date"                        : hx.Date(mode="input", default=None,   optionality="optional", view={"label": "Inception Date"},                                                                      async_input=["bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task"], async_output=["bi_facility_fetch_task","start_renewal_task"]),
                "expiry_date"                           : hx.Date(mode="input", default=None,   optionality="optional", view={"label": "Expiry Date"},                                                                         async_input=["bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task"], async_output=["bi_facility_fetch_task","start_renewal_task"]),
                "underwriter_name"                      : hx.Str(mode="input",  default=None,   optionality="optional", view={"label": "Underwriter Name"},                                                                    async_input=["bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task"], async_output=["bi_facility_fetch_task","start_renewal_task"]),
                "settlement_currency"                   : hx.Str(mode="input",  default=None,   optionality="optional", view={"label": "Settlement Currency"},                                                                 async_input=["bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task"], async_output=["bi_facility_fetch_task","start_renewal_task"]),
                "section_is_renewal"                    : hx.Str(mode="input",  default=None,   optionality="optional", view={"label": "Section Is Renewal"},                                                                  async_input=["bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task"], async_output=["bi_facility_fetch_task","start_renewal_task"]),
                "division"                              : hx.Str(mode="input",  default=None,   optionality="optional", view={"label": "Division"},                                                                            async_input=["bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task"], async_output=["bi_facility_fetch_task","start_renewal_task"]),
                "written_or_estimated_signed_line"      : hx.Float(mode="input",default=None,   optionality="optional", view={"label": "Written Or Estimated Signed Line",          "format":percent_format(2)},               async_input=["bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task"], async_output=["bi_facility_fetch_task","start_renewal_task"]),
                "trifocus_name"                         : hx.Str(mode="input",  default=None,   optionality="optional", view={"label": "Trifocus Name"},                                                                       async_input=["bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task"], async_output=["bi_facility_fetch_task","start_renewal_task"]),
                "external_acquisition_cost_multiplier"  : hx.Float(mode="input",default=None,   optionality="optional", view={"label": "External Acquisition Cost Multiplier",      "format":percent_format(2)},               async_input=["bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task"], async_output=["bi_facility_fetch_task","start_renewal_task"]),
                "profit_commission_multiplier"          : hx.Float(mode="input",default=None,   optionality="optional", view={"label": "Profit Commission Multiplier",              "format":percent_format(2)},               async_input=["bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task"], async_output=["bi_facility_fetch_task","start_renewal_task"]),
                "placing_brokername"                    : hx.Str(mode="input",  default=None,   optionality="optional", view={"label": "Placing Brokername"},                                                                  async_input=["bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task"], async_output=["bi_facility_fetch_task","start_renewal_task"]),
                "risk_class_code"                       : hx.Str(mode="input",  default=None,   optionality="optional", view={"label": "Risk Class Code"},                                                                     async_input=["bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task"], async_output=["bi_facility_fetch_task","start_renewal_task"]),
                "yoa"                                   : hx.Float(mode="input",default=None,   optionality="optional", validation={"min_value": 0}, view={"label": "Year of Account",                           "format":integer_format(0)},               async_input=["bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task"], async_output=["bi_facility_fetch_task","start_renewal_task"]),
                "written_or_estimated_premium"          : hx.Float(mode="input",default=None,   optionality="optional", validation={"min_value": 0}, view={"label": "AFB Net Premium",                           "format":thousands_format(0)},             async_input=["bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task"], async_output=["bi_facility_fetch_task","start_renewal_task"]),
                "rate_change_divisor"                   : hx.Float(mode="input",default=None,   optionality="optional", view={"label": "Rate Change Multiplier",                    "format":percent_format(2)},               async_input=["bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task"], async_output=["bi_facility_fetch_task"]),
                "spot_rate_usd_to_sett"                 : hx.Float(mode="input",default=None,   optionality="optional", view={"label": "Spot Rate USD to Settlement Fx",            "format":integer_format(3)},                                                                                                                                               async_output=["bi_facility_fetch_task", "bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task","start_renewal_task"]),
                "net_beazley_premium_sett_fx"           : hx.Float(mode="input",default=None,   optionality="optional", view={"label": "Net Beazley Premium @ Settlement Fx",       "format":thousands_format(0)},                                                                                                                                             async_output=["bi_facility_fetch_task", "bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task","start_renewal_task"]),
                "net_100pct_premium_sett_fx"            : hx.Float(mode="input",default=None,   optionality="optional", view={"label": "Net 100pct Premium @ Settlement Fx",        "format":thousands_format(0)},                                                                                                                                             async_output=["bi_facility_fetch_task", "bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task","start_renewal_task"]),
                "gross_100pct_premium_sett_fx"          : hx.Float(mode="input",default=None,   optionality="optional", view={"label": "Gross 100pct Premium @ Settlement Fx",      "format":thousands_format(0)},                                                                                                                                             async_output=["bi_facility_fetch_task", "bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task","start_renewal_task"]),
                "net_100pct_premium_adjexp_sett_fx"     : hx.Float(mode="input",default=None,   optionality="optional", view={"label": "Net 100pct Adjusted Expiring Premium @ Settlement Fx",  "format":thousands_format(0)},                                                                                                                                 async_output=["bi_facility_fetch_task", "bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task","start_renewal_task"]),
            }),

 
            # listing of individual claims (technically exposure references) for all selected facilities
            "claims_listing"            : hx.List(mode="input", children={
                    'date_extracted'                    : hx.Date(mode="input",  default=None,   optionality="optional", view={"label": "Date Extracted"},                                                    async_output=["bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task", "bi_facility_fetch_task"]),
                    'section_reference'                 : hx.Str(mode="input",   default=None,   optionality="optional", view={"label": "Section Reference"},                                                 async_output=["bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task", "bi_facility_fetch_task"]),
                    'claim_reference'                   : hx.Str(mode="input",   default=None,   optionality="optional", view={"label": "Claim Reference"},                                                   async_output=["bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task", "bi_facility_fetch_task"]),
                    'exposure_reference'                : hx.Str(mode="input",   default=None,   optionality="optional", view={"label": "Exposure Reference"},                                                async_output=["bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task", "bi_facility_fetch_task"]),
                    'yoa'                               : hx.Float(mode="input", default=None,   optionality="optional", view={"label": "YOA",                              "format":integer_format(0)},      async_output=["bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task", "bi_facility_fetch_task"]),
                    'beazley_catcode'                   : hx.Str(mode="input",   default=None,   optionality="optional", view={"label": "Beazley CatCode"},                                                   async_output=["bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task", "bi_facility_fetch_task"]),
                    'market_catcode'                    : hx.Str(mode="input",   default=None,   optionality="optional", view={"label": "Market CatCode"},                                                    async_output=["bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task", "bi_facility_fetch_task"]),
                    'trifocus_name'                     : hx.Str(mode="input",   default=None,   optionality="optional", view={"label": "TriFocus Name"},                                                     async_output=["bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task", "bi_facility_fetch_task"]),
                    'settlement_currency'               : hx.Str(mode="input",   default=None,   optionality="optional", view={"label": "Settlement Currency"},                                               async_output=["bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task", "bi_facility_fetch_task"]),
                    'block_indicator'                   : hx.Str(mode="input",   default=None,   optionality="optional", view={"label": "Block Indicator"},                                                   async_output=["bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task", "bi_facility_fetch_task"]),
                    'date_of_loss'                      : hx.Date(mode="input",  default=None,   optionality="optional", view={"label": "Date Of Loss"},                                                      async_output=["bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task", "bi_facility_fetch_task"]),
                    'claim_made_date'                   : hx.Date(mode="input",  default=None,   optionality="optional", view={"label": "Claim Made Date"},                                                   async_output=["bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task", "bi_facility_fetch_task"]),
                    'claim_or_circumstance'             : hx.Str(mode="input",   default=None,   optionality="optional", view={"label": "Claim Or Circumstance"},                                             async_output=["bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task", "bi_facility_fetch_task"]),
                    'beazley_share_total_incurred'      : hx.Float(mode="input", default=None,   optionality="optional", view={"label": "Beazley Share Total Incurred",     "format":thousands_format(0)},    async_output=["bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task", "bi_facility_fetch_task"]),
                    'slip_order_total_incurred'         : hx.Float(mode="input", default=None,   optionality="optional", view={"label": "Slip Order Total Incurred",        "format":thousands_format(0)},    async_output=["bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task", "bi_facility_fetch_task"]),
                    'slip_order_total_paid'             : hx.Float(mode="input", default=None,   optionality="optional", view={"label": "Slip Order Total Paid",            "format":thousands_format(0)},    async_output=["bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task", "bi_facility_fetch_task"]),
                    'beazley_share_pre_peer_blend'      : hx.Float(mode="input", default=None,   optionality="optional", view={"label": "Beazley Share Pre Peer Blend",     "format":thousands_format(0)},    async_output=["bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task", "bi_facility_fetch_task"]),
                    'beazley_share_pre_peer_most_likely': hx.Float(mode="input", default=None,   optionality="optional", view={"label": "Beazley Share Pre Peer Most Likely","format":thousands_format(0)},   async_output=["bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task", "bi_facility_fetch_task"]),
                    'loss_category'                     : hx.Str(mode="input",   default=None,   optionality="optional", view={"label": "Loss Category"},                                                     async_output=["bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task", "bi_facility_fetch_task"]),
                    'bi_paid'                           : hx.Float(mode="input", default=None,   optionality="optional", view={"label": "BI Paid",                          "format":thousands_format(0)},    async_output=["bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task", "bi_facility_fetch_task"]),
                    'bi_os'                             : hx.Float(mode="input", default=None,   optionality="optional", view={"label": "BI OS",                            "format":thousands_format(0)},    async_output=["bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task", "bi_facility_fetch_task"]),
                    'bi_incurred'                       : hx.Float(mode="input", default=None,   optionality="optional", view={"label": "BI Incurred",                      "format":thousands_format(0)},    async_output=["bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task", "bi_facility_fetch_task"]),
                    'pre_peer_blend_incurred'           : hx.Float(mode="input", default=None,   optionality="optional", view={"label": "Pre Peer Blend Incurred",          "format":thousands_format(0)},    async_output=["bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task", "bi_facility_fetch_task"]),
                    'pre_peer_most_likely_incurred'     : hx.Float(mode="input", default=None,   optionality="optional", view={"label": "Pre Peer most likely Incurred",    "format":thousands_format(0)},    async_output=["bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task", "bi_facility_fetch_task"]),
                    'show_cat'                          : hx.Bool(mode="input",  default=None,   optionality="optional", view={"label": "Show Cat"},                                                          async_output=["bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task", "bi_facility_fetch_task"]),
                    'show_large'                        : hx.Bool(mode="input",  default=None,   optionality="optional", view={"label": "Show Large"},                                                        async_output=["bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task", "bi_facility_fetch_task"]),
                    'class_rank'                        : hx.Float(mode="input", default=None,   optionality="optional", view={"label": "Rank",                             "format":thousands_format(0)},    async_output=["bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task", "bi_facility_fetch_task"]),
            }),



            # listing of individual claims movements (technically exposure references) for all selected facilities
            "claims_movements"                  : hx.List(mode="input",                                                                                                                                        async_input=["tri_exclusions_setup_task"], async_output=["bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task", "bi_facility_fetch_task"], children={
                    'date_extracted'            : hx.Date(mode="input",  default=None,   optionality="optional", view={"label": "Date Extracted"},                                                             async_input=["tri_exclusions_setup_task"], async_output=["bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task", "bi_facility_fetch_task"]),
                    'loss_category'             : hx.Str(mode="input",   default=None,   optionality="optional", view={"label": "Loss Category"},                                                              async_input=["tri_exclusions_setup_task"], async_output=["bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task", "bi_facility_fetch_task"]),
                    'yoa'                       : hx.Float(mode="input", default=None,   optionality="optional", view={"label": "YOA",                                      "format":integer_format(0)},       async_input=["tri_exclusions_setup_task"], async_output=["bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task", "bi_facility_fetch_task"]),
                    'mvmt_yr'                   : hx.Float(mode="input", default=None,   optionality="optional", view={"label": "Movement Year",                            "format":integer_format(0)},       async_input=["tri_exclusions_setup_task"], async_output=["bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task", "bi_facility_fetch_task"]),
                    'incurredmvmt_100_sett_fx'  : hx.Float(mode="input", default=None,   optionality="optional", view={"label": "Incurred Movement",                        "format":thousands_format(0)},     async_input=["tri_exclusions_setup_task"], async_output=["bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task", "bi_facility_fetch_task"]),
            }),

        })
    })

    #facility detail - list node
    cds.override_node_properties("cds/bi_data/facility_detail", {"async_input" : ["tri_exclusions_setup_task"], "async_output": ["bi_facility_fetch_task"]})
    cds.override_node_properties("cds/bi_data/claims_listing", {"async_output" : ["bi_clm_and_mvmt_inc_triangles_fetch_task", "bi_clm_and_mvmt_exc_triangles_fetch_task"]})
