name: PR Review - Prod - Model Release

permissions:
  contents: write
  issues: write
  pull-requests: write
  actions: read
  
on:
  pull_request_review:
    types: [submitted, edited]

jobs:

  approve-model-release:
    if: contains(github.event.pull_request.labels.*.name, 'hx_model_release') && github.event.review.state == 'approved'
    uses: beazley/hyperexponential.rater.shared_workflows/.github/workflows/reusable-prod-approve_model_release.yml@main
    with:
      ENVIRONMENT: "us-prd"
    secrets:
      HX_AZURE_AD_CLIENTSECRET: ${{ secrets.HX_AZURE_AD_CLIENTSECRET }}
      READ_GITHUB_REPO_PAT: ${{ secrets.READ_GITHUB_REPO_PAT }}
      SERVICE_NOW_USERNAME: ${{ secrets.SERVICE_NOW_USERNAME }}
      SERVICE_NOW_PASSWORD: ${{ secrets.SERVICE_NOW_PASSWORD }}

  auto-merge-pr:
    if: contains(github.event.pull_request.labels.*.name, 'hx_model_release') && github.event.review.state == 'approved'
    needs: approve-model-release
    uses: beazley/hyperexponential.rater.shared_workflows/.github/workflows/reusable-prod-auto_merge_pr.yml@main
    secrets:
      READ_GITHUB_REPO_PAT: ${{ secrets.READ_GITHUB_REPO_PAT }}

  model_release_emails:
    if: contains(github.event.pull_request.labels.*.name, 'hx_model_release') && github.event.review.state == 'approved'
    needs: approve-model-release
    uses: beazley/hyperexponential.rater.shared_workflows/.github/workflows/reusable-all-model-release-emails.yml@main
    with:
      FORM_BODY: ${{github.event.pull_request.body}}
    secrets:
      READ_GITHUB_REPO_PAT: ${{ secrets.READ_GITHUB_REPO_PAT }}
      EMAIL_AZURE_AD_CLIENTSECRET: ${{ secrets.EMAIL_AZURE_AD_CLIENTSECRET }}
    
  prod-refresh-source-files:
    if: contains(github.event.pull_request.labels.*.name, 'hx_model_release') && github.event.review.state == 'approved'
    needs: approve-model-release
    uses: beazley/hyperexponential.rater.shared_workflows/.github/workflows/reusable-all-get_model_source_files.yml@main
    with:
      ENVIRONMENT: "us-prd"
    secrets:
      HX_AZURE_AD_CLIENTSECRET: ${{ secrets.HX_AZURE_AD_CLIENTSECRET }}
      READ_GITHUB_REPO_PAT: ${{ secrets.READ_GITHUB_REPO_PAT }}

  prod-model-movement-checks:
    if: contains(github.event.pull_request.labels.*.name, 'hx_model_release') && github.event.review.state == 'approved'
    needs: [approve-model-release, prod-refresh-source-files]
    uses: beazley/hyperexponential.rater.shared_workflows/.github/workflows/reusable-prod-model-movement-checks.yml@main
    with:
      BRANCH_DEV: "us-dev"
      BRANCH_PROD: "us-prd"
    secrets:
      READ_GITHUB_REPO_PAT: ${{ secrets.READ_GITHUB_REPO_PAT }}
      READ_GITHUB_PACKAGE_PAT:  ${{ secrets.READ_GITHUB_PACKAGE_PAT }}
      HX_MODEL_MOVEMENT_AZURE_AD_USERNAME: ${{ secrets.HX_MODEL_MOVEMENT_AZURE_AD_USERNAME }}
      HX_MODEL_MOVEMENT_AZURE_AD_PASSWORD: ${{ secrets.HX_MODEL_MOVEMENT_AZURE_AD_PASSWORD }}
      EMAIL_AZURE_AD_CLIENTSECRET: ${{ secrets.EMAIL_AZURE_AD_CLIENTSECRET }}

  reject-model-release:
    if: contains(github.event.pull_request.labels.*.name, 'hx_model_release') && github.event.review.state == 'changes_requested'
    uses: beazley/hyperexponential.rater.shared_workflows/.github/workflows/reusable-prod-reject_model_release.yml@main
    with:
      ENVIRONMENT: "us-prd"
    secrets:
      HX_AZURE_AD_CLIENTSECRET: ${{ secrets.HX_AZURE_AD_CLIENTSECRET }}
      READ_GITHUB_REPO_PAT: ${{ secrets.READ_GITHUB_REPO_PAT }}
      SERVICE_NOW_USERNAME: ${{ secrets.SERVICE_NOW_USERNAME }}
      SERVICE_NOW_PASSWORD: ${{ secrets.SERVICE_NOW_PASSWORD }}

  auto-reject-pr:
    if: contains(github.event.pull_request.labels.*.name, 'hx_model_release') && github.event.review.state == 'changes_requested'
    needs: reject-model-release
    uses: beazley/hyperexponential.rater.shared_workflows/.github/workflows/reusable-prod-auto_reject_pr.yml@main
    secrets:
      READ_GITHUB_REPO_PAT: ${{ secrets.READ_GITHUB_REPO_PAT }}

  create-change:
    needs: [approve-model-release, model_release_emails]
    if: contains(github.event.pull_request.labels.*.name, 'hx_model_release') && github.event.review.state == 'approved'
    uses: beazley/servicenow-change/.github/workflows/create-change.yml@v1
    with:
      version: ${{ needs.model_release_emails.outputs.model_version_label }}
      release-notes: ${{ needs.model_release_emails.outputs.release_note }}
      job-status: ${{ needs.approve-model-release.result }}
      service-now-service-offering: ${{ vars.SERVICE_NOW_CONFIGURATION_ITEM }}
      service-now-configuration-item: "Hyperexponential Renew Prd"
      service-now-business-service: "Rating Support Services"
    secrets: inherit