import hx_data_schema as hx
from libraries.common_data_schema.data_schema.sch_common_data_schema import CommonDataSchema
from data_schema.sch_risk_information import sch_risk_information
from data_schema.sch_risk_assessment import sch_risk_assessment
from data_schema.sch_exposure_details import sch_exposure_details
# from data_schema.sch_experience_rating import sch_experience_rating
from data_schema.sch_pricing import sch_pricing
from data_schema.sch_rate_change import sch_rate_change
from data_schema.sch_rating_summary import sch_rating_summary
from data_schema.sch_rating_summary_mmp import sch_rating_summary_mmp
from data_schema.sch_async_capiq import sch_async_capiq
# from data_schema.sch_example_code import sch_example_code
from data_schema.sch_model_state import sch_model_state
#from data_schema.sch_autogenerated import sch_rater_defined
from data_schema.sch_validations import sch_validations
from libraries.email_notification.data_schema.bug_report_schema import bug_report



def sch_common_data_schema():
    cds = CommonDataSchema()

    sch_risk_information(cds)
    sch_risk_assessment(cds)
    sch_rate_change(cds)
    sch_exposure_details(cds)
    sch_pricing(cds)
    sch_rating_summary(cds)
    sch_rating_summary_mmp(cds)
    sch_async_capiq(cds)
    # sch_experience_rating(cds) 
    # sch_example_code(cds) # Remove for live model
    sch_validations(cds)

   # sch_rater_defined(cds)

    return cds.get_data_schema()


@hx.data_schema
def data_schema():
    return hx.Structure(children={
        **sch_common_data_schema(),
        **sch_model_state(),
        **bug_report(),
        # hx core - modifying to allow for async_inputs
        "hx_core": hx.Structure(children={
            "inception_date": hx.Date(default="2018-01-01", mode="input", async_input=["rarc_task", "generate_uw_rationale_doc_task"], view={"label": "Inception Date"}),
            "expiry_date": hx.Date(default="2018-12-31", mode="input", async_input=["rarc_task", "generate_uw_rationale_doc_task"], view={"label": "Expiry Date"}),
        }, view={"label": "Hx Core"}),
    })