name: Manual - All - Create Correction

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        description: 'The environment for which the datafix will be applied to.'
        required: true
        type: choice
        options:
        - us-dev
        - us-tst
        - us-pre-prod
        - us-prd
      HX_POLICY_OPTION_ID:
        description: 'The Policy Option Id to be corrected.'
        required: true
        type: string
      HX_CORRECTION_NAME:
        description: 'The name for the correction.'
        required: true
        type: string

jobs:

  commence_correction:
    uses: beazley/hyperexponential.rater.shared_workflows/.github/workflows/reusable-all-create_correction.yml@main
    with:
      ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
      HX_POLICY_OPTION_ID: ${{ inputs.HX_POLICY_OPTION_ID }}
      HX_CORRECTION_NAME: ${{ inputs.HX_CORRECTION_NAME }}
    secrets:
      HX_AZURE_AD_CLIENTSECRET: ${{ secrets.HX_AZURE_AD_CLIENTSECRET }}
      READ_GITHUB_REPO_PAT: ${{ secrets.READ_GITHUB_REPO_PAT }}
      SERVICE_NOW_CLIENT_ID: ${{ secrets.SERVICE_NOW_CLIENT_ID }}
      SERVICE_NOW_CLIENT_SECRET: ${{ secrets.SERVICE_NOW_CLIENT_SECRET }}