raise Exception("""This file is generated

Do not edit manually as all of the changes will be lost.
This is the static version of your Data Schema that will allow easier debugging.
""")

import hx_data_schema as hx


@hx.data_schema
def hx_calculation_legacy_initial_premium():
    return hx.Structure(children={
        "hx_core": hx.Structure(children={
            "inception_date": hx.Date(default="2018-01-01", mode="input", view={"label": "Inception Date"}),
            "expiry_date": hx.Date(default="2018-12-31", mode="input", view={"label": "Expiry Date"}),
            "model_premium": hx.Float(mode="output", view={"label": "Model Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
            "charged_premium": hx.Float(mode="output", view={"label": "Gross Quoted Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
            "premium_currency": hx.Str(mode="output", view={"label": "Currency"}),
            "ulr": hx.Float(mode="output", view={"label": "Implied ULR", "format": {"output": "percent", "mantissa": 1}}),
            "class_code": hx.Str(mode="output", view={"label": "Class Code"}),
        }, view={"label": "Hx Core"}),
        "cds": hx.Structure(view={"label": "cds"}, children={
            "key_industry": hx.Structure(view={"label": "Key Industry"}, children={
                "code_type": hx.Str(mode="input", default="SIC_USA", optionality="optional", options=["NAICS", "SIC_USA", "SIC_UK", "UW Defined"], view={"label": "Industry Code Type"}),
                "code": hx.Str(mode="input", default_index=0, optionality="optional", options_column="SIC Code 4ch", options_table="sic_lookup", view={"label": "SIC Code"}),
                "code_name": hx.Str(mode="output", optionality="optional", view={"label": "Industry Group"}),
                "industry_group": hx.Str(mode="output", view={"label": "Industry Group"}),
                "industry": hx.Str(mode="output", view={"label": "Industry"}),
            }),
            "exposure": hx.Structure(view={"label": "Exposure"}, children={
                "aggregate": hx.Structure(view={"label": "Aggregate"}, children={
                    "revenue": hx.Int(mode="input", default=0, view={"label": "Annual Revenue", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "assets": hx.Int(mode="input", default=0, view={"label": "Assets", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "employees": hx.Int(mode="input", default=0, view={"label": "Number of Officers and Employees", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "locations": hx.Int(mode="input", default=0, view={"label": "Number of Locations", "format": {"thousandSeparated": True, "mantissa": 0}}),
                }),
            }),
            "standard_fields": hx.Structure(view={"label": "Standard Fields"}, children={
                "insured_name": hx.Str(mode="input", default=None, async_input=["start_renewal_task"], optionality="optional", view={"label": "Insured Name"}),
                "broker": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Broker Name"}),
                "expiry_date": hx.Date(mode="output", view={"label": "Expiry Date"}),
                "inception_date": hx.Date(mode="output", view={"label": "Inception Date"}),
                "insured_country": hx.Str(mode="output", optionality="optional", options=["", "AND", "ARE", "AFG", "ATG", "AIA", "ALB", "ARM", "AGO", "ATA", "ARG", "ASM", "AUT", "AUS", "ABW", "ALA", "AZE", "BIH", "BRB", "BGD", "BEL", "BFA", "BGR", "BHR", "BDI", "BEN", "BLM", "BMU", "BRN", "BOL", "BES", "BRA", "BHS", "BTN", "BVT", "BWA", "BLR", "BLZ", "CAN", "CCK", "COD", "CAF", "COG", "CHE", "CIV", "COK", "CHL", "CMR", "CHN", "COL", "CRI", "CUB", "CPV", "CUW", "CXR", "CYP", "CZE", "DEU", "DJI", "DNK", "DMA", "DOM", "DZA", "ECU", "EST", "EGY", "ESH", "ERI", "ESP", "ETH", "FIN", "FJI", "FLK", "FSM", "FRO", "FRA", "GAB", "GBR", "GRD", "GEO", "GUF", "GGY", "GHA", "GIB", "GRL", "GMB", "GIN", "GLP", "GNQ", "GRC", "SGS", "GTM", "GUM", "GNB", "GUY", "HKG", "HMD", "HND", "HRV", "HTI", "HUN", "IDN", "IRL", "ISR", "IMN", "IND", "IOT", "IRQ", "IRN", "ISL", "ITA", "JEY", "JAM", "JOR", "JPN", "KEN", "KGZ", "KHM", "KIR", "COM", "KNA", "PRK", "KOR", "KWT", "CYM", "KAZ", "LAO", "LBN", "LCA", "LIE", "LKA", "LBR", "LSO", "LTU", "LUX", "LVA", "LBY", "MAR", "MCO", "MDA", "MNE", "MAF", "MDG", "MHL", "MKD", "MLI", "MMR", "MNG", "MAC", "MNP", "MTQ", "MRT", "MSR", "MLT", "MUS", "MDV", "MWI", "MEX", "MYS", "MOZ", "NAM", "NCL", "NER", "NFK", "NGA", "NIC", "NLD", "NOR", "NPL", "NRU", "NIU", "NZL", "OMN", "PAN", "PER", "PYF", "PNG", "PHL", "PAK", "POL", "SPM", "PCN", "PRI", "PSE", "PRT", "PLW", "PRY", "QAT", "REU", "ROU", "SRB", "RUS", "RWA", "SAU", "SLB", "SYC", "SDN", "SWE", "SGP", "SHN", "SVN", "SJM", "SVK", "SLE", "SMR", "SEN", "SOM", "SUR", "SSD", "STP", "SLV", "SXM", "SYR", "SWZ", "TCA", "TCD", "ATF", "TGO", "THA", "TJK", "TKL", "TLS", "TKM", "TUN", "TON", "TUR", "TTO", "TUV", "TWN", "TZA", "UKR", "UGA", "UMI", "USA", "URY", "UZB", "VAT", "VCT", "VEN", "VGB", "VIR", "VNM", "VUT", "WLF", "WSM", "YEM", "MYT", "ZAF", "ZMB", "ZWE", "ATB", "BYS", "CTE", "CSK", "DHY", "ATN", "AFI", "ATF", "DDR", "GEL", "JTN", "MID", "NHB", "PCI", "PCZ", "SKM", "RHO", "PUS", "HVO", "VDR", "WAK", "YMD"], view={"label": "Insured Country"}),
                "insured_postal_code": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Insured Postal Code"}),
                "insured_state_or_province": hx.Str(mode="input", default=None, optionality="optional", options_column="State", options_table="state_lookup", view={"label": "State"}),
                "is_admitted_or_surplus": hx.Str(mode="input", default="Admitted", optionality="required", options=["Admitted", "Admitted - LRE", "Surplus"], view={"label": "Admitted / Surplus"}),
                "is_free_trade_zone": hx.Bool(mode="input", default=False, optionality="required", view={"label": "Is Free-Trade Zone"}),
                "is_renewal": hx.Bool(mode="input", default=False, async_output=["start_renewal_task"], optionality="required", view={"label": "Renewal?"}),
                "underwriter": hx.Str(mode="input", default=None, allow_custom_value=True, optionality="optional", options_column="UnderwriterName", options_table="underwriter_list", view={"label": "Underwriter"}),
                "policy_reference": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Policy Reference", "options": {"read_only": {"read_only": True}}}),
                "facility_reference": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Facility Reference"}),
                "benchmark_class": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Benchmark Class"}),
                "uw_rationale": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Underwriter Rationale"}),
                "trifocus": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Trifocus"}),
                "rating_methodology": hx.Str(mode="input", default="Rater", options=["Rater", "Case Priced"], view={"label": "Rater Priced or Case Priced?"}),
                "is_case_priced": hx.Bool(mode="output", view={"label": "Is Case Priced"}),
                "is_rater_priced": hx.Bool(mode="output", view={"label": "Is Rater Priced"}),
            }),
            "layers": hx.List(mode="input", default_element_count=6, view={"label": "Layers"}, children={
                "limit": hx.Float(mode="input", default=0, optionality="optional", view={"label": "Full Layer\nLimit", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "excess": hx.Float(mode="output", optionality="optional", view={"label": "Attachment\nPoint", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "deductible": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Deductible", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "aggregate_limit": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Aggregate Limit", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "aggregate_excess": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Aggregate Excess", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "aggregate_deductible": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Aggregate Deductible", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "currency": hx.Str(mode="input", default=None, optionality="optional", options=["ADP", "AFA", "AON", "AOR", "ATS", "AZM", "BEF", "BGL", "BRE", "BUK", "BYB", "BYR", "CSD", "CSK", "CYP", "DDM", "DEM", "ECS", "EEK", "ESP", "FIM", "FRF", "GHC", "GRD", "GWP", "HRK", "IEP", "ITL", "LTL", "LUF", "LVL", "MGF", "MRO", "MTL", "MXP", "MZM", "NIC", "NLG", "PES", "PLZ", "PTE", "ROL", "RUR", "SDD", "SDP", "SIT", "SKK", "SRG", "STD", "SUR", "TRL", "UYP", "VEB", "VEF", "XEU", "YUM", "ZMK", "ZRN", "ZRZ", "ZWD", "ZWR", "AED", "AFN", "ALL", "AMD", "ANG", "AOA", "ARS", "AUD", "AWG", "AZN", "BAM", "BBD", "BDT", "BGN", "BHD", "BIF", "BMD", "BND", "BOB", "BOV", "BRL", "BSD", "BTN", "BWP", "BYN", "BZD", "CAD", "CDF", "CHE", "CHF", "CHW", "CLF", "CLP", "CNY", "COP", "COU", "CRC", "CUC", "CUP", "CVE", "CZK", "DJF", "DKK", "DOP", "DZD", "EGP", "ERN", "ETB", "EUR", "FJD", "FKP", "GBP", "GEL", "GHS", "GIP", "GMD", "GNF", "GTQ", "GYD", "HKD", "HNL", "HTG", "HUF", "IDR", "ILS", "INR", "IQD", "IRR", "ISK", "JMD", "JOD", "JPY", "KES", "KGS", "KHR", "KMF", "KPW", "KRW", "KWD", "KYD", "KZT", "LAK", "LBP", "LKR", "LRD", "LSL", "LYD", "MAD", "MDL", "MGA", "MKD", "MMK", "MNT", "MOP", "MRU", "MUR", "MVR", "MWK", "MXN", "MXV", "MYR", "MZN", "NAD", "NGN", "NIO", "NOK", "NPR", "NZD", "OMR", "PAB", "PEN", "PGK", "PHP", "PKR", "PLN", "PYG", "QAR", "RON", "RSD", "RUB", "RWF", "SAR", "SBD", "SCR", "SDG", "SEK", "SGD", "SHP", "SLE", "SLL", "SOS", "SRD", "SSP", "STN", "SVC", "SYP", "SZL", "THB", "TJS", "TMT", "TND", "TOP", "TRY", "TTD", "TWD", "TZS", "UAH", "UGX", "USD", "USN", "UYI", "UYU", "UYW", "UZS", "VED", "VES", "VND", "VUV", "WST", "XAF", "XAG", "XAU", "XBA", "XBB", "XBC", "XBD", "XCD", "XDR", "XOF", "XPD", "XPF", "XPT", "XSU", "XTS", "XUA", "XXX", "YER", "ZAR", "ZMW", "ZWL"], view={"label": "Currency"}),
                "section_reference": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Section Reference", "options": {"read_only": {"read_only": True}}}),
                "brokerage": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Brokerage", "format": {"output": "percent", "mantissa": 1}, "options": {"read_only": {"read_only": True}}}),
                "written_line": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Written Line", "format": {"output": "percent", "mantissa": 1}}),
                "premium": hx.Float(mode="input", default=0, optionality="optional", view={"label": "Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "status": hx.Str(mode="input", default="Submission", async_output=["expiring_policy_fetch_task", "start_renewal_task"], optionality="optional", options=["Submission", "Quote", "Bound", "Not Taken Up"], view={"label": "Deal Status"}),
                "is_primary_excess": hx.Str(mode="output", optionality="optional", options=["Primary", "Excess"], view={"label": "Primary / Excess"}),
                "benchmark_premium": hx.Float(mode="output", optionality="optional", view={"label": "Gross Benchmark Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "bpi": hx.Float(mode="output", optionality="optional", view={"label": "BPI", "format": {"output": "percent", "mantissa": 1}}),
                "bpi_pre_uw_adj": hx.Float(mode="output", optionality="optional", view={"label": "BPI (Pre-UW Adjustment)", "format": {"output": "percent", "mantissa": 1}}),
                "model_premium": hx.Float(mode="output", optionality="optional", view={"label": "Gross Model Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "unity_premium": hx.Float(mode="output", optionality="optional", view={"label": "Gross Unity Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "quoted_premium": hx.Float(mode="output", optionality="optional", view={"label": "Gross Quoted Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "technical_premium": hx.Float(mode="output", optionality="optional", view={"label": "Gross Technical Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "technical_premium_pre_uw_adj": hx.Float(mode="output", optionality="optional", view={"label": "Gross Technical Premium (Pre-UW Adjustment)", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "technical_premium_net": hx.Float(mode="output", optionality="optional", view={"label": "Net Technical Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "tpi": hx.Float(mode="output", optionality="optional", view={"label": "TPI", "format": {"output": "percent", "mantissa": 1}}),
                "tpi_pre_uw_adj": hx.Float(mode="output", optionality="optional", view={"label": "TPI (Pre-UW Adjustment)", "format": {"output": "percent", "mantissa": 1}}),
                "pflr_att": hx.Float(mode="output", optionality="optional", view={"label": "Priced-for Loss Ratio (Att)", "format": {"output": "percent", "mantissa": 1}}),
                "pflr_cat": hx.Float(mode="output", optionality="optional", view={"label": "Priced-for Loss Ratio (Cat)", "format": {"output": "percent", "mantissa": 1}}),
                "pflr": hx.Float(mode="output", optionality="optional", view={"label": "Priced-for Loss Ratio", "format": {"output": "percent", "mantissa": 1}}),
                "roc": hx.Float(mode="output", optionality="optional", view={"label": "Return on Capital", "format": {"output": "percent", "mantissa": 1}}),
                "uw_adj_impact": hx.Float(mode="output", optionality="optional", view={"label": "Impact of Underwriting Adjustments", "format": {"output": "percent", "mantissa": 1}}),
                "trifocus": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Trifocus"}),
                "expected_loss_cost": hx.Float(mode="output", optionality="optional", view={"label": "Expected Loss Cost", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "expected_loss_cost_pre_uw_adj": hx.Float(mode="output", optionality="optional", view={"label": "Expected Loss Cost (Pre-UW Ajustment)", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "rate_change": hx.Structure(view={"label": "Rate Change"}, children={
                    "exposure_change": hx.Structure(view={"label": "Exposure Change"}, children={
                        "model_calculated": hx.Float(mode="output", view={"label": "Model %", "format": {"output": "percent", "mantissa": 0}}),
                        "uw_selected": hx.Float(mode="override", view={"label": "Rate Change", "format": {"output": "percent", "mantissa": 2}}),
                        "comments": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Comment"}),
                    }),
                    "risk_characteristics_change": hx.Structure(view={"label": "Risk Characteristics Change"}, children={
                        "model_calculated": hx.Float(mode="output", view={"label": "Model %", "format": {"output": "percent", "mantissa": 0}}),
                        "uw_selected": hx.Float(mode="override", view={"label": "Rate Change", "format": {"output": "percent", "mantissa": 2}}),
                        "comments": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Comment"}),
                    }),
                    "limit_change": hx.Structure(view={"label": "Limit Change"}, children={
                        "model_calculated": hx.Float(mode="output", view={"label": "Model %", "format": {"output": "percent", "mantissa": 0}}),
                        "uw_selected": hx.Float(mode="override", view={"label": "Rate Change", "format": {"output": "percent", "mantissa": 2}}),
                        "comments": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Comment"}),
                    }),
                    "deductible_change": hx.Structure(view={"label": "Deductible Change"}, children={
                        "model_calculated": hx.Float(mode="output", view={"label": "Model %", "format": {"output": "percent", "mantissa": 0}}),
                        "uw_selected": hx.Float(mode="override", view={"label": "Rate Change", "format": {"output": "percent", "mantissa": 2}}),
                        "comments": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Comment"}),
                    }),
                    "terms_conditions_change": hx.Structure(view={"label": "Terms & Conditions Change"}, children={
                        "model_calculated": hx.Float(mode="output", view={"label": "Model %", "format": {"output": "percent", "mantissa": 0}}),
                        "uw_selected": hx.Float(mode="override", view={"label": "Rate Change", "format": {"output": "percent", "mantissa": 2}}),
                        "comments": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Comment"}),
                    }),
                    "other_change": hx.Structure(view={"label": "Other Change"}, children={
                        "model_calculated": hx.Float(mode="output", view={"label": "Model %", "format": {"output": "percent", "mantissa": 0}}),
                        "uw_selected": hx.Float(mode="override", view={"label": "Rate Change", "format": {"output": "percent", "mantissa": 2}}),
                        "comments": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Comment"}),
                    }),
                    "brokerage_change": hx.Structure(view={"label": "Brokerage Change"}, children={
                        "model_calculated": hx.Float(mode="output", view={"label": "Model %", "format": {"output": "percent", "mantissa": 0}}),
                        "uw_selected": hx.Float(mode="override", view={"label": "Rate Change", "format": {"output": "percent", "mantissa": 2}}),
                        "comments": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Comment"}),
                    }),
                    "rate_change": hx.Structure(view={"label": "Risk Adjusted Rate Change"}, children={
                        "model_calculated": hx.Float(mode="output", view={"label": "Model %", "format": {"output": "percent", "mantissa": 0}}),
                        "uw_selected": hx.Float(mode="output", view={"label": "Rate Change", "format": {"output": "percent", "mantissa": 2}}),
                        "comments": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Comment"}),
                        "lloyds_limit_attachment_point_change": hx.Float(mode="output", view={"label": "Lloyds's Limit Attachment Point Change", "format": {"output": "percent", "mantissa": 0}}),
                        "lloyds_breadth_of_cover_change": hx.Float(mode="output", view={"label": "Lloyds's Breadth of Cover Change", "format": {"output": "percent", "mantissa": 0}}),
                        "other_factors_change": hx.Float(mode="output", view={"label": "Other Factors Change", "format": {"output": "percent", "mantissa": 0}}),
                    }),
                    "expiring_layer": hx.Int(mode="input", default=1, optionality="optional", view={"label": "Expiring Layer"}),
                    "expiring_policy_reference": hx.Str(mode="input", default="", async_output=["expiring_policy_fetch_task", "start_renewal_task"], view={"label": "Expiring Policy Reference Number"}),
                    "expiring_policy_option_id": hx.Int(mode="override", async_input=["expiring_policy_fetch_task", "start_renewal_task"], view={"label": "Expiring Policy Option", "format": {"thousandSeparated": False}}),
                    "expiring_insured_name": hx.Str(mode="output", async_output=["expiring_policy_fetch_task", "start_renewal_task"], view={"label": "Expiring Insured Name"}),
                    "expiring_premium": hx.Float(mode="input", default=0, async_output=["expiring_policy_fetch_task", "start_renewal_task"], view={"label": "Expiring Premium (Beazley's Share)", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "expiring_brokerage": hx.Float(mode="input", default=0.15, async_output=["expiring_policy_fetch_task", "start_renewal_task"], view={"label": "Expiring Brokerage/Commission", "format": {"output": "percent", "mantissa": 1}}),
                    "expiring_premium_comment": hx.Str(mode="input", default="", view={"label": "Comment"}),
                    "expiring_beazley_share": hx.Float(mode="input", default=1, async_output=["expiring_policy_fetch_task", "start_renewal_task"], view={"label": "Expiring Beazley Share", "format": {"output": "percent", "mantissa": 0}}),
                    "expiring_excess": hx.Float(mode="input", default=0, async_output=["expiring_policy_fetch_task", "start_renewal_task"], view={"label": "Expiring Attachment Point", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "expiring_excess_social_engineering": hx.Float(mode="input", default=0, async_output=["expiring_policy_fetch_task", "start_renewal_task"], view={"label": "Expiring SE Attachment Point", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "expiring_excess_other_cov": hx.Float(mode="input", default=0, async_output=["expiring_policy_fetch_task", "start_renewal_task"], view={"label": "Expiring Other Cov Attachment Point", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "expiring_limit": hx.Float(mode="input", default=0, async_output=["expiring_policy_fetch_task", "start_renewal_task"], view={"label": "Expiring Full Layer Limit", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "expiring_limit_social_engineering": hx.Float(mode="input", default=0, async_output=["expiring_policy_fetch_task", "start_renewal_task"], view={"label": "Expiring Social Engineering Limit", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "expiring_limit_other_cov": hx.Float(mode="input", default=0, async_output=["expiring_policy_fetch_task", "start_renewal_task"], view={"label": "Expiring Other Coverage Limit", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "expiring_policy_term": hx.Float(mode="input", default=12, async_output=["expiring_policy_fetch_task", "start_renewal_task"], view={"label": "Expiring Policy Term (months)"}),
                    "expiring_premium_annual": hx.Float(mode="output", async_output=["expiring_policy_fetch_task", "start_renewal_task"], view={"label": "Expiring Annualized Premium"}),
                    "expiring_revenue": hx.Int(mode="input", default=0, async_output=["expiring_policy_fetch_task", "start_renewal_task"], view={"label": "Expiring Annual Revenue", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "expiring_assets": hx.Int(mode="input", default=0, async_output=["expiring_policy_fetch_task", "start_renewal_task"], view={"label": "Expiring Assets", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "expiring_employees": hx.Int(mode="input", default=0, async_output=["expiring_policy_fetch_task", "start_renewal_task"], view={"label": "Expiring Number of Officers and Employees", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "expiring_locations": hx.Int(mode="input", default=0, async_output=["expiring_policy_fetch_task", "start_renewal_task"], view={"label": "Expiring Number of Locations", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "expiring_beazley_layer": hx.Str(mode="input", default="", async_output=["expiring_policy_fetch_task", "start_renewal_task"], view={"label": "Expiring Beazley Layer"}),
                }),
                "is_bound": hx.Bool(mode="output"),
                "deviation_from_unity": hx.Float(mode="output", view={"label": "Deviation from Unity", "format": {"thousandSeparated": False, "mantissa": 3}}),
                "net_benchmark_premium": hx.Float(mode="output", view={"label": "Net Benchmark Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "net_technical_premium": hx.Float(mode="output", view={"label": "Net Technical Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "layer_label": hx.Str(mode="output", view={"label": "Layer Label"}),
                "limit_social_engineering": hx.Int(mode="input", default=0, view={"label": "Social Engineering\nLimit", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "limit_other_cov": hx.Int(mode="input", default=0, view={"label": "Other Coverages\nLimit", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "excess_social_engineering": hx.Int(mode="output", view={"label": "Attachment Point Social Engineering", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "excess_other_cov": hx.Int(mode="output", view={"label": "Attachment Point Other", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "layer_brokerage": hx.Float(mode="override", view={"label": "Commission", "format": {"output": "percent", "mantissa": 1}}),
                "layer_quality": hx.Bool(mode="input", default=False, view={"label": "Layer Premium\nIs Reliable"}),
                "lead_underwriter": hx.Str(mode="input", default="", view={"label": "Lead\nUnderwriter"}),
                "participating_cosurety": hx.Str(mode="input", default="", view={"label": "Participating\nCosurety"}),
                "lead_percentage": hx.Float(mode="input", default=1, view={"label": "Lead\nPercentage", "format": {"output": "percent", "mantissa": 0}}),
                "rate_per_m": hx.Float(mode="output", view={"label": "Rate per \nMillion", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "percent_underlying_rate": hx.Float(mode="output", view={"label": "Percent of\nUnderlying Rate", "format": {"output": "percent", "mantissa": 0}}),
                "internal_weighted_premium": hx.Float(mode="output", view={"label": "Internal\nWeighted Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "final_premium": hx.Float(mode="output", view={"label": "Final Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "final_premium_annual": hx.Float(mode="output", view={"label": "Final Premium (Annualized)", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "unity_premium_annual": hx.Float(mode="output", view={"label": "Unity Premium (Annualized)", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "priced_to_lr": hx.Float(mode="output"),
                "benchmark_lr": hx.Float(mode="output"),
                "technical_lr": hx.Float(mode="output"),
                "assumed_brokerage": hx.Float(mode="output"),
                "written_line_view": hx.Float(mode="output", optionality="optional", view={"label": "Written Line", "format": {"output": "percent", "mantissa": 1}}),
                "status_view": hx.Str(mode="output", view={"label": "Status"}),
                "pflr_pre_uw_adj": hx.Float(mode="output", view={"label": "Priced-for Loss Ratio (Pre-UW Adjustment)", "format": {"output": "percent", "mantissa": 1}}),
            }),
            "currencies": hx.Structure(view={"label": "Currencies"}, children={
                "target_currency": hx.Str(mode="input", default=None, optionality="optional", options=["ADP", "AFA", "AON", "AOR", "ATS", "AZM", "BEF", "BGL", "BRE", "BUK", "BYB", "BYR", "CSD", "CSK", "CYP", "DDM", "DEM", "ECS", "EEK", "ESP", "FIM", "FRF", "GHC", "GRD", "GWP", "HRK", "IEP", "ITL", "LTL", "LUF", "LVL", "MGF", "MRO", "MTL", "MXP", "MZM", "NIC", "NLG", "PES", "PLZ", "PTE", "ROL", "RUR", "SDD", "SDP", "SIT", "SKK", "SRG", "STD", "SUR", "TRL", "UYP", "VEB", "VEF", "XEU", "YUM", "ZMK", "ZRN", "ZRZ", "ZWD", "ZWR", "AED", "AFN", "ALL", "AMD", "ANG", "AOA", "ARS", "AUD", "AWG", "AZN", "BAM", "BBD", "BDT", "BGN", "BHD", "BIF", "BMD", "BND", "BOB", "BOV", "BRL", "BSD", "BTN", "BWP", "BYN", "BZD", "CAD", "CDF", "CHE", "CHF", "CHW", "CLF", "CLP", "CNY", "COP", "COU", "CRC", "CUC", "CUP", "CVE", "CZK", "DJF", "DKK", "DOP", "DZD", "EGP", "ERN", "ETB", "EUR", "FJD", "FKP", "GBP", "GEL", "GHS", "GIP", "GMD", "GNF", "GTQ", "GYD", "HKD", "HNL", "HTG", "HUF", "IDR", "ILS", "INR", "IQD", "IRR", "ISK", "JMD", "JOD", "JPY", "KES", "KGS", "KHR", "KMF", "KPW", "KRW", "KWD", "KYD", "KZT", "LAK", "LBP", "LKR", "LRD", "LSL", "LYD", "MAD", "MDL", "MGA", "MKD", "MMK", "MNT", "MOP", "MRU", "MUR", "MVR", "MWK", "MXN", "MXV", "MYR", "MZN", "NAD", "NGN", "NIO", "NOK", "NPR", "NZD", "OMR", "PAB", "PEN", "PGK", "PHP", "PKR", "PLN", "PYG", "QAR", "RON", "RSD", "RUB", "RWF", "SAR", "SBD", "SCR", "SDG", "SEK", "SGD", "SHP", "SLE", "SLL", "SOS", "SRD", "SSP", "STN", "SVC", "SYP", "SZL", "THB", "TJS", "TMT", "TND", "TOP", "TRY", "TTD", "TWD", "TZS", "UAH", "UGX", "USD", "USN", "UYI", "UYU", "UYW", "UZS", "VED", "VES", "VND", "VUV", "WST", "XAF", "XAG", "XAU", "XBA", "XBB", "XBC", "XBD", "XCD", "XDR", "XOF", "XPD", "XPF", "XPT", "XSU", "XTS", "XUA", "XXX", "YER", "ZAR", "ZMW", "ZWL"], view={"label": "Target Currency"}),
                "source_currency": hx.Str(mode="input", default=None, optionality="optional", options=["ADP", "AFA", "AON", "AOR", "ATS", "AZM", "BEF", "BGL", "BRE", "BUK", "BYB", "BYR", "CSD", "CSK", "CYP", "DDM", "DEM", "ECS", "EEK", "ESP", "FIM", "FRF", "GHC", "GRD", "GWP", "HRK", "IEP", "ITL", "LTL", "LUF", "LVL", "MGF", "MRO", "MTL", "MXP", "MZM", "NIC", "NLG", "PES", "PLZ", "PTE", "ROL", "RUR", "SDD", "SDP", "SIT", "SKK", "SRG", "STD", "SUR", "TRL", "UYP", "VEB", "VEF", "XEU", "YUM", "ZMK", "ZRN", "ZRZ", "ZWD", "ZWR", "AED", "AFN", "ALL", "AMD", "ANG", "AOA", "ARS", "AUD", "AWG", "AZN", "BAM", "BBD", "BDT", "BGN", "BHD", "BIF", "BMD", "BND", "BOB", "BOV", "BRL", "BSD", "BTN", "BWP", "BYN", "BZD", "CAD", "CDF", "CHE", "CHF", "CHW", "CLF", "CLP", "CNY", "COP", "COU", "CRC", "CUC", "CUP", "CVE", "CZK", "DJF", "DKK", "DOP", "DZD", "EGP", "ERN", "ETB", "EUR", "FJD", "FKP", "GBP", "GEL", "GHS", "GIP", "GMD", "GNF", "GTQ", "GYD", "HKD", "HNL", "HTG", "HUF", "IDR", "ILS", "INR", "IQD", "IRR", "ISK", "JMD", "JOD", "JPY", "KES", "KGS", "KHR", "KMF", "KPW", "KRW", "KWD", "KYD", "KZT", "LAK", "LBP", "LKR", "LRD", "LSL", "LYD", "MAD", "MDL", "MGA", "MKD", "MMK", "MNT", "MOP", "MRU", "MUR", "MVR", "MWK", "MXN", "MXV", "MYR", "MZN", "NAD", "NGN", "NIO", "NOK", "NPR", "NZD", "OMR", "PAB", "PEN", "PGK", "PHP", "PKR", "PLN", "PYG", "QAR", "RON", "RSD", "RUB", "RWF", "SAR", "SBD", "SCR", "SDG", "SEK", "SGD", "SHP", "SLE", "SLL", "SOS", "SRD", "SSP", "STN", "SVC", "SYP", "SZL", "THB", "TJS", "TMT", "TND", "TOP", "TRY", "TTD", "TWD", "TZS", "UAH", "UGX", "USD", "USN", "UYI", "UYU", "UYW", "UZS", "VED", "VES", "VND", "VUV", "WST", "XAF", "XAG", "XAU", "XBA", "XBB", "XBC", "XBD", "XCD", "XDR", "XOF", "XPD", "XPF", "XPT", "XSU", "XTS", "XUA", "XXX", "YER", "ZAR", "ZMW", "ZWL"], view={"label": "Source Currency"}),
                "multi_currency_support": hx.Bool(mode="input", default=False, optionality="required", view={"label": "Multi Currency Support"}),
                "rates": hx.List(mode="input", view={"label": "Rates"}, children={
                    "code": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Code"}),
                    "rate": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Rate", "format": {"thousandSeparated": False, "mantissa": 2}}),
                }),
            }),
            "experience_rating": hx.Structure(view={"label": "Experience Rating"}, children={
                "claims_available": hx.Bool(mode="input", default=False, view={"label": "Loss Data Avaialble"}),
                "claims_fgu": hx.Bool(mode="input", default=False, view={"label": "Claims From Ground Up"}),
                "claims_net_of_deductible": hx.Bool(mode="input", default=False, view={"label": "Are Claims net of Deductible"}),
            }),
            "yoa": hx.Int(mode="output", view={"label": "YOA"}),
            "database_id": hx.Int(mode="output", view={"label": "Database ID", "format": {"thousandSeparated": False, "mantissa": 0}}),
            "application_date": hx.Date(mode="input", default="2000-01-01", view={"label": "Application Date"}),
            "broker_contact": hx.Str(mode="input", default="", view={"label": "Broker Contact"}),
            "is_surplus": hx.Bool(mode="output"),
            "general_comments": hx.Str(mode="input", default="", view={"label": "Knowledge Of Insured"}),
            "term_adjustment_underlying": hx.Float(mode="output", view={"label": "Term Adjustment for the Underlying Layer"}),
            "term_adjustment": hx.Float(mode="output", view={"label": "Term Adjustment"}),
            "modifiers_dollar_value": hx.Float(mode="output", view={"label": "Schedule Rating Impact", "format": {"thousandSeparated": True, "mantissa": 0}}),
            "is_follow": hx.Bool(mode="input", default=False, view={"label": "(For cosurety only) Is Beazley following\nthe lead insurer's premium?"}),
            "lead_premium": hx.Float(mode="output", view={"format": {"thousandSeparated": True, "mantissa": 0}}),
            "has_social_engineering": hx.Bool(mode="input", default=True, view={"label": "Include Social Engineering Tower"}),
            "has_other_coverages": hx.Bool(mode="input", default=False, view={"label": "Include Other Coverages Tower"}),
            "entity_type": hx.Str(mode="output", view={"label": "Entity Type Factor"}),
            "excess_factor": hx.Float(mode="output", view={"label": "Excess Factor"}),
            "beazley_layer": hx.Str(mode="input", default=None, optionality="optional", options_data="../excess_layers", options_field="layer_label", view={"label": "Beazley Layer"}),
            "beazley_share": hx.Float(mode="input", default=1, view={"label": "Beazley Share", "format": {"output": "percent", "mantissa": 0}}),
            "beazley_pre_layer": hx.Str(mode="output", view={"label": "Preceding Layer"}),
            "underlying_brokerage": hx.Float(mode="override", view={"label": "Underlying Insurer Commission", "format": {"output": "percent", "mantissa": 1}}),
            "underlying_layer_limit": hx.Int(mode="output", view={"label": "Underlying Layer Limit"}),
            "underlying_premium": hx.Int(mode="output", view={"label": "Underlying Premium"}),
            "underlying_rate_per_m": hx.Int(mode="output", view={"label": "Underlying Rate per Million"}),
            "total_layer_limit": hx.Int(mode="output", view={"label": "Total Layer Limit"}),
            "beazley_limit": hx.Int(mode="output", view={"label": "Beazley's Limit"}),
            "beazley_layer_index": hx.Int(mode="output", view={"label": "Beazley Layer"}),
            "retention": hx.Structure(view={"label": "Retention"}, children={
                "limit": hx.Int(mode="input", default=0, view={"label": "Full Layer\nLimit", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "limit_social_engineering": hx.Int(mode="input", default=0, view={"label": "Social Engineering\nLimit", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "limit_other_cov": hx.Int(mode="input", default=0, view={"label": "Other Coverages\nLimit", "format": {"thousandSeparated": True, "mantissa": 0}}),
            }),
            "excess_layers": hx.List(mode="output", view={"label": "Excess Layers"}, children={
                "layer_label": hx.Str(mode="output", view={"label": "Layer Label"}),
            }),
            "underlying_inception_date": hx.Date(mode="override", view={"label": "Underlying Layer's Inception Date"}),
            "underlying_expiry_date": hx.Date(mode="override", view={"label": "Underlying Layer's Expiry Date"}),
            "social_engineering_sublimit": hx.Float(mode="input", default=0, view={"label": "SE Limit in Underlying Layer", "format": {"thousandSeparated": True, "mantissa": 0}}),
            "social_engineering_limit": hx.Float(mode="input", default=0, view={"label": "SE Limit in Beazley Layer", "format": {"thousandSeparated": True, "mantissa": 0}}),
            "social_engineering_allocation": hx.Float(mode="input", default=0, view={"label": "Allocation of SE in Underlying Premium", "format": {"output": "percent", "mantissa": 0}}),
            "rating_factors": hx.Structure(children={
                "claim_basis": hx.Str(mode="input", default_index=1, optionality="required", options_column="Claim Basis", options_table="claim_basis", view={"label": "Claim Basis"}),
                "endt_extensions": hx.Str(mode="input", default_index=0, optionality="required", options_column="Endorsements and Coverages Extensions", options_table="endt_extensions", view={"label": "Endorsements &\nCoverage Extensions"}),
                "sublimited_perils": hx.Str(mode="input", default="None", optionality="required", options_column="Sublimited Perils", options_table="sublimited_perils", view={"label": "Sublimited Perils"}),
                "other_on_premises": hx.Str(mode="input", default="None", optionality="required", options_column="Other Perils", options_table="other_perils", view={"label": "Other On-Premises Perils"}),
                "other_off_premises": hx.Str(mode="input", default="None", optionality="required", options_column="Other Perils", options_table="other_perils", view={"label": "Other Off-Premises Perils"}),
            }),
            "classification_peculiarities": hx.Structure(view={"label": "Classification Peculiarities"}, children={
                "available": hx.Bool(mode="output"),
                "minimum_state": hx.Float(mode="output", view={"label": "Max Credit", "format": {"output": "percent", "mantissa": 0}}),
                "maximum_state": hx.Float(mode="output", view={"label": "Max Debit", "format": {"output": "percent", "mantissa": 0}}),
                "selected": hx.Float(mode="input", default=0, view={"label": "Selected", "format": {"output": "percent", "mantissa": 1}}),
                "comment": hx.Str(mode="input", default="", view={"label": "Comment"}),
                "minimum_plan": hx.Float(mode="output", view={"label": "Max Credit Rate Plan", "format": {"output": "percent", "mantissa": 0}}),
                "maximum_plan": hx.Float(mode="output", view={"label": "Max Debit Rate Plan", "format": {"output": "percent", "mantissa": 0}}),
            }),
            "management": hx.Structure(view={"label": "Management"}, children={
                "available": hx.Bool(mode="output"),
                "minimum_state": hx.Float(mode="output", view={"label": "Max Credit", "format": {"output": "percent", "mantissa": 0}}),
                "maximum_state": hx.Float(mode="output", view={"label": "Max Debit", "format": {"output": "percent", "mantissa": 0}}),
                "selected": hx.Float(mode="input", default=0, view={"label": "Selected", "format": {"output": "percent", "mantissa": 1}}),
                "comment": hx.Str(mode="input", default="", view={"label": "Comment"}),
                "minimum_plan": hx.Float(mode="output", view={"label": "Max Credit Rate Plan", "format": {"output": "percent", "mantissa": 0}}),
                "maximum_plan": hx.Float(mode="output", view={"label": "Max Debit Rate Plan", "format": {"output": "percent", "mantissa": 0}}),
            }),
            "personnel": hx.Structure(view={"label": "Personnel"}, children={
                "available": hx.Bool(mode="output"),
                "minimum_state": hx.Float(mode="output", view={"label": "Max Credit", "format": {"output": "percent", "mantissa": 0}}),
                "maximum_state": hx.Float(mode="output", view={"label": "Max Debit", "format": {"output": "percent", "mantissa": 0}}),
                "selected": hx.Float(mode="input", default=0, view={"label": "Selected", "format": {"output": "percent", "mantissa": 1}}),
                "comment": hx.Str(mode="input", default="", view={"label": "Comment"}),
                "minimum_plan": hx.Float(mode="output", view={"label": "Max Credit Rate Plan", "format": {"output": "percent", "mantissa": 0}}),
                "maximum_plan": hx.Float(mode="output", view={"label": "Max Debit Rate Plan", "format": {"output": "percent", "mantissa": 0}}),
            }),
            "location": hx.Structure(view={"label": "Location"}, children={
                "available": hx.Bool(mode="output"),
                "minimum_state": hx.Float(mode="output", view={"label": "Max Credit", "format": {"output": "percent", "mantissa": 0}}),
                "maximum_state": hx.Float(mode="output", view={"label": "Max Debit", "format": {"output": "percent", "mantissa": 0}}),
                "selected": hx.Float(mode="input", default=0, view={"label": "Selected", "format": {"output": "percent", "mantissa": 1}}),
                "comment": hx.Str(mode="input", default="", view={"label": "Comment"}),
                "minimum_plan": hx.Float(mode="output", view={"label": "Max Credit Rate Plan", "format": {"output": "percent", "mantissa": 0}}),
                "maximum_plan": hx.Float(mode="output", view={"label": "Max Debit Rate Plan", "format": {"output": "percent", "mantissa": 0}}),
            }),
            "response_to_losses": hx.Structure(view={"label": "Response To Losses"}, children={
                "available": hx.Bool(mode="output"),
                "minimum_state": hx.Float(mode="output", view={"label": "Max Credit", "format": {"output": "percent", "mantissa": 0}}),
                "maximum_state": hx.Float(mode="output", view={"label": "Max Debit", "format": {"output": "percent", "mantissa": 0}}),
                "selected": hx.Float(mode="input", default=0, view={"label": "Selected", "format": {"output": "percent", "mantissa": 1}}),
                "comment": hx.Str(mode="input", default="", view={"label": "Comment"}),
                "minimum_plan": hx.Float(mode="output", view={"label": "Max Credit Rate Plan", "format": {"output": "percent", "mantissa": 0}}),
                "maximum_plan": hx.Float(mode="output", view={"label": "Max Debit Rate Plan", "format": {"output": "percent", "mantissa": 0}}),
            }),
            "endorsements": hx.Structure(view={"label": "Endorsements"}, children={
                "available": hx.Bool(mode="output"),
                "minimum_state": hx.Float(mode="output", view={"label": "Max Credit", "format": {"output": "percent", "mantissa": 0}}),
                "maximum_state": hx.Float(mode="output", view={"label": "Max Debit", "format": {"output": "percent", "mantissa": 0}}),
                "selected": hx.Float(mode="input", default=0, view={"label": "Selected", "format": {"output": "percent", "mantissa": 1}}),
                "comment": hx.Str(mode="input", default="", view={"label": "Comment"}),
                "minimum_plan": hx.Float(mode="output", view={"label": "Max Credit Rate Plan", "format": {"output": "percent", "mantissa": 0}}),
                "maximum_plan": hx.Float(mode="output", view={"label": "Max Debit Rate Plan", "format": {"output": "percent", "mantissa": 0}}),
            }),
            "expense_modification": hx.Structure(view={"label": "Expense Modification"}, children={
                "available": hx.Bool(mode="output"),
                "minimum_state": hx.Float(mode="output", view={"label": "Max Credit", "format": {"output": "percent", "mantissa": 0}}),
                "maximum_state": hx.Float(mode="output", view={"label": "Max Debit", "format": {"output": "percent", "mantissa": 0}}),
                "selected": hx.Float(mode="input", default=0, view={"label": "Selected", "format": {"output": "percent", "mantissa": 1}}),
                "comment": hx.Str(mode="input", default="", view={"label": "Comment"}),
                "minimum_plan": hx.Float(mode="output", view={"label": "Max Credit Rate Plan", "format": {"output": "percent", "mantissa": 0}}),
                "maximum_plan": hx.Float(mode="output", view={"label": "Max Debit Rate Plan", "format": {"output": "percent", "mantissa": 0}}),
            }),
            "total_modifiers": hx.Structure(view={"label": "Total Modifiers"}, children={
                "minimum_state": hx.Float(mode="output", view={"label": "Max Credit", "format": {"output": "percent", "mantissa": 0}}),
                "maximum_state": hx.Float(mode="output", view={"label": "Max Debit", "format": {"output": "percent", "mantissa": 0}}),
                "selected": hx.Float(mode="output", view={"label": "Selected", "format": {"output": "percent", "mantissa": 1}}),
            }),
            "total_unbounded": hx.Float(mode="output", view={"label": "Total Unbounded", "format": {"output": "percent", "mantissa": 0}}),
            "mod_factor": hx.Float(mode="output", view={"label": "Factor"}),
            "eligibility_min_before": hx.Float(mode="output", view={"label": "Eligibility Requirement (Before)", "format": {"thousandSeparated": True, "mantissa": 0}}),
            "eligibility_min_after": hx.Float(mode="output", view={"label": "Eligibility Requirement (After)", "format": {"thousandSeparated": True, "mantissa": 0}}),
            "expense_mod_factor": hx.Float(mode="output", view={"label": "Expense Modification Factor"}),
            "expense_mod_flag": hx.Bool(mode="output"),
            "surplus_deviation_factor": hx.Float(mode="input", default=1, view={"label": "Surplus Deviation", "format": {"thousandSeparated": False, "mantissa": 3}}),
            "options": hx.List(mode="input", default_element_count=1, view={"label": "Options"}, children={
                "quoted_premium": hx.Float(mode="input", default=0, view={"label": "Gross Quoted Premium (Case Priced)", "format": {"thousandSeparated": True, "mantissa": 0}, "options": {"read_only": {"read_only": True}}}),
                "benchmark_premium": hx.Float(mode="output", view={"label": "Gross Benchmark Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "technical_premium": hx.Float(mode="output", view={"label": "Gross Technical Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "status": hx.Str(mode="input", default="Assessment Pending", options=["Assessment Pending", "Rating", "Quoted", "Bound", "Post Bind Complete", "Declined", "Not Taken Up"], view={"label": "Status"}),
                "section_reference": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Section Reference", "options": {"read_only": {"read_only": True}}}),
                "bpi": hx.Float(mode="input", default=0, view={"label": "BPI", "format": {"output": "percent", "mantissa": 1}, "options": {"read_only": {"read_only": True}}}),
                "tpi": hx.Float(mode="output", view={"label": "TPI", "format": {"output": "percent", "mantissa": 1}}),
                "pflr": hx.Float(mode="output", view={"label": "Priced-for Loss Ratio", "format": {"output": "percent", "mantissa": 1}}),
                "roc": hx.Float(mode="output", view={"label": "Return on Capital", "format": {"output": "percent", "mantissa": 1}}),
                "written_line": hx.Float(mode="input", default=1, view={"label": "Written Line", "format": {"output": "percent", "mantissa": 1}, "options": {"read_only": {"read_only": True}}}),
                "brokerage": hx.Float(mode="input", default=0, view={"label": "Brokerage (excl. PC's)", "format": {"output": "percent", "mantissa": 1}, "options": {"read_only": {"read_only": True}}}),
                "status_view": hx.Str(mode="output", view={"label": "Status"}),
            }),
            "rate_change": hx.Structure(children={
                "show_option_1": hx.Bool(mode="output"),
                "show_option_2": hx.Bool(mode="output"),
                "show_option_3": hx.Bool(mode="output"),
                "show_option_4": hx.Bool(mode="output"),
                "show_option_5": hx.Bool(mode="output"),
                "show_option_6": hx.Bool(mode="output"),
            }),
            "chosen_date": hx.Str(mode="override", options=["2024_06_01", "2025_01_01"], view={"label": "Chosen Data"}),
            "conditions_met": hx.Bool(mode="output", view={"label": "Are Conditions Met"}),
            "is_excess_surplus": hx.Bool(mode="output", view={"label": "Is Excess Surplus"}),
            "not_excess_surplus": hx.Bool(mode="output", view={"label": "Not Excess Surplus"}),
            "do_excess_rating": hx.Bool(mode="output"),
            "admitted_excess": hx.Structure(children={
                "primary_limit": hx.Structure(view={"label": "Primary Limit"}, children={
                    "value": hx.Float(mode="output", optionality="optional", view={"label": "Value", "format": {"thousandSeparated": True, "mantissa": 0}}),
                }),
                "primary_retention": hx.Structure(view={"label": "Primary Retention"}, children={
                    "value": hx.Float(mode="output", optionality="optional", view={"label": "Value", "format": {"thousandSeparated": True, "mantissa": 0}}),
                }),
                "primary_premium": hx.Structure(view={"label": "Primary Premium"}, children={
                    "value": hx.Float(mode="output", optionality="optional", view={"label": "Value", "format": {"thousandSeparated": True, "mantissa": 0}}),
                }),
                "excess_limit": hx.Structure(view={"label": "Excess Limit"}, children={
                    "value": hx.Float(mode="output", optionality="optional", view={"label": "Value", "format": {"thousandSeparated": True, "mantissa": 0}}),
                }),
                "excess_attachment_point": hx.Structure(view={"label": "Excess Attachment Point"}, children={
                    "value": hx.Float(mode="output", optionality="optional", view={"label": "Value", "format": {"thousandSeparated": True, "mantissa": 0}}),
                }),
                "no_of_policies_sharing_single_limit": hx.Structure(view={"label": "Number of Coverages Under Same Aggregate"}, children={
                    "value": hx.Int(mode="output", optionality="optional", options=[1, 2, 3, 4, 5, 6], view={"label": "Value"}),
                }),
                "large_loss_potential": hx.Structure(view={"label": "Large Loss Potential"}, children={
                    "value": hx.Str(mode="output", optionality="optional", options=["Above Average", "Average", "Below Average"], view={"label": "Value"}),
                }),
                "primary_rate_adequacy_correction": hx.Structure(view={"label": "Primary Rate Adequacy Correction"}, children={
                    "value": hx.Float(mode="output", optionality="optional", view={"label": "Value", "format": {"output": "percent", "mantissa": 0}}),
                    "min": hx.Float(mode="output", view={"label": "Min", "format": {"output": "percent", "mantissa": 0}}),
                    "max": hx.Float(mode="output", view={"label": "Max", "format": {"output": "percent", "mantissa": 0}}),
                }),
                "industry_sector_risk_level": hx.Structure(view={"label": "Industry Sector Risk Level"}, children={
                    "value": hx.Str(mode="output", optionality="optional", options=["Low Risk", "Normal Risk", "High Risk"], view={"label": "Value"}),
                }),
                "industry_sector_factor": hx.Structure(view={"label": "Industry Sector Factor"}, children={
                    "value": hx.Float(mode="output", optionality="optional", view={"label": "Value", "format": {"output": "percent", "mantissa": 0}}),
                    "min": hx.Float(mode="output", view={"label": "Min", "format": {"output": "percent", "mantissa": 0}}),
                    "max": hx.Float(mode="output", view={"label": "Max", "format": {"output": "percent", "mantissa": 0}}),
                    "default": hx.Float(mode="output", view={"label": "Default", "format": {"output": "percent", "mantissa": 0}}),
                }),
                "company_risk_level": hx.Structure(view={"label": "Company Risk Level"}, children={
                    "value": hx.Str(mode="output", optionality="optional", options=["Low Risk", "Normal Risk", "High Risk"], view={"label": "Value"}),
                }),
                "company_factor": hx.Structure(view={"label": "Company Factor"}, children={
                    "value": hx.Float(mode="output", optionality="optional", view={"label": "Value", "format": {"output": "percent", "mantissa": 0}}),
                    "min": hx.Float(mode="output", view={"label": "Min", "format": {"output": "percent", "mantissa": 0}}),
                    "max": hx.Float(mode="output", view={"label": "Max", "format": {"output": "percent", "mantissa": 0}}),
                    "default": hx.Float(mode="output", view={"label": "Default", "format": {"output": "percent", "mantissa": 0}}),
                }),
                "litigation_risk_level": hx.Structure(view={"label": "Litigation Risk Level"}, children={
                    "value": hx.Str(mode="output", optionality="optional", options=["Low Risk", "Normal Risk", "High Risk"], view={"label": "Value"}),
                }),
                "litigation_factor": hx.Structure(view={"label": "Litigation Factor"}, children={
                    "value": hx.Float(mode="output", optionality="optional", view={"label": "Value", "format": {"output": "percent", "mantissa": 0}}),
                    "min": hx.Float(mode="output", view={"label": "Min", "format": {"output": "percent", "mantissa": 0}}),
                    "max": hx.Float(mode="output", view={"label": "Max", "format": {"output": "percent", "mantissa": 0}}),
                    "default": hx.Float(mode="output", view={"label": "Default", "format": {"output": "percent", "mantissa": 0}}),
                }),
                "fl_schedule_rating_factor": hx.Structure(view={"label": "FL Schedule Rating Factor"}, children={
                    "value": hx.Float(mode="output", optionality="optional", view={"label": "Value", "format": {"output": "percent", "mantissa": 0}}),
                    "min": hx.Float(mode="output", view={"label": "Min", "format": {"output": "percent", "mantissa": 0}}),
                    "max": hx.Float(mode="output", view={"label": "Max", "format": {"output": "percent", "mantissa": 0}}),
                }),
                "surplus_deviation": hx.Structure(view={"label": "Surplus Deviation"}, children={
                    "value": hx.Float(mode="input", default=0, optionality="optional", view={"label": "Value", "format": {"output": "percent", "mantissa": 0}}),
                }),
                "additional_rating_factor": hx.Structure(view={"label": "Additional Rating Factor"}, children={
                    "value": hx.Float(mode="output", view={"label": "Value", "format": {"thousandSeparated": True, "mantissa": 0}}),
                }),
                "model_premium": hx.Structure(view={"label": "Annualised Plan Premium"}, children={
                    "value": hx.Float(mode="output", view={"label": "Value", "format": {"thousandSeparated": True, "mantissa": 0}}),
                }),
                "max_round_down": hx.Structure(view={"label": "Max Round Down"}, children={
                    "value": hx.Float(mode="output", view={"label": "Value", "format": {"thousandSeparated": True, "mantissa": 0}}),
                }),
                "max_round_up": hx.Structure(view={"label": "Max Round Up"}, children={
                    "value": hx.Float(mode="output", view={"label": "Value", "format": {"thousandSeparated": True, "mantissa": 0}}),
                }),
                "rounded_premium": hx.Structure(view={"label": "Annualised Rounded Plan Premium"}, children={
                    "value": hx.Float(mode="override", view={"label": "Value", "format": {"thousandSeparated": True, "mantissa": 0}}),
                }),
            }),
            "exposure_change": hx.Structure(children={
                "employee_count": hx.Structure(view={"label": "Employee Count"}, children={
                    "renewal": hx.Float(mode="input", default=0, view={"label": "Renewal"}),
                    "expiry": hx.Float(mode="input", default=0, view={"label": "Expiry"}),
                }),
                "location_count": hx.Structure(view={"label": "Location Count"}, children={
                    "renewal": hx.Float(mode="input", default=0, view={"label": "Renewal"}),
                    "expiry": hx.Float(mode="input", default=0, view={"label": "Expiry"}),
                }),
            }),
        }),
        "info_date": hx.Str(mode="output"),
        "total_adj_factor": hx.Float(mode="output"),
        "beazley_layer_index": hx.Int(mode="output"),
        "show_rate_change": hx.Bool(mode="output"),
        "expiring_policy_option_id": hx.Int(mode="output", async_input=["expiring_policy_fetch_task", "start_renewal_task"]),
        "debug_num": hx.Float(mode="output", view={"format": {"thousandSeparated": False, "mantissa": 3}}),
        "debug_num1": hx.Float(mode="output", view={"format": {"thousandSeparated": False, "mantissa": 3}}),
        "debug_num2": hx.Float(mode="output", view={"format": {"thousandSeparated": False, "mantissa": 3}}),
        "debug_num3": hx.Float(mode="output", view={"format": {"thousandSeparated": False, "mantissa": 3}}),
        "debug_num4": hx.Float(mode="output", view={"format": {"thousandSeparated": False, "mantissa": 3}}),
        "debug_num5": hx.Float(mode="output", view={"format": {"thousandSeparated": False, "mantissa": 3}}),
        "debug_str": hx.Str(mode="output"),
        "debug_task_input": hx.Float(mode="input", default=0, async_input=["test_async_task"], view={"format": {"thousandSeparated": False, "mantissa": 1}}),
        "debug_task_output": hx.Float(mode="input", default=0, async_output="test_async_task", view={"format": {"thousandSeparated": False, "mantissa": 1}}),
        "model_state": hx.Structure(children={
            "pressed_start_renewal_task": hx.Bool(mode="output", async_output=["start_renewal_task"]),
            "show_landing_page": hx.Bool(mode="output"),
            "show_after_landing_page": hx.Bool(mode="output"),
        }),
        "bug_report": hx.Structure(children={
            "helper_text": hx.Str(mode="output", optionality="optional"),
            "recipient_email": hx.Str(mode="output", async_input=["send_bug_report_task"], async_output=["new_bug_report_task", {"task": "send_bug_report_task", "reset": False}, "cancel_bug_report_task"], view={"label": "Recipient Email"}),
            "cc_email": hx.Str(mode="output", async_input=["send_bug_report_task"], async_output=["new_bug_report_task", {"task": "send_bug_report_task", "reset": False}, "cancel_bug_report_task"], view={"label": "CC Email"}),
            "subject_line": hx.Str(mode="output", async_input=["send_bug_report_task"], async_output=["new_bug_report_task", {"task": "send_bug_report_task", "reset": False}, "cancel_bug_report_task"], view={"label": "Subject Line"}),
            "summary": hx.Str(mode="input", default="", async_input=["send_bug_report_task"], async_output=["new_bug_report_task", {"task": "send_bug_report_task", "reset": False}, "cancel_bug_report_task"], view={"multiline": True}),
            "email_body": hx.Str(mode="input", default=None, async_input=["send_bug_report_task"], async_output=["new_bug_report_task", {"task": "send_bug_report_task", "reset": False}, "cancel_bug_report_task"], optionality="optional", view={"label": "Details"}),
            "inputs_outputs_file_show": hx.Bool(mode="output", async_output=["new_bug_report_task"]),
            "inputs_outputs_file": hx.File(mode="output", async_output=["generate_bug_report_task", "cancel_bug_report_task", "send_bug_report_task"], file_name="inputs_outputs.json", view={"label": "Input/Outputs File"}),
            "file_helper_text": hx.Str(mode="input", default="**Note: Make sure to press the \"Upload File\" button to attach the file**", view={"options": {"read_only": {"read_only": True}}}),
            "files_shown": hx.Int(mode="input", default=1, async_output=["new_bug_report_task", {"task": "add_additional_file_task", "reset": False}]),
            "screenshot_files": hx.Structure(children={
                "f1": hx.Structure(children={
                    "file": hx.File(mode="input", async_input=["add_additional_file_task", "send_bug_report_task"], async_output=["new_bug_report_task", "cancel_bug_report_task"]),
                    "show_file": hx.Bool(mode="input", default=True, async_output=["new_bug_report_task", {"task": "add_additional_file_task", "reset": False}]),
                    "show_text": hx.Bool(mode="input", default=True, async_output=["new_bug_report_task", {"task": "add_additional_file_task", "reset": False}]),
                }),
                "f2": hx.Structure(children={
                    "file": hx.File(mode="input", async_input=["add_additional_file_task", "send_bug_report_task"], async_output=["new_bug_report_task", "cancel_bug_report_task"]),
                    "show_file": hx.Bool(mode="input", default=False, async_output=["new_bug_report_task", {"task": "add_additional_file_task", "reset": False}]),
                    "show_text": hx.Bool(mode="input", default=False, async_output=["new_bug_report_task", {"task": "add_additional_file_task", "reset": False}]),
                }),
                "f3": hx.Structure(children={
                    "file": hx.File(mode="input", async_input=["add_additional_file_task", "send_bug_report_task"], async_output=["new_bug_report_task", "cancel_bug_report_task"]),
                    "show_file": hx.Bool(mode="input", default=False, async_output=["new_bug_report_task", {"task": "add_additional_file_task", "reset": False}]),
                    "show_text": hx.Bool(mode="input", default=False, async_output=["new_bug_report_task", {"task": "add_additional_file_task", "reset": False}]),
                }),
                "f4": hx.Structure(children={
                    "file": hx.File(mode="input", async_input=["add_additional_file_task", "send_bug_report_task"], async_output=["new_bug_report_task", "cancel_bug_report_task"]),
                    "show_file": hx.Bool(mode="input", default=False, async_output=["new_bug_report_task", {"task": "add_additional_file_task", "reset": False}]),
                    "show_text": hx.Bool(mode="input", default=False, async_output=["new_bug_report_task", {"task": "add_additional_file_task", "reset": False}]),
                }),
                "f5": hx.Structure(children={
                    "file": hx.File(mode="input", async_input=["add_additional_file_task", "send_bug_report_task"], async_output=["new_bug_report_task", "cancel_bug_report_task"]),
                    "show_file": hx.Bool(mode="input", default=False, async_output=["new_bug_report_task", {"task": "add_additional_file_task", "reset": False}]),
                    "show_text": hx.Bool(mode="input", default=False, async_output=["new_bug_report_task", {"task": "add_additional_file_task", "reset": False}]),
                }),
            }),
            "commenced_flag": hx.Bool(mode="output", async_output=["new_bug_report_task", {"task": "send_bug_report_task", "reset": False}, "cancel_bug_report_task"], view={"label": "Commenced"}),
            "inputs_outputs": hx.Str(mode="output", async_input=["generate_bug_report_task", "cancel_bug_report_task", "new_bug_report_task", "send_bug_report_task"], view={"label": "Inputs/Outputs"}),
            "show_email": hx.Bool(mode="input", default=False),
            "model_name": hx.Str(mode="output", async_input=["send_bug_report_task"], async_output=["new_bug_report_task", {"task": "send_bug_report_task", "reset": False}, "cancel_bug_report_task"]),
        }),
    })
