raise Exception("""This file is generated

Do not edit manually as all of the changes will be lost.
This is the static version of your Data Schema that will allow easier debugging.
""")

import hx_data_schema as hx


@hx.data_schema
def hx_calculation_legacy_initial_premium():
    return hx.Structure(children={
        "hx_core": hx.Structure(children={
            "inception_date": hx.Date(default="2025-01-01", mode="input", view={"label": "Inception Date"}, async_input=["rarc_task"]),
            "expiry_date": hx.Date(default="2026-01-01", mode="input", view={"label": "Expiry Date"}, async_input=["rarc_task"]),
            "model_premium": hx.Float(mode="output", view={"label": "Model Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
            "charged_premium": hx.Float(mode="output", view={"label": "Charged Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
            "premium_currency": hx.Str(mode="output", view={"label": "Premium Currency"}),
            "ulr": hx.Float(mode="output", view={"label": "ULR", "format": {"output": "percent", "mantissa": 1}}),
            "class_code": hx.Str(mode="output", view={"label": "Class Code"}),
        }, view={"label": "Hx Core"}),
        "cds": hx.Structure(view={"label": "cds"}, children={
            "key_industry": hx.Structure(view={"label": "Key Industry"}, children={
                "code_type": hx.Str(mode="input", default=None, optionality="optional", options=["NAICS", "SIC_USA", "SIC_UK", "UW Defined"], view={"label": "Industry Code Type"}),
                "code": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Industry Code"}),
                "code_name": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Industry Code Name"}),
            }),
            "exposure": hx.Structure(view={"label": "Exposure"}, children={
                "aggregate": hx.Structure(view={"label": "Aggregate"}, children={
                    "example_aggregate_exposure": hx.Float(mode="input", default=0, view={"label": "Agg Exposure", "format": {"thousandSeparated": True, "mantissa": 0}}),
                }),
                "granular": hx.Structure(view={"label": "Granular"}, children={
                    "example_exposure": hx.List(mode="input", async_input=["rarc_task"], children={
                        "country": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Country"}),
                        "city": hx.Str(mode="input", default=None, optionality="optional", view={"label": "City"}),
                        "type": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Type"}),
                        "tiv": hx.Float(mode="input", default=None, optionality="optional", view={"label": "TIV", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    }),
                    "total_sum_insured_label": hx.Str(mode="output"),
                    "average_sum_insured_label": hx.Str(mode="output"),
                    "benchmark_premium_label": hx.Str(mode="output"),
                    "rov_hovertext": hx.Str(mode="output"),
                    "number_of_units": hx.Structure(view={"label": "Number of Units"}, children={
                        "rov": hx.Int(mode="input", default=0, async_input=["rarc_task"], validation={"min_value": 0}, view={"label": "ROV", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "auv": hx.Int(mode="input", default=0, async_input=["rarc_task"], validation={"min_value": 0}, view={"label": "AUV", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "seismic_towed": hx.Int(mode="input", default=0, async_input=["rarc_task"], validation={"min_value": 0}, view={"label": "Seismic-Towed", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "seismic_ocean_bottom": hx.Int(mode="input", default=0, async_input=["rarc_task"], validation={"min_value": 0}, view={"label": "Seismic-Ocean Bottom", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "diving_oceanographic": hx.Int(mode="input", default=0, async_input=["rarc_task"], validation={"min_value": 0}, view={"label": "Diving & Oceanographic", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "submersibles": hx.Int(mode="input", default=0, async_input=["rarc_task"], validation={"min_value": 0}, view={"label": "Submersibles", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "other": hx.Int(mode="input", default=0, async_input=["rarc_task"], validation={"min_value": 0}, view={"label": "Other", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "total": hx.Float(mode="output", view={"label": "Total", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    }),
                    "total_sum_insured": hx.Structure(view={"label": "Total Sum Insured"}, children={
                        "rov": hx.Float(mode="input", default=0, async_input=["rarc_task"], validation={"min_value": 0.0}, view={"label": "ROV", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "auv": hx.Float(mode="input", default=0, async_input=["rarc_task"], validation={"min_value": 0.0}, view={"label": "AUV", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "seismic_towed": hx.Float(mode="input", default=0, async_input=["rarc_task"], validation={"min_value": 0.0}, view={"label": "Seismic-Towed", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "seismic_ocean_bottom": hx.Float(mode="input", default=0, async_input=["rarc_task"], validation={"min_value": 0.0}, view={"label": "Seismic-Ocean Bottom", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "diving_oceanographic": hx.Float(mode="input", default=0, async_input=["rarc_task"], validation={"min_value": 0.0}, view={"label": "Diving & Oceanographic", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "submersibles": hx.Float(mode="input", default=0, async_input=["rarc_task"], validation={"min_value": 0.0}, view={"label": "Submersibles", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "other": hx.Float(mode="input", default=0, async_input=["rarc_task"], validation={"min_value": 0.0}, view={"label": "Other", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "total": hx.Float(mode="output", view={"label": "Total", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    }),
                    "average_sum_insured_per_unit": hx.Structure(view={"label": "Average Sum Insured per Unit"}, children={
                        "rov": hx.Float(mode="output", view={"label": "ROV", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "auv": hx.Float(mode="output", view={"label": "AUV", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "seismic_towed": hx.Float(mode="output", view={"label": "Seismic-Towed", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "seismic_ocean_bottom": hx.Float(mode="output", view={"label": "Seismic-Ocean Bottom", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "diving_oceanographic": hx.Float(mode="output", view={"label": "Diving & Oceanographic", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "submersibles": hx.Float(mode="output", view={"label": "Submersibles", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "other": hx.Float(mode="output", view={"label": "Other", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    }),
                    "excess_per_loss": hx.Structure(view={"label": "Excess (per loss)"}, children={
                        "rov": hx.Float(mode="input", default=0, async_input=["rarc_task"], validation={"min_value": 0.0}, view={"label": "ROV", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "auv": hx.Float(mode="output", async_input=["rarc_task"], validation={"min_value": 0.0}, view={"label": "AUV", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "seismic_towed": hx.Float(mode="input", default=0, async_input=["rarc_task"], validation={"min_value": 0.0}, view={"label": "Seismic-Towed", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "seismic_ocean_bottom": hx.Float(mode="input", default=0, async_input=["rarc_task"], validation={"min_value": 0.0}, view={"label": "Seismic-Ocean Bottom", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "diving_oceanographic": hx.Float(mode="input", default=0, async_input=["rarc_task"], validation={"min_value": 0.0}, view={"label": "Diving & Oceanographic", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "submersibles": hx.Float(mode="input", default=0, async_input=["rarc_task"], validation={"min_value": 0.0}, view={"label": "Submersibles", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "other": hx.Float(mode="input", default=0, async_input=["rarc_task"], validation={"min_value": 0.0}, view={"label": "Other", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    }),
                    "excess_per_loss_auv": hx.Structure(view={"label": "Excess (per loss)"}, children={
                        "normal_ops": hx.Float(mode="input", default=50000, async_input=["rarc_task"], validation={"min_value": 0.0}, view={"label": "Normal Operation", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "launch_recovery": hx.Float(mode="input", default=100000, async_input=["rarc_task"], validation={"min_value": 0.0}, view={"label": "Launch & recovery", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    }),
                    "benchmark_premium": hx.Structure(view={"label": "Benchmark Premium"}, children={
                        "rov": hx.Float(mode="output", view={"label": "ROV", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "auv": hx.Float(mode="output", view={"label": "AUV", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "seismic_towed": hx.Float(mode="output", view={"label": "Seismic-Towed", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "seismic_ocean_bottom": hx.Float(mode="output", view={"label": "Seismic-Ocean Bottom", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "diving_oceanographic": hx.Float(mode="output", view={"label": "Diving & Oceanographic", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "submersibles": hx.Float(mode="output", view={"label": "Submersibles", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "other": hx.Float(mode="output", view={"label": "Other", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "total": hx.Float(mode="output", view={"label": "Total", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    }),
                    "type_of_work": hx.Str(mode="input", default="Oil & Gas", async_input=["rarc_task"], options_column="Type of Work", options_table="lst_type_of_work", view={"label": "Type of Work"}),
                    "ice_debris_other_traffic": hx.Str(mode="input", default="None", async_input=["rarc_task"], options_column="Ice, debris, other marine traffic", options_table="lst_ice_debris_traffic", view={"label": "Will there be ice, debris or other marine traffic?"}),
                    "experience_level": hx.Str(mode="input", default="Average", async_input=["rarc_task"], options_column="Experience Category", options_table="lst_experience_category", view={"label": "Experience of people operating the vessels"}),
                    "usage_factor": hx.Float(mode="input", default=0.6, async_input=["rarc_task"], view={"label": "Usage %", "format": {"output": "percent", "mantissa": 1}}),
                    "uw_adjustment": hx.Float(mode="input", default=0, async_input=["rarc_task"], view={"label": "Adjustment (%)", "format": {"output": "percent", "mantissa": 1}}),
                    "uw_adjustment_rationale": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Adjustment Rationale"}),
                    "total_expected_loss_gbp": hx.Float(mode="output"),
                    "total_expected_loss": hx.Float(mode="output"),
                }),
            }),
            "standard_fields": hx.Structure(view={"label": "Standard Fields"}, children={
                "insured_name": hx.Str(mode="input", default=None, allow_custom_value=True, async_input=["start_renewal_task"], optionality="optional", options_column="insured_name", options_table="insured_names", view={"label": "Insured Name"}),
                "broker": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Broker Name"}),
                "expiry_date": hx.Date(mode="output", view={"label": "Expiry Date"}),
                "inception_date": hx.Date(mode="output", view={"label": "Inception Date"}),
                "insured_country": hx.Str(mode="input", default=None, optionality="optional", options=["", "AND", "ARE", "AFG", "ATG", "AIA", "ALB", "ARM", "AGO", "ATA", "ARG", "ASM", "AUT", "AUS", "ABW", "ALA", "AZE", "BIH", "BRB", "BGD", "BEL", "BFA", "BGR", "BHR", "BDI", "BEN", "BLM", "BMU", "BRN", "BOL", "BES", "BRA", "BHS", "BTN", "BVT", "BWA", "BLR", "BLZ", "CAN", "CCK", "COD", "CAF", "COG", "CHE", "CIV", "COK", "CHL", "CMR", "CHN", "COL", "CRI", "CUB", "CPV", "CUW", "CXR", "CYP", "CZE", "DEU", "DJI", "DNK", "DMA", "DOM", "DZA", "ECU", "EST", "EGY", "ESH", "ERI", "ESP", "ETH", "FIN", "FJI", "FLK", "FSM", "FRO", "FRA", "GAB", "GBR", "GRD", "GEO", "GUF", "GGY", "GHA", "GIB", "GRL", "GMB", "GIN", "GLP", "GNQ", "GRC", "SGS", "GTM", "GUM", "GNB", "GUY", "HKG", "HMD", "HND", "HRV", "HTI", "HUN", "IDN", "IRL", "ISR", "IMN", "IND", "IOT", "IRQ", "IRN", "ISL", "ITA", "JEY", "JAM", "JOR", "JPN", "KEN", "KGZ", "KHM", "KIR", "COM", "KNA", "PRK", "KOR", "KWT", "CYM", "KAZ", "LAO", "LBN", "LCA", "LIE", "LKA", "LBR", "LSO", "LTU", "LUX", "LVA", "LBY", "MAR", "MCO", "MDA", "MNE", "MAF", "MDG", "MHL", "MKD", "MLI", "MMR", "MNG", "MAC", "MNP", "MTQ", "MRT", "MSR", "MLT", "MUS", "MDV", "MWI", "MEX", "MYS", "MOZ", "NAM", "NCL", "NER", "NFK", "NGA", "NIC", "NLD", "NOR", "NPL", "NRU", "NIU", "NZL", "OMN", "PAN", "PER", "PYF", "PNG", "PHL", "PAK", "POL", "SPM", "PCN", "PRI", "PSE", "PRT", "PLW", "PRY", "QAT", "REU", "ROU", "SRB", "RUS", "RWA", "SAU", "SLB", "SYC", "SDN", "SWE", "SGP", "SHN", "SVN", "SJM", "SVK", "SLE", "SMR", "SEN", "SOM", "SUR", "SSD", "STP", "SLV", "SXM", "SYR", "SWZ", "TCA", "TCD", "ATF", "TGO", "THA", "TJK", "TKL", "TLS", "TKM", "TUN", "TON", "TUR", "TTO", "TUV", "TWN", "TZA", "UKR", "UGA", "UMI", "USA", "URY", "UZB", "VAT", "VCT", "VEN", "VGB", "VIR", "VNM", "VUT", "WLF", "WSM", "YEM", "MYT", "ZAF", "ZMB", "ZWE", "ATB", "BYS", "CTE", "CSK", "DHY", "ATN", "AFI", "ATF", "DDR", "GEL", "JTN", "MID", "NHB", "PCI", "PCZ", "SKM", "RHO", "PUS", "HVO", "VDR", "WAK", "YMD"], view={"label": "Insured Country"}),
                "insured_postal_code": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Insured Postal Code"}),
                "insured_state_or_province": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Insured State or Province"}),
                "is_admitted_or_surplus": hx.Str(mode="input", default=None, optionality="optional", options=["Admitted", "Surplus"], view={"label": "Is Admitted Or Surplus"}),
                "is_free_trade_zone": hx.Bool(mode="input", default=False, optionality="required", view={"label": "Is Free-Trade Zone"}),
                "is_renewal": hx.Bool(mode="input", default=False, async_output=[{"task": "start_renewal_task", "reset": False}], optionality="required", view={"label": "Is Renewal"}),
                "underwriter": hx.Str(mode="input", default=None, optionality="optional", options_column="underwriter", options_table="table_input_underwriters", view={"label": "Underwriter"}),
                "policy_reference": hx.Str(mode="input", default=None, async_input=["insert_hx_meta_policy_references_task"], optionality="optional", view={"label": "Policy Reference"}),
                "facility_reference": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Facility Reference"}),
                "benchmark_class": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Benchmark Class"}),
                "uw_rationale": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Underwriter Rationale"}),
                "trifocus": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Trifocus"}),
                "rating_methodology": hx.Str(mode="input", default="Rater", options=["Rater", "Case Priced"], view={"label": "Rater Priced or Case Priced?"}),
                "is_case_priced": hx.Bool(mode="output", view={"label": "Is Case Priced"}),
                "is_rater_priced": hx.Bool(mode="output", view={"label": "Is Rater Priced"}),
            }),
            "layers": hx.List(mode="input", max_element_count=6, view={"label": "Layers"}, children={
                "limit": hx.Float(mode="input", default=None, async_input=["rarc_task"], optionality="optional", view={"label": "Limit", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "excess": hx.Float(mode="input", default=None, async_input=["rarc_task"], optionality="optional", view={"label": "Excess", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "deductible": hx.Float(mode="input", default=None, async_input=["rarc_task"], optionality="optional", view={"label": "Deductible", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "aggregate_limit": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Aggregate Limit", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "aggregate_excess": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Aggregate Excess", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "aggregate_deductible": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Aggregate Deductible", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "currency": hx.Str(mode="input", default=None, optionality="optional", options=["ADP", "AFA", "AON", "AOR", "ATS", "AZM", "BEF", "BGL", "BRE", "BUK", "BYB", "BYR", "CSD", "CSK", "CYP", "DDM", "DEM", "ECS", "EEK", "ESP", "FIM", "FRF", "GHC", "GRD", "GWP", "HRK", "IEP", "ITL", "LTL", "LUF", "LVL", "MGF", "MRO", "MTL", "MXP", "MZM", "NIC", "NLG", "PES", "PLZ", "PTE", "ROL", "RUR", "SDD", "SDP", "SIT", "SKK", "SRG", "STD", "SUR", "TRL", "UYP", "VEB", "VEF", "XEU", "YUM", "ZMK", "ZRN", "ZRZ", "ZWD", "ZWR", "AED", "AFN", "ALL", "AMD", "ANG", "AOA", "ARS", "AUD", "AWG", "AZN", "BAM", "BBD", "BDT", "BGN", "BHD", "BIF", "BMD", "BND", "BOB", "BOV", "BRL", "BSD", "BTN", "BWP", "BYN", "BZD", "CAD", "CDF", "CHE", "CHF", "CHW", "CLF", "CLP", "CNY", "COP", "COU", "CRC", "CUC", "CUP", "CVE", "CZK", "DJF", "DKK", "DOP", "DZD", "EGP", "ERN", "ETB", "EUR", "FJD", "FKP", "GBP", "GEL", "GHS", "GIP", "GMD", "GNF", "GTQ", "GYD", "HKD", "HNL", "HTG", "HUF", "IDR", "ILS", "INR", "IQD", "IRR", "ISK", "JMD", "JOD", "JPY", "KES", "KGS", "KHR", "KMF", "KPW", "KRW", "KWD", "KYD", "KZT", "LAK", "LBP", "LKR", "LRD", "LSL", "LYD", "MAD", "MDL", "MGA", "MKD", "MMK", "MNT", "MOP", "MRU", "MUR", "MVR", "MWK", "MXN", "MXV", "MYR", "MZN", "NAD", "NGN", "NIO", "NOK", "NPR", "NZD", "OMR", "PAB", "PEN", "PGK", "PHP", "PKR", "PLN", "PYG", "QAR", "RON", "RSD", "RUB", "RWF", "SAR", "SBD", "SCR", "SDG", "SEK", "SGD", "SHP", "SLE", "SLL", "SOS", "SRD", "SSP", "STN", "SVC", "SYP", "SZL", "THB", "TJS", "TMT", "TND", "TOP", "TRY", "TTD", "TWD", "TZS", "UAH", "UGX", "USD", "USN", "UYI", "UYU", "UYW", "UZS", "VED", "VES", "VND", "VUV", "WST", "XAF", "XAG", "XAU", "XBA", "XBB", "XBC", "XBD", "XCD", "XDR", "XOF", "XPD", "XPF", "XPT", "XSU", "XTS", "XUA", "XXX", "YER", "ZAR", "ZMW", "ZWL"], view={"label": "Currency"}),
                "section_reference": hx.Str(mode="output", optionality="optional", view={"label": "Section Reference"}),
                "brokerage": hx.Float(mode="output", async_input=["rarc_task"], optionality="optional", view={"label": "Brokerage", "format": {"output": "percent", "mantissa": 1}}),
                "written_line": hx.Float(mode="output", async_input=["rarc_task"], optionality="optional", view={"label": "Written Line", "format": {"output": "percent", "mantissa": 1}}),
                "premium": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Gross Bound Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "status": hx.Str(mode="input", default=None, async_input=["start_renewal_task"], optionality="optional", options=["Assessment Pending", "Rating", "Quoted", "Bound", "Post Bind Complete", "Declined", "Not Taken Up"], view={"label": "Status", "options": {"read_only": {"read_only": True}}}),
                "is_primary_excess": hx.Str(mode="input", default=None, optionality="optional", options=["Primary", "Excess"], view={"label": "Primary or Excess"}),
                "benchmark_premium": hx.Float(mode="output", async_input=["rarc_task"], optionality="optional", view={"label": "Gross Benchmark Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "bpi": hx.Float(mode="output", optionality="optional", view={"label": "BPI", "format": {"output": "percent", "mantissa": 1}}),
                "bpi_pre_uw_adj": hx.Float(mode="output", optionality="optional", view={"label": "BPI (Pre-UW Adjustment)", "format": {"output": "percent", "mantissa": 1}}),
                "model_premium": hx.Float(mode="output", optionality="optional", view={"label": "Gross Model Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "unity_premium": hx.Float(mode="output", optionality="optional", view={"label": "Gross Unity Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "quoted_premium": hx.Float(mode="output", optionality="optional", view={"label": "Gross Quoted Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "technical_premium": hx.Float(mode="output", optionality="optional", view={"label": "Gross Technical Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "technical_premium_pre_uw_adj": hx.Float(mode="output", optionality="optional", view={"label": "Gross Technical Premium (Pre-UW Adjustment)", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "technical_premium_net": hx.Float(mode="output", optionality="optional", view={"label": "Net Technical Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "tpi": hx.Float(mode="output", optionality="optional", view={"label": "TPI", "format": {"output": "percent", "mantissa": 1}}),
                "tpi_pre_uw_adj": hx.Float(mode="output", optionality="optional", view={"label": "TPI (Pre-UW Adjustment)", "format": {"output": "percent", "mantissa": 1}}),
                "pflr_att": hx.Float(mode="output", optionality="optional", view={"label": "Priced-for Loss Ratio (Att)", "format": {"output": "percent", "mantissa": 1}}),
                "pflr_cat": hx.Float(mode="output", optionality="optional", view={"label": "Priced-for Loss Ratio (Cat)", "format": {"output": "percent", "mantissa": 1}}),
                "pflr": hx.Float(mode="output", optionality="optional", view={"label": "Priced-for Loss Ratio", "format": {"output": "percent", "mantissa": 1}}),
                "roc": hx.Float(mode="output", optionality="optional", view={"label": "Return on Capital", "format": {"output": "percent", "mantissa": 1}}),
                "uw_adj_impact": hx.Float(mode="output", optionality="optional", view={"label": "Impact of Underwriting Adjustments", "format": {"output": "percent", "mantissa": 1}}),
                "trifocus": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Trifocus"}),
                "expected_loss_cost": hx.Float(mode="output", optionality="optional", view={"label": "Expected Loss Cost", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "expected_loss_cost_pre_uw_adj": hx.Float(mode="output", optionality="optional", view={"label": "Expected Loss Cost (Pre-UW Ajustment)", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "coverages": hx.Structure(view={"label": "Coverages"}, children={
                    "example_coverage_1": hx.Structure(view={"label": "Example Coverage 1"}, children={
                        "limit": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Limit", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "excess": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Excess", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "deductible": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Deductible", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "aggregate_limit": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Aggregate Limit", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "aggregate_excess": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Aggregate Excess", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "aggregate_deductible": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Aggregate Deductible", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "currency": hx.Str(mode="input", default=None, optionality="optional", options=["ADP", "AFA", "AON", "AOR", "ATS", "AZM", "BEF", "BGL", "BRE", "BUK", "BYB", "BYR", "CSD", "CSK", "CYP", "DDM", "DEM", "ECS", "EEK", "ESP", "FIM", "FRF", "GHC", "GRD", "GWP", "HRK", "IEP", "ITL", "LTL", "LUF", "LVL", "MGF", "MRO", "MTL", "MXP", "MZM", "NIC", "NLG", "PES", "PLZ", "PTE", "ROL", "RUR", "SDD", "SDP", "SIT", "SKK", "SRG", "STD", "SUR", "TRL", "UYP", "VEB", "VEF", "XEU", "YUM", "ZMK", "ZRN", "ZRZ", "ZWD", "ZWR", "AED", "AFN", "ALL", "AMD", "ANG", "AOA", "ARS", "AUD", "AWG", "AZN", "BAM", "BBD", "BDT", "BGN", "BHD", "BIF", "BMD", "BND", "BOB", "BOV", "BRL", "BSD", "BTN", "BWP", "BYN", "BZD", "CAD", "CDF", "CHE", "CHF", "CHW", "CLF", "CLP", "CNY", "COP", "COU", "CRC", "CUC", "CUP", "CVE", "CZK", "DJF", "DKK", "DOP", "DZD", "EGP", "ERN", "ETB", "EUR", "FJD", "FKP", "GBP", "GEL", "GHS", "GIP", "GMD", "GNF", "GTQ", "GYD", "HKD", "HNL", "HTG", "HUF", "IDR", "ILS", "INR", "IQD", "IRR", "ISK", "JMD", "JOD", "JPY", "KES", "KGS", "KHR", "KMF", "KPW", "KRW", "KWD", "KYD", "KZT", "LAK", "LBP", "LKR", "LRD", "LSL", "LYD", "MAD", "MDL", "MGA", "MKD", "MMK", "MNT", "MOP", "MRU", "MUR", "MVR", "MWK", "MXN", "MXV", "MYR", "MZN", "NAD", "NGN", "NIO", "NOK", "NPR", "NZD", "OMR", "PAB", "PEN", "PGK", "PHP", "PKR", "PLN", "PYG", "QAR", "RON", "RSD", "RUB", "RWF", "SAR", "SBD", "SCR", "SDG", "SEK", "SGD", "SHP", "SLE", "SLL", "SOS", "SRD", "SSP", "STN", "SVC", "SYP", "SZL", "THB", "TJS", "TMT", "TND", "TOP", "TRY", "TTD", "TWD", "TZS", "UAH", "UGX", "USD", "USN", "UYI", "UYU", "UYW", "UZS", "VED", "VES", "VND", "VUV", "WST", "XAF", "XAG", "XAU", "XBA", "XBB", "XBC", "XBD", "XCD", "XDR", "XOF", "XPD", "XPF", "XPT", "XSU", "XTS", "XUA", "XXX", "YER", "ZAR", "ZMW", "ZWL"], view={"label": "Currency"}),
                        "section_reference": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Section Reference"}),
                        "brokerage": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Brokerage", "format": {"output": "percent", "mantissa": 1}}),
                        "written_line": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Written Line", "format": {"output": "percent", "mantissa": 1}}),
                        "premium": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Gross Bound Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "status": hx.Str(mode="input", default=None, optionality="optional", options=["Assessment Pending", "Rating", "Quoted", "Bound", "Post Bind Complete", "Declined", "Not Taken Up"], view={"label": "Status"}),
                        "benchmark_premium": hx.Float(mode="output", optionality="optional", view={"label": "Gross Benchmark Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "bpi": hx.Float(mode="output", optionality="optional", view={"label": "BPI", "format": {"output": "percent", "mantissa": 1}}),
                        "bpi_pre_uw_adj": hx.Float(mode="output", optionality="optional", view={"label": "BPI (Pre-UW Adjustment)", "format": {"output": "percent", "mantissa": 1}}),
                        "model_premium": hx.Float(mode="output", optionality="optional", view={"label": "Gross Model Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "unity_premium": hx.Float(mode="output", optionality="optional", view={"label": "Gross Unity Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "quoted_premium": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Gross Quoted Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "technical_premium": hx.Float(mode="output", optionality="optional", view={"label": "Gross Technical Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "technical_premium_pre_uw_adj": hx.Float(mode="output", optionality="optional", view={"label": "Gross Technical Premium (Pre-UW Adjustment)", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "technical_premium_net": hx.Float(mode="output", optionality="optional", view={"label": "Net Technical Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "tpi": hx.Float(mode="output", optionality="optional", view={"label": "TPI", "format": {"output": "percent", "mantissa": 1}}),
                        "tpi_pre_uw_adj": hx.Float(mode="output", optionality="optional", view={"label": "TPI (Pre-UW Adjustment)", "format": {"output": "percent", "mantissa": 1}}),
                        "pflr_att": hx.Float(mode="output", optionality="optional", view={"label": "Priced-for Loss Ratio (Att)", "format": {"output": "percent", "mantissa": 1}}),
                        "pflr_cat": hx.Float(mode="output", optionality="optional", view={"label": "Priced-for Loss Ratio (Cat)", "format": {"output": "percent", "mantissa": 1}}),
                        "pflr": hx.Float(mode="output", optionality="optional", view={"label": "Priced-for Loss Ratio", "format": {"output": "percent", "mantissa": 1}}),
                        "roc": hx.Float(mode="output", optionality="optional", view={"label": "Return on Capital", "format": {"output": "percent", "mantissa": 1}}),
                        "uw_adj_impact": hx.Float(mode="output", optionality="optional", view={"label": "Impact of Underwriting Adjustments", "format": {"output": "percent", "mantissa": 1}}),
                        "example_common_coverage_variable": hx.Float(mode="input", default=0, view={"label": "Common Coverage Variable"}),
                        "example_specific_coverage_variable": hx.Float(mode="input", default=0, view={"label": "Common Coverage Variable"}),
                    }),
                    "example_coverage_2": hx.Structure(view={"label": "Example Coverage 2"}, children={
                        "limit": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Limit", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "excess": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Excess", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "deductible": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Deductible", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "aggregate_limit": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Aggregate Limit", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "aggregate_excess": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Aggregate Excess", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "aggregate_deductible": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Aggregate Deductible", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "currency": hx.Str(mode="input", default=None, optionality="optional", options=["ADP", "AFA", "AON", "AOR", "ATS", "AZM", "BEF", "BGL", "BRE", "BUK", "BYB", "BYR", "CSD", "CSK", "CYP", "DDM", "DEM", "ECS", "EEK", "ESP", "FIM", "FRF", "GHC", "GRD", "GWP", "HRK", "IEP", "ITL", "LTL", "LUF", "LVL", "MGF", "MRO", "MTL", "MXP", "MZM", "NIC", "NLG", "PES", "PLZ", "PTE", "ROL", "RUR", "SDD", "SDP", "SIT", "SKK", "SRG", "STD", "SUR", "TRL", "UYP", "VEB", "VEF", "XEU", "YUM", "ZMK", "ZRN", "ZRZ", "ZWD", "ZWR", "AED", "AFN", "ALL", "AMD", "ANG", "AOA", "ARS", "AUD", "AWG", "AZN", "BAM", "BBD", "BDT", "BGN", "BHD", "BIF", "BMD", "BND", "BOB", "BOV", "BRL", "BSD", "BTN", "BWP", "BYN", "BZD", "CAD", "CDF", "CHE", "CHF", "CHW", "CLF", "CLP", "CNY", "COP", "COU", "CRC", "CUC", "CUP", "CVE", "CZK", "DJF", "DKK", "DOP", "DZD", "EGP", "ERN", "ETB", "EUR", "FJD", "FKP", "GBP", "GEL", "GHS", "GIP", "GMD", "GNF", "GTQ", "GYD", "HKD", "HNL", "HTG", "HUF", "IDR", "ILS", "INR", "IQD", "IRR", "ISK", "JMD", "JOD", "JPY", "KES", "KGS", "KHR", "KMF", "KPW", "KRW", "KWD", "KYD", "KZT", "LAK", "LBP", "LKR", "LRD", "LSL", "LYD", "MAD", "MDL", "MGA", "MKD", "MMK", "MNT", "MOP", "MRU", "MUR", "MVR", "MWK", "MXN", "MXV", "MYR", "MZN", "NAD", "NGN", "NIO", "NOK", "NPR", "NZD", "OMR", "PAB", "PEN", "PGK", "PHP", "PKR", "PLN", "PYG", "QAR", "RON", "RSD", "RUB", "RWF", "SAR", "SBD", "SCR", "SDG", "SEK", "SGD", "SHP", "SLE", "SLL", "SOS", "SRD", "SSP", "STN", "SVC", "SYP", "SZL", "THB", "TJS", "TMT", "TND", "TOP", "TRY", "TTD", "TWD", "TZS", "UAH", "UGX", "USD", "USN", "UYI", "UYU", "UYW", "UZS", "VED", "VES", "VND", "VUV", "WST", "XAF", "XAG", "XAU", "XBA", "XBB", "XBC", "XBD", "XCD", "XDR", "XOF", "XPD", "XPF", "XPT", "XSU", "XTS", "XUA", "XXX", "YER", "ZAR", "ZMW", "ZWL"], view={"label": "Currency"}),
                        "section_reference": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Section Reference"}),
                        "brokerage": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Brokerage", "format": {"output": "percent", "mantissa": 1}}),
                        "written_line": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Written Line", "format": {"output": "percent", "mantissa": 1}}),
                        "premium": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Gross Bound Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "status": hx.Str(mode="input", default=None, optionality="optional", options=["Assessment Pending", "Rating", "Quoted", "Bound", "Post Bind Complete", "Declined", "Not Taken Up"], view={"label": "Status"}),
                        "benchmark_premium": hx.Float(mode="output", optionality="optional", view={"label": "Gross Benchmark Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "bpi": hx.Float(mode="output", optionality="optional", view={"label": "BPI", "format": {"output": "percent", "mantissa": 1}}),
                        "bpi_pre_uw_adj": hx.Float(mode="output", optionality="optional", view={"label": "BPI (Pre-UW Adjustment)", "format": {"output": "percent", "mantissa": 1}}),
                        "model_premium": hx.Float(mode="output", optionality="optional", view={"label": "Gross Model Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "unity_premium": hx.Float(mode="output", optionality="optional", view={"label": "Gross Unity Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "quoted_premium": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Gross Quoted Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "technical_premium": hx.Float(mode="output", optionality="optional", view={"label": "Gross Technical Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "technical_premium_pre_uw_adj": hx.Float(mode="output", optionality="optional", view={"label": "Gross Technical Premium (Pre-UW Adjustment)", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "technical_premium_net": hx.Float(mode="output", optionality="optional", view={"label": "Net Technical Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "tpi": hx.Float(mode="output", optionality="optional", view={"label": "TPI", "format": {"output": "percent", "mantissa": 1}}),
                        "tpi_pre_uw_adj": hx.Float(mode="output", optionality="optional", view={"label": "TPI (Pre-UW Adjustment)", "format": {"output": "percent", "mantissa": 1}}),
                        "pflr_att": hx.Float(mode="output", optionality="optional", view={"label": "Priced-for Loss Ratio (Att)", "format": {"output": "percent", "mantissa": 1}}),
                        "pflr_cat": hx.Float(mode="output", optionality="optional", view={"label": "Priced-for Loss Ratio (Cat)", "format": {"output": "percent", "mantissa": 1}}),
                        "pflr": hx.Float(mode="output", optionality="optional", view={"label": "Priced-for Loss Ratio", "format": {"output": "percent", "mantissa": 1}}),
                        "roc": hx.Float(mode="output", optionality="optional", view={"label": "Return on Capital", "format": {"output": "percent", "mantissa": 1}}),
                        "uw_adj_impact": hx.Float(mode="output", optionality="optional", view={"label": "Impact of Underwriting Adjustments", "format": {"output": "percent", "mantissa": 1}}),
                        "example_common_coverage_variable": hx.Float(mode="input", default=0, view={"label": "Common Coverage Variable"}),
                    }),
                }),
                "rate_change": hx.Structure(view={"label": "Rate Change"}, children={
                    "exposure_change": hx.Structure(view={"label": "Exposure Change"}, children={
                        "model_calculated": hx.Float(mode="output", async_output=["rarc_task"], view={"label": "Model %", "format": {"output": "percent", "mantissa": 0}}),
                        "uw_selected": hx.Float(mode="override", view={"label": "UW Selected %", "format": {"output": "percent", "mantissa": 0}}),
                        "comments": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Comment"}),
                    }),
                    "risk_characteristics_change": hx.Structure(view={"label": "Risk Characteristics Change"}, children={
                        "model_calculated": hx.Float(mode="output", async_output=["rarc_task"], view={"label": "Model %", "format": {"output": "percent", "mantissa": 0}}),
                        "uw_selected": hx.Float(mode="override", view={"label": "UW Selected %", "format": {"output": "percent", "mantissa": 0}}),
                        "comments": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Comment"}),
                    }),
                    "limit_change": hx.Structure(view={"label": "Limit Change"}, children={
                        "model_calculated": hx.Float(mode="output", async_output=["rarc_task"], view={"label": "Model %", "format": {"output": "percent", "mantissa": 0}}),
                        "uw_selected": hx.Float(mode="override", view={"label": "UW Selected %", "format": {"output": "percent", "mantissa": 0}}),
                        "comments": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Comment"}),
                    }),
                    "deductible_change": hx.Structure(view={"label": "Deductible Change"}, children={
                        "model_calculated": hx.Float(mode="output", async_output=["rarc_task"], view={"label": "Model %", "format": {"output": "percent", "mantissa": 0}}),
                        "uw_selected": hx.Float(mode="override", view={"label": "UW Selected %", "format": {"output": "percent", "mantissa": 0}}),
                        "comments": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Comment"}),
                    }),
                    "terms_conditions_change": hx.Structure(view={"label": "Terms & Conditions Change"}, children={
                        "model_calculated": hx.Float(mode="output", async_output=["rarc_task"], view={"label": "Model %", "format": {"output": "percent", "mantissa": 0}}),
                        "uw_selected": hx.Float(mode="override", view={"label": "UW Selected %", "format": {"output": "percent", "mantissa": 0}}),
                        "comments": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Comment"}),
                    }),
                    "other_change": hx.Structure(view={"label": "Other Change (incl. Brokerage)"}, children={
                        "model_calculated": hx.Float(mode="output", async_output=["rarc_task"], view={"label": "Model %", "format": {"output": "percent", "mantissa": 0}}),
                        "uw_selected": hx.Float(mode="override", view={"label": "UW Selected %", "format": {"output": "percent", "mantissa": 0}}),
                        "comments": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Comment"}),
                    }),
                    "brokerage_change": hx.Structure(view={"label": "Brokerage Change"}, children={
                        "model_calculated": hx.Float(mode="output", async_output=["rarc_task"], view={"label": "Model %", "format": {"output": "percent", "mantissa": 0}}),
                        "uw_selected": hx.Float(mode="override", view={"label": "UW Selected %", "format": {"output": "percent", "mantissa": 0}}),
                        "comments": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Comment"}),
                    }),
                    "rate_change": hx.Structure(view={"label": "Risk Adjusted Rate Change"}, children={
                        "model_calculated": hx.Float(mode="output", view={"label": "Model %", "format": {"output": "percent", "mantissa": 0}}),
                        "uw_selected": hx.Float(mode="output", view={"label": "UW Selected %", "format": {"output": "percent", "mantissa": 0}}),
                        "comments": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Comment"}),
                        "lloyds_limit_attachment_point_change": hx.Float(mode="output", view={"label": "Lloyds's Limit Attachment Point Change", "format": {"output": "percent", "mantissa": 0}}),
                        "lloyds_breadth_of_cover_change": hx.Float(mode="output", view={"label": "Lloyds's Breadth of Cover Change", "format": {"output": "percent", "mantissa": 0}}),
                        "other_factors_change": hx.Float(mode="output", view={"label": "Other Factors Change", "format": {"output": "percent", "mantissa": 0}}),
                    }),
                    "expiring_layer": hx.Int(mode="input", default=1, async_input=["expiring_policy_fetch_task", "rarc_task"], optionality="optional", options=[1, 2, 3, 4, 5, 6], view={"label": "Expiring Layer"}),
                    "premium": hx.Structure(children={
                        "line_100pct": hx.Structure(children={
                            "annualised": hx.Structure(view={"label": "Premium - Annualised (100% Line)"}, children={
                                "expiring": hx.Float(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task"], view={"label": "Expiring", "format": {"thousandSeparated": True, "mantissa": 0}}),
                                "rebased_expiring": hx.Float(mode="output", view={"label": "Rebased\nExpiring", "format": {"thousandSeparated": True, "mantissa": 0}}),
                                "renewal": hx.Float(mode="output", view={"label": "Renewal", "format": {"thousandSeparated": True, "mantissa": 0}}),
                            }),
                        }),
                        "beazley_line": hx.Structure(children={
                            "policy_term": hx.Structure(view={"label": "Premium - Policy Term (Beazley Line)"}, children={
                                "expiring": hx.Float(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task"], view={"label": "Expiring", "format": {"thousandSeparated": True, "mantissa": 0}}),
                                "rebased_expiring": hx.Float(mode="output", view={"label": "Rebased\nExpiring", "format": {"thousandSeparated": True, "mantissa": 0}}),
                                "renewal": hx.Float(mode="output", view={"label": "Renewal", "format": {"thousandSeparated": True, "mantissa": 0}}),
                            }),
                            "annualised": hx.Structure(view={"label": "Premium - Annualised (Beazley Line)"}, children={
                                "expiring": hx.Float(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task"], view={"label": "Expiring", "format": {"thousandSeparated": True, "mantissa": 0}}),
                                "rebased_expiring": hx.Float(mode="output", view={"label": "Rebased\nExpiring", "format": {"thousandSeparated": True, "mantissa": 0}}),
                                "renewal": hx.Float(mode="output", view={"label": "Renewal", "format": {"thousandSeparated": True, "mantissa": 0}}),
                            }),
                        }),
                    }),
                    "expiring_policy_info": hx.Structure(children={
                        "expiring_exposure": hx.Float(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task"]),
                        "expiring_policy_length": hx.Float(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task"]),
                        "expiring_premium": hx.Float(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task"]),
                        "expiring_limit": hx.Float(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task"]),
                        "expiring_deductible": hx.Float(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task"]),
                        "expiring_brokerage": hx.Float(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task"]),
                        "expiring_write_line": hx.Float(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task"]),
                        "expiring_expected_loss": hx.Float(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task"]),
                        "expiring_section_reference": hx.Float(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task"]),
                    }),
                    "risk_adjusted_rate_change": hx.Float(mode="output", view={"label": "Final Risk Adjusted Rate Change", "format": {"output": "percent", "mantissa": 0}}),
                    "risk_adjusted_rate_change_case_priced": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Final Risk Adjusted Rate Change", "format": {"output": "percent", "mantissa": 0}, "options": {"read_only": {"read_only": True}}}),
                    "risk_adjusted_rate_change_gross_for_reporting": hx.Float(mode="output"),
                    "error_message": hx.Str(mode="output"),
                    "temp_storage": hx.Structure(children={
                        "quoted_premium": hx.Float(mode="output", async_output=["rarc_task"]),
                        "benchmark_premium": hx.Float(mode="output", async_output=["rarc_task"]),
                    }),
                }),
                "bpi_case_priced": hx.Float(mode="input", default=0, optionality="required", view={"label": "BPI (Case Priced)", "format": {"output": "percent", "mantissa": 1}}),
                "pflr_pre_uw_adj": hx.Float(mode="output", optionality="optional", view={"label": "Priced-for Loss Ratio (Pre-UW Adj.)", "format": {"output": "percent", "mantissa": 1}}),
                "premium_label": hx.Str(mode="output"),
                "quoted_premium_annualised": hx.Float(mode="output", async_input=["rarc_task"]),
                "benchmark_premium_annualised": hx.Float(mode="output", async_input=["rarc_task"]),
                "benchmark_premium_net": hx.Float(mode="output", optionality="optional", view={"label": "Net Benchmark Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "prem_rate_benchmark_net": hx.Float(mode="output", view={"label": "Prem Rate (Net)", "format": {"output": "percent", "mantissa": 3}}),
                "prem_rate_benchmark_gross": hx.Float(mode="output", view={"label": "Prem Rate (Gross)", "format": {"output": "percent", "mantissa": 3}}),
                "quoted_premium_net": hx.Float(mode="input", default=0, optionality="optional", view={"label": "Net brokerage", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "prem_rate_net": hx.Float(mode="output", view={"label": "Prem Rate (Net)", "format": {"output": "percent", "mantissa": 3}}),
                "prem_rate_gross": hx.Float(mode="output", view={"label": "Prem Rate (Gross)", "format": {"output": "percent", "mantissa": 3}}),
                "technical_premium_pre_uw_adj_net": hx.Float(mode="output", view={"label": "Net brokerage", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "quoted_premium_case_priced": hx.Float(mode="output", view={"label": "Gross Achieved Premium (Case Priced)", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "quoted_premium_net_case_priced": hx.Float(mode="input", default=0, view={"label": "Net Achieved Premium (Case Priced)", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "net_kpi": hx.Structure(view={"label": "Net"}, children={
                    "benchmark_premium": hx.Float(mode="output", view={"label": "Benchmark Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "benchmark_rate": hx.Float(mode="output", view={"label": "Benchmark Rate", "format": {"output": "percent", "mantissa": 3}}),
                    "achieved_premium": hx.Float(mode="input", default=0, view={"label": "Achieved Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "achieved_rate": hx.Float(mode="output", view={"label": "Achieved Rate", "format": {"output": "percent", "mantissa": 3}}),
                    "bpi_pre_uw_adj": hx.Float(mode="output", view={"label": "BPI Pre UW Adj", "format": {"output": "percent", "mantissa": 2}}),
                    "bpi_post_uw_adj": hx.Float(mode="output", view={"label": "BPI Post UW Adj", "format": {"output": "percent", "mantissa": 2}}),
                    "pflr": hx.Float(mode="output", view={"label": "PFLR (Net)", "format": {"output": "percent", "mantissa": 2}}),
                    "technical_premium": hx.Float(mode="output", view={"label": "Technical Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "tpi_pre_uw_adj": hx.Float(mode="output", view={"label": "TPI Pre UW Adj", "format": {"output": "percent", "mantissa": 2}}),
                    "tpi_post_uw_adj": hx.Float(mode="output", view={"label": "TPI Post UW Adj", "format": {"output": "percent", "mantissa": 2}}),
                }),
                "gross_kpi": hx.Structure(view={"label": "Gross"}, children={
                    "benchmark_premium": hx.Float(mode="output", view={"label": "Benchmark Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "benchmark_rate": hx.Float(mode="output", view={"label": "Benchmark Rate", "format": {"output": "percent", "mantissa": 3}}),
                    "achieved_premium": hx.Float(mode="output", view={"label": "Achieved Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "achieved_rate": hx.Float(mode="output", view={"label": "Achieved Rate", "format": {"output": "percent", "mantissa": 3}}),
                }),
            }),
            "currencies": hx.Structure(view={"label": "Currencies"}, children={
                "target_currency": hx.Str(mode="input", default=None, optionality="optional", options=["ADP", "AFA", "AON", "AOR", "ATS", "AZM", "BEF", "BGL", "BRE", "BUK", "BYB", "BYR", "CSD", "CSK", "CYP", "DDM", "DEM", "ECS", "EEK", "ESP", "FIM", "FRF", "GHC", "GRD", "GWP", "HRK", "IEP", "ITL", "LTL", "LUF", "LVL", "MGF", "MRO", "MTL", "MXP", "MZM", "NIC", "NLG", "PES", "PLZ", "PTE", "ROL", "RUR", "SDD", "SDP", "SIT", "SKK", "SRG", "STD", "SUR", "TRL", "UYP", "VEB", "VEF", "XEU", "YUM", "ZMK", "ZRN", "ZRZ", "ZWD", "ZWR", "AED", "AFN", "ALL", "AMD", "ANG", "AOA", "ARS", "AUD", "AWG", "AZN", "BAM", "BBD", "BDT", "BGN", "BHD", "BIF", "BMD", "BND", "BOB", "BOV", "BRL", "BSD", "BTN", "BWP", "BYN", "BZD", "CAD", "CDF", "CHE", "CHF", "CHW", "CLF", "CLP", "CNY", "COP", "COU", "CRC", "CUC", "CUP", "CVE", "CZK", "DJF", "DKK", "DOP", "DZD", "EGP", "ERN", "ETB", "EUR", "FJD", "FKP", "GBP", "GEL", "GHS", "GIP", "GMD", "GNF", "GTQ", "GYD", "HKD", "HNL", "HTG", "HUF", "IDR", "ILS", "INR", "IQD", "IRR", "ISK", "JMD", "JOD", "JPY", "KES", "KGS", "KHR", "KMF", "KPW", "KRW", "KWD", "KYD", "KZT", "LAK", "LBP", "LKR", "LRD", "LSL", "LYD", "MAD", "MDL", "MGA", "MKD", "MMK", "MNT", "MOP", "MRU", "MUR", "MVR", "MWK", "MXN", "MXV", "MYR", "MZN", "NAD", "NGN", "NIO", "NOK", "NPR", "NZD", "OMR", "PAB", "PEN", "PGK", "PHP", "PKR", "PLN", "PYG", "QAR", "RON", "RSD", "RUB", "RWF", "SAR", "SBD", "SCR", "SDG", "SEK", "SGD", "SHP", "SLE", "SLL", "SOS", "SRD", "SSP", "STN", "SVC", "SYP", "SZL", "THB", "TJS", "TMT", "TND", "TOP", "TRY", "TTD", "TWD", "TZS", "UAH", "UGX", "USD", "USN", "UYI", "UYU", "UYW", "UZS", "VED", "VES", "VND", "VUV", "WST", "XAF", "XAG", "XAU", "XBA", "XBB", "XBC", "XBD", "XCD", "XDR", "XOF", "XPD", "XPF", "XPT", "XSU", "XTS", "XUA", "XXX", "YER", "ZAR", "ZMW", "ZWL"], view={"label": "Target Currency"}),
                "source_currency": hx.Str(mode="input", default="USD", async_input=["start_renewal_task"], optionality="optional", options=["AUD", "CAD", "DKK", "EUR", "GBP", "JPY", "NOK", "SGD", "USD"], view={"label": "Source Currency"}),
                "multi_currency_support": hx.Bool(mode="input", default=False, optionality="required", view={"label": "Multi Currency Support"}),
                "rates": hx.List(mode="input", view={"label": "Rates"}, children={
                    "code": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Code"}),
                    "rate": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Rate", "format": {"thousandSeparated": False, "mantissa": 2}}),
                }),
            }),
            "experience_rating": hx.Structure(view={"label": "Experience Rating"}, children={
                "claims_available": hx.Bool(mode="input", default=False, view={"label": "Loss Data Avaialble"}),
                "claims_fgu": hx.Bool(mode="input", default=False, view={"label": "Claims From Ground Up"}),
                "claims_net_of_deductible": hx.Bool(mode="input", default=False, view={"label": "Are Claims net of Deductible"}),
            }),
            "policy_option_id": hx.Int(mode="output", view={"label": "Policy Option ID", "format": {"thousandSeparated": False, "mantissa": 0}}),
            "broker_contact": hx.Str(mode="input", default="", view={"label": "Broker Contact"}),
            "case_pricing_analysis_location": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Case Pricing Analysis Filepath"}),
            "yoa": hx.Int(mode="output", view={"label": "YOA", "format": {"thousandSeparated": False}}),
            "beazley_share": hx.Float(mode="input", default=1, view={"label": "Beazley's share", "format": {"output": "percent", "mantissa": 1}}),
            "brokerage": hx.Float(mode="input", default=0.25, async_input=["rarc_task"], view={"label": "Brokerage", "format": {"output": "percent", "mantissa": 1}}),
            "policy_term": hx.Float(mode="output", view={"label": "Policy term (years)", "format": {"thousandSeparated": True, "mantissa": 1}}),
            "rate_change": hx.Structure(children={
                "show_layer_1": hx.Bool(mode="output"),
                "show_layer_2": hx.Bool(mode="output"),
                "show_layer_3": hx.Bool(mode="output"),
                "show_layer_4": hx.Bool(mode="output"),
                "show_layer_5": hx.Bool(mode="output"),
                "show_layer_6": hx.Bool(mode="output"),
                "expiring_policy_option_id": hx.Int(mode="override", async_input=["expiring_policy_fetch_task", "rarc_task"], view={"label": "Expiring Policy Option", "format": {"thousandSeparated": False}}),
                "has_fetch_not_run": hx.Bool(mode="input", default=True, async_output=["expiring_policy_fetch_task", "rarc_task"]),
                "has_fetch_run": hx.Bool(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task"]),
                "has_rarc_not_run": hx.Bool(mode="input", default=True, async_output=["rarc_task"]),
                "has_rarc_run": hx.Bool(mode="output", async_output=["rarc_task"]),
                "rarc_run_again_message": hx.Str(mode="output"),
                "rarc_message_show": hx.Bool(mode="output"),
                "layer_mapping": hx.Str(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task"]),
            }),
            "rating_factors": hx.Structure(children={
                "policy_term": hx.Float(mode="output"),
            }),
            "example_structure": hx.Structure(view={"label": "Example Code"}, children={
                "example_child1": hx.Float(mode="input", default=0, view={"label": "Example Child 1"}),
                "example_child2": hx.Float(mode="input", default=0, view={"label": "Example Child 2"}),
            }),
        }),
        "model_state": hx.Structure(children={
            "pressed_start_renewal_task": hx.Bool(mode="output", async_output=["start_renewal_task"]),
            "show_landing_page": hx.Bool(mode="output"),
            "show_after_landing_page": hx.Bool(mode="output"),
            "show_rate_change": hx.Bool(mode="output"),
            "landing_page_info": hx.Str(mode="input", default="Click the 'import expiring policy data' arrow in the top right corner then click **Start Policy**. ", async_output=["start_renewal_task"], view={"read_only": True}),
            "expiring_policy_option_id": hx.Int(mode="input", default=None, async_output=["start_renewal_task", "sync_expiring_ids"], optionality="optional"),
        }),
        "bug_report_email": hx.Str(mode="output"),
        "policy_doc": hx.Structure(children={
            "data_dict": hx.Str(mode="output", async_input=["policy_to_excel_task"]),
            "output_file": hx.File(mode="output", async_output=["policy_to_excel_task"], file_name="Policy_Summary.xlsx"),
            "task_data_dict": hx.Str(mode="output", async_output=["policy_to_excel_task"]),
            "show_generate_button": hx.Bool(mode="output"),
            "show_download": hx.Bool(mode="output"),
            "premium_check": hx.Str(mode="output"),
            "show_premium_check": hx.Bool(mode="output"),
        }),
    })
