import hx_data_schema as hx
from data_schema.sch_utilities import thousands_format
from data_schema.sch_utilities import percent_format
from data_schema.sch_utilities import integer_format

def sch_rater_defined(cds):
    cds.extend_node_items("cds/layers/coverages", {
        "cargo_transit": {"label": "Cargo"},
        "cargo_storage": {"label": "Cargo"},
        "specie_transit": {"label": "Specie"},
        "specie_storage": {"label": "Specie"},
        "conloss_transit": {"label": "Con Loss"},
        "conloss": {"label": "Con Loss"},
    })
    cds.extend_node_rater_defined("cds", {
        "policy_info": hx.Structure(children={
            "deductions": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Deductions"}),
            "term": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Term (Years)"}),
            "beazley_share": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Beazley Share (%)"}),

        }),
    })
    cds.extend_node_rater_defined("cds/layers/coverages/cargo_transit", {
        "transit_flag": hx.Bool(mode="input", default=True, view={"label": "Transit"}),
        "wh_to_port_flag": hx.Bool(mode="input", default=True, view={"label": "Initial Warehouse to Port"}),
        "loading_flag": hx.Bool(mode="input", default=True, view={"label": "Loading"}),
        "voyage_flag": hx.Bool(mode="input", default=True, view={"label": "Voyage"}),
        "unloading_flag": hx.Bool(mode="input", default=True, view={"label": "Unloading"}),
        "port_to_wh_flag": hx.Bool(mode="input", default=True, view={"label": "Port to Final Warehouse"}),
        "base_rate": hx.Float(mode="output", view={"label": "Base Rate"}),
        "commodity": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Commodity"}),
        "commodity_factor": hx.Float(mode="output", view={"label": "Factor"}),
        "trans_vals": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Est Ann Transit Vals"}),
        "trans_vals_factor": hx.Float(mode="output", view={"label": " "}),
        "deductible_level": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Deductible Level"}),
        "deductible_factor": hx.Float(mode="override", view={"label": " "}),
        "excess_factor": hx.Float(mode="output", view={"label": " "}),
        "packaging": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Packaging"}),
        "packaging_factor": hx.Float(mode="output", view={"label": " "}),
        "conv_air": hx.Str(mode="input", default="Air", view={"label": "Conveyance"}),
        "conv_land": hx.Str(mode="input", default="Land", view={"label": " "}),
        "conv_sea": hx.Str(mode="input", default="Sea", view={"label": " "}),
        "conv_air_factor": hx.Float(mode="input", default=None, optionality="optional", view={"label": " "}),
        "conv_land_factor": hx.Float(mode="input", default=None, optionality="optional", view={"label": " "}),
        "conv_sea_factor": hx.Float(mode="input", default=None, optionality="optional", view={"label": " "}),
        "conv_check": hx.Float(mode="output", view={"label": "Check"}),
        "voyage": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Voyage"}),
        "voyage_factor": hx.Float(mode="output", view={"label": " "}),
        "surveyor": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Surveyor Present"}),
        "surveyor_factor": hx.Float(mode="output", view={"label": " "}),
        "vessel": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Vessel"}),
        "vessel_factor": hx.Float(mode="output", view={"label": " "}),
        "uw_discretion": hx.Str(mode="input", default=None, optionality="optional", view={"label": "UW Discretion"}),
        "uw_discretion_weight": hx.Float(mode="input", default=1.0, view={"label": " "}),
        "type_of_cover": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Type of Cover"}),
        "type_of_cover_factor": hx.Float(mode="output", view={"label": " "}),
        "technical_deductions": hx.Float(mode="output", view={"label": "Technical Annual Transit Rate Base Deductions"}),
        "technical_rate": hx.Float(mode="output", view={"label": "Technical Annual Transit Rate"}),
        "actual_rate": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Actual Transit Rate (Annual)"}),
        "pct_of_technical": hx.Float(mode="output", view={"label": "Percentage of Technical"}),
    })
    cds.extend_node_rater_defined("cds/layers/coverages/cargo_storage", {
        "storage_flag": hx.Bool(mode="input", default=True, view={"label": "Storage"}),
        "base_rate": hx.Float(mode="output", view={"label": "Base Rate"}),
        "stock_vals": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Expo'd Stock Vals"}),
        "deductible_level": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Deductible Level"}),
        "deductible_factor": hx.Float(mode="override", view={"label": "Factor"}),
        "excess_factor": hx.Float(mode="override", view={"label": " "}),
        "survey": hx.Bool(mode="input", default=True, view={"label": "Satis. Survey Report"}),
        "survey_factor": hx.Float(mode="output", view={"label": " "}),
        "risk_mgmt": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Risk Management"}),
        "risk_mgmt_weight": hx.Float(mode="input", default=1.0, view={"label": " "}),
        "type_of_cover": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Type of Cover"}),
        "type_of_cover_factor": hx.Float(mode="output", view={"label": " "}),
        "uw_discretion": hx.Str(mode="input", default=None, optionality="optional", view={"label": "UW Discretion"}),
        "uw_discretion_weight": hx.Float(mode="input", default=1.0, view={"label": " "}),
        "rate": hx.Float(mode="output", view={"label": "Storage Rate"}),
        "avg_val_pcm": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Avg Val Expo'd PCM"}),
        "cat_expo": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Cat Expo"}),
        "cat_pct_of_total": hx.Float(mode="output", view={"label": "% of Total"}),
        "combined_cat_load": hx.Float(mode="output", view={"label": "Combined Cat Load"}),
        "cat_expo_tp": hx.Float(mode="override", view={"label": "Technical Premium"}),
        "country": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Country"}),
        "country_cat_expo": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Cat Exposure Amount"}),
        "country_cat_load": hx.Float(mode="output", view={"label": "Load Applied"}),
        "retail_expo": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Retail Expo"}),
        "retail_pct_of_total": hx.Float(mode="output", view={"label": "% of Total"}),
        "retail_load": hx.Float(mode="input", default=1.5, view={"label": "Retail Load"}),
        "retail_expo_tp": hx.Float(mode="output", view={"label": "Technical Premium"}),
        "all_else_expo": hx.Float(mode="override", view={"label": "Everything Else"}),
        "all_else_pct_of_total": hx.Float(mode="output", view={"label": "% of Total"}),
        "all_else_load": hx.Float(mode="input", default=1.0, view={"label": "Everything Else Load"}),
        "all_else_expo_tp": hx.Float(mode="output", view={"label": "Technical Premium"}),
        "technical_deductions": hx.Float(mode="output", view={"label": "Technical Annual Storage Rate Base Deductions"}),
        "technical_rate": hx.Float(mode="output", view={"label": "Technical Annual Storage Rate"}),
        "actual_rate": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Actual Storage Rate (Annual)"}),
        "pct_of_technical": hx.Float(mode="output", view={"label": "Percentage of Technical"}),
    })
    cds.extend_node_rater_defined("cds/layers/coverages/specie_transit", {
        "transit_flag": hx.Bool(mode="input", default=True, view={"label": "Transit"}),
        "base_rate": hx.Str(mode="output", view={"label": "Base Rate"}),
        "commodity": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Commodity"}),
        "commodity_factor": hx.Float(mode="output", view={"label": "Factor"}),
        "trans_vals": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Expo'd Stock Vals"}),
        "trans_vals_factor": hx.Float(mode="output", view={"label": " "}),
        "deductible_level": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Deductible Level"}),
        "deductible_factor": hx.Float(mode="override", view={"label": " "}),
        "excess_factor": hx.Float(mode="output", view={"label": " "}),
        "type_of_cover": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Type of Cover"}),
        "type_of_cover_factor": hx.Float(mode="output", view={"label": " "}),
        "uw_discretion": hx.Str(mode="input", default=None, optionality="optional", view={"label": "UW Discretion"}),
        "uw_discretion_weight": hx.Float(mode="input", default=1.0, view={"label": " "}),
        "technical_deductions": hx.Float(mode="output", view={"label": "Technical Annual Transit Rate Base Deductions"}),
        "technical_rate": hx.Float(mode="output", view={"label": "Technical Annual Transit Rate"}),
        "actual_rate": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Actual Transit Rate (Annual)"}),
        "actual_premium": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Actual Transit Premium (Term)"}),
        "pct_of_technical": hx.Float(mode="output", view={"label": "Percentage of Technical"}),
    })
    cds.extend_node_rater_defined("cds/layers/coverages/specie_storage", {
        "storage_flag": hx.Bool(mode="input", default=True, view={"label": "Storage"}),
        "base_rate": hx.Float(mode="output", view={"label": "Base Rate"}),
        "commodity": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Commodity"}),
        "commodity_factor": hx.Float(mode="output", view={"label": " "}),
        "stock_vals": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Expo'D Stock Vals"}),
        "stock_vals_factor": hx.Float(mode="output", view={"label": " "}),
        "deductible_level": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Deductible Level"}),
        "deductible_factor": hx.Float(mode="override", view={"label": " "}),
        "excess_factor": hx.Float(mode="override", view={"label": " "}),
        "survey": hx.Bool(mode="input", default=True, view={"label": "Satis. Survey Report"}),
        "survey_factor": hx.Float(mode="output", view={"label": " "}),
        "risk_mgmt": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Risk Management"}),
        "risk_mgmt_weight": hx.Float(mode="input", default=1.0, view={"label": " "}),
        "type_of_cover": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Type of Cover"}),
        "type_of_cover_factor": hx.Float(mode="output", view={"label": " "}),
        "uw_discretion": hx.Str(mode="input", default=None, optionality="optional", view={"label": "UW Discretion"}),
        "uw_discretion_weight": hx.Float(mode="input", default=1.0, view={"label": " "}),
        "rate": hx.Float(mode="output", view={"label": "Storage Rate"}),
        "avg_val_pcm": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Avg Val Expo'd PCM"}),
        "cat_expo": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Cat Expo"}),
        "cat_pct_of_total": hx.Float(mode="output", view={"label": "% of Total"}),
        "combined_cat_load": hx.Float(mode="output", view={"label": "Combined Cat Load"}),
        "cat_expo_tp": hx.Float(mode="override", view={"label": "Technical Premium"}),
        "country": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Country"}),
        "country_cat_expo": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Cat Exposure Amount"}),
        "country_cat_load": hx.Float(mode="output", view={"label": "Load Applied"}),
        "non_cat_expo": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Non-CAT Expo"}),
        "non_cat_pct_of_total": hx.Float(mode="output", view={"label": "% of Total"}),
        "non_cat_load": hx.Float(mode="output", view={"label": "Non-CAT Load"}),
        "non_cat_expo_tp": hx.Float(mode="output", view={"label": "Technical Premium"}),
        "technical_deductions": hx.Float(mode="output", view={"label": "Technical Annual Storage Rate Base Deductions"}),
        "technical_rate": hx.Float(mode="output", view={"label": "Technical Annual Storage Rate"}),
        "actual_rate": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Actual Storage Rate (Annual)"}),
        "pct_of_technical": hx.Float(mode="output", view={"label": "Percentage of Technical"}),
    })
    cds.extend_node_rater_defined("cds/layers/coverages/conloss_transit", {
        "transit_flag": hx.Bool(mode="input", default=True, view={"label": "Transit"}),
        "base_rate": hx.Float(mode="output", view={"label": "Base Rate"}),
        "trans_vals": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Est Ann Transit Vals"}),
        "trans_vals_factor": hx.Float(mode="output", view={"label": "Factor"}),
        "deductible_level": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Deductible"}),
        "deductible_factor": hx.Float(mode="override", view={"label": " "}),
        "packaging_1": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Packaging"}),
        "packaging_2": hx.Str(mode="input", default=None, optionality="optional", view={"label": " "}),
        "packaging_1_factor": hx.Float(mode="input", default=None, optionality="optional", view={"label": " "}),
        "packaging_2_factor": hx.Float(mode="input", default=None, optionality="optional", view={"label": " "}),
        "packaging_check": hx.Float(mode="output", view={"label": "Check"}),
        "conv_air": hx.Str(mode="input", default="Air", view={"label": "Conveyance"}),
        "conv_land": hx.Str(mode="input", default="Land", view={"label": " "}),
        "conv_sea": hx.Str(mode="input", default="Sea", view={"label": " "}),
        "conv_air_factor": hx.Float(mode="input", default=None, optionality="optional", view={"label": " "}),
        "conv_land_factor": hx.Float(mode="input", default=None, optionality="optional", view={"label": " "}),
        "conv_sea_factor": hx.Float(mode="input", default=None, optionality="optional", view={"label": " "}),
        "conv_check": hx.Float(mode="output", view={"label": "Check"}),
        "voyage": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Voyage"}),
        "voyage_factor": hx.Float(mode="output", view={"label": " "}),
        "surveyor": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Surveyor Present"}),
        "surveyor_factor": hx.Float(mode="output", view={"label": " "}),
        "vessel": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Vessel"}),
        "vessel_factor": hx.Float(mode="output", view={"label": " "}),
        "uw_discretion": hx.Str(mode="input", default=None, optionality="optional", view={"label": "UW Discretion"}),
        "uw_discretion_weight": hx.Float(mode="input", default=1.0, view={"label": " "}),
        "type_of_cover": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Type Of Cover"}),
        "type_of_cover_factor": hx.Float(mode="output", view={"label": " "}),
        "technical_deductions": hx.Float(mode="output", view={"label": "Technical Annual Transit Rate Base Deductions"}),
        "technical_rate": hx.Float(mode="output", view={"label": "Technical Annual Transit Rate"}),
        "actual_rate": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Actual Transit Rate"}),
        "actual_premium": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Actual Transit Premium"}),
        "pct_of_technical": hx.Float(mode="output", view={"label": "Percentage of Technical"}),
    })
    cds.extend_node_rater_defined("cds/layers/coverages/conloss", {
        "conloss_flag": hx.Bool(mode="input", default=True, view={"label": "Con Loss"}),
        "base_rate": hx.Str(mode="output", view={"label": "Base Rate"}),
        "limit_factor": hx.Float(mode="output", view={"label": " "}),
        "exposure": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Exposure"}),
        "exposure_factor": hx.Float(mode="output", view={"label": " "}),
        "indemnity_period": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Indemnity Period"}),
        "deductible_level": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Deductible"}),
        "deductible_factor": hx.Float(mode="output", view={"label": " "}),
        "uw_discretion": hx.Str(mode="input", default=None, optionality="optional", view={"label": "UW Discretion"}),
        "uw_discretion_weight": hx.Float(mode="input", default=1.0, view={"label": " "}),
        "technical_deductions": hx.Float(mode="output", view={"label": "Technical Con Loss Rate Base Deductions"}),
        "technical_rate": hx.Float(mode="output", view={"label": "Technical Con Loss Rate"}),
        "actual_rate": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Actual Storage Rate"}),
        "pct_of_technical": hx.Float(mode="output", view={"label": "Percentage Of Technical"}),
    })
    cds.override_node_properties("cds/layers/coverages/cargo_transit/technical_premium", {
        "view": {"label": "Technical Transit Premium (Term)"},
    })
    cds.override_node_properties("cds/layers/coverages/cargo_transit/quoted_premium", {
        "view": {"label": "Actual Transit Premium (Term)"},
    })
    cds.override_node_properties("cds/layers/coverages/cargo_storage/technical_premium", {
        "view": {"label": "Technical Storage Premium (Term)"},
    })
    cds.override_node_properties("cds/layers/coverages/cargo_storage/quoted_premium", {
        "view": {"label": "Actual Storage Premium (Term)"},
    })
    cds.override_node_properties("cds/layers/coverages/specie_transit/technical_premium", {
        "view": {"label": "Technical Transit Premium (Term)"},
    })
    cds.override_node_properties("cds/layers/coverages/specie_storage/technical_premium", {
        "view": {"label": "Technical Storage Premium (Term)"},
    })
    cds.override_node_properties("cds/layers/coverages/specie_storage/quoted_premium", {
        "view": {"label": "Actual Storage Premium (Term)"},
    })
    cds.override_node_properties("cds/layers/coverages/conloss_transit/technical_premium", {
        "view": {"label": "Technical Transit Premium"},
    })
    cds.override_node_properties("cds/layers/coverages/conloss/limit", {
        "view": {"label": "Indemnity Limit"},
    })
    cds.override_node_properties("cds/layers/coverages/conloss/technical_premium", {
        "view": {"label": "Technical Con Loss Premium"},
    })
    cds.override_node_properties("cds/layers/coverages/conloss/quoted_premium", {
        "view": {"label": "Actual Storage Premium"},
    })
