raise Exception("""This file is generated

Do not edit manually as all of the changes will be lost.
This is the static version of your Data Schema that will allow easier debugging.
""")

import hx_data_schema as hx


@hx.data_schema
def data_schema():
    return hx.Structure(children={
        "hx_core": hx.Structure(children={
            "inception_date": hx.Date(default="2018-01-01", mode="input", view={"label": "Inception Date"}),
            "expiry_date": hx.Date(default="2018-12-31", mode="input", view={"label": "Expiry Date"}),
            "model_premium": hx.Float(mode="output", view={"label": "Model Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
            "charged_premium": hx.Float(mode="output", view={"label": "Charged Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
            "premium_currency": hx.Str(mode="output", view={"label": "Premium Currency"}),
            "ulr": hx.Float(mode="output", view={"label": "ULR", "format": {"output": "percent", "mantissa": 1}}),
            "class_code": hx.Str(mode="output", view={"label": "Class Code"}),
        }, view={"label": "Hx Core"}),
        "cds": hx.Structure(view={"label": "cds"}, children={
            "key_industry": hx.Structure(view={"label": "Key Industry"}, children={
                "code_type": hx.Str(mode="input", default=None, optionality="optional", options=["NAICS", "SIC_USA", "SIC_UK", "UW Defined"], view={"label": "Industry Code Type"}),
                "code": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Industry Code"}),
                "code_name": hx.Str(mode="input", default_index=0, optionality="required", options_column="occupation_name", options_table="table_input_occupations", view={"label": "Occupation"}),
                "sub_occupation": hx.Structure(children={
                    "group": hx.Int(mode="output"),
                    "list": hx.List(mode="output", children={
                        "name": hx.Str(mode="output"),
                    }),
                    "name": hx.Str(mode="input", default=None, optionality="optional", options_data="../list", options_field="name", view={"label": "Sub Occupation"}),
                }),
            }),
            "exposure": hx.Structure(view={"label": "Exposure"}, children={
                "aggregate": hx.Structure(view={"label": "Aggregate"}, children={
                    "total_revenue": hx.Int(mode="output", view={"label": "Total Revenue", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "med_mal": hx.Structure(children={
                        "total_credit_or_debit": hx.Float(mode="output", view={"label": "Total Credit/Debit", "format": {"output": "percent", "mantissa": 0}}),
                        "total_endorsement": hx.Float(mode="output", view={"label": "Endorsement Total Credit/Debit", "format": {"output": "percent", "mantissa": 0}}),
                    }),
                    "staffing": hx.Structure(children={
                        "total": hx.Float(mode="output", optionality="optional", view={"label": "Total", "format": {"output": "percent", "mantissa": 0}}),
                    }),
                }),
            }),
            "standard_fields": hx.Structure(view={"label": "Standard Fields"}, children={
                "insured_name": hx.Str(mode="input", default=None, optionality="optional", options_column="firm_name", options_table="table_input_reference_firms", view={"label": "Insured Name"}),
                "broker": hx.Str(mode="input", default=None, optionality="optional", options_column="name", options_table="table_input_underwriters", view={"label": "Broker Name"}),
                "expiry_date": hx.Date(mode="output", view={"label": "Expiry Date"}),
                "inception_date": hx.Date(mode="output", view={"label": "Inception Date"}),
                "insured_country": hx.Str(mode="input", default=None, optionality="optional", options=["", "AND", "ARE", "AFG", "ATG", "AIA", "ALB", "ARM", "AGO", "ATA", "ARG", "ASM", "AUT", "AUS", "ABW", "ALA", "AZE", "BIH", "BRB", "BGD", "BEL", "BFA", "BGR", "BHR", "BDI", "BEN", "BLM", "BMU", "BRN", "BOL", "BES", "BRA", "BHS", "BTN", "BVT", "BWA", "BLR", "BLZ", "CAN", "CCK", "COD", "CAF", "COG", "CHE", "CIV", "COK", "CHL", "CMR", "CHN", "COL", "CRI", "CUB", "CPV", "CUW", "CXR", "CYP", "CZE", "DEU", "DJI", "DNK", "DMA", "DOM", "DZA", "ECU", "EST", "EGY", "ESH", "ERI", "ESP", "ETH", "FIN", "FJI", "FLK", "FSM", "FRO", "FRA", "GAB", "GBR", "GRD", "GEO", "GUF", "GGY", "GHA", "GIB", "GRL", "GMB", "GIN", "GLP", "GNQ", "GRC", "SGS", "GTM", "GUM", "GNB", "GUY", "HKG", "HMD", "HND", "HRV", "HTI", "HUN", "IDN", "IRL", "ISR", "IMN", "IND", "IOT", "IRQ", "IRN", "ISL", "ITA", "JEY", "JAM", "JOR", "JPN", "KEN", "KGZ", "KHM", "KIR", "COM", "KNA", "PRK", "KOR", "KWT", "CYM", "KAZ", "LAO", "LBN", "LCA", "LIE", "LKA", "LBR", "LSO", "LTU", "LUX", "LVA", "LBY", "MAR", "MCO", "MDA", "MNE", "MAF", "MDG", "MHL", "MKD", "MLI", "MMR", "MNG", "MAC", "MNP", "MTQ", "MRT", "MSR", "MLT", "MUS", "MDV", "MWI", "MEX", "MYS", "MOZ", "NAM", "NCL", "NER", "NFK", "NGA", "NIC", "NLD", "NOR", "NPL", "NRU", "NIU", "NZL", "OMN", "PAN", "PER", "PYF", "PNG", "PHL", "PAK", "POL", "SPM", "PCN", "PRI", "PSE", "PRT", "PLW", "PRY", "QAT", "REU", "ROU", "SRB", "RUS", "RWA", "SAU", "SLB", "SYC", "SDN", "SWE", "SGP", "SHN", "SVN", "SJM", "SVK", "SLE", "SMR", "SEN", "SOM", "SUR", "SSD", "STP", "SLV", "SXM", "SYR", "SWZ", "TCA", "TCD", "ATF", "TGO", "THA", "TJK", "TKL", "TLS", "TKM", "TUN", "TON", "TUR", "TTO", "TUV", "TWN", "TZA", "UKR", "UGA", "UMI", "USA", "URY", "UZB", "VAT", "VCT", "VEN", "VGB", "VIR", "VNM", "VUT", "WLF", "WSM", "YEM", "MYT", "ZAF", "ZMB", "ZWE", "ATB", "BYS", "CTE", "CSK", "DHY", "ATN", "AFI", "ATF", "DDR", "GEL", "JTN", "MID", "NHB", "PCI", "PCZ", "SKM", "RHO", "PUS", "HVO", "VDR", "WAK", "YMD"], view={"label": "Insured Country"}),
                "insured_postal_code": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Insured Postal Code"}),
                "insured_state_or_province": hx.Str(mode="input", default_index=0, optionality="required", options_column="state_code", options_table="table_input_states", view={"label": "State"}),
                "is_admitted_or_surplus": hx.Str(mode="input", default=None, optionality="optional", options=["Admitted", "Surplus"], view={"label": "Is Admitted Or Surplus"}),
                "is_free_trade_zone": hx.Bool(mode="input", default=False, optionality="required", view={"label": "Is Free-Trade Zone"}),
                "is_renewal": hx.Bool(mode="input", default=False, optionality="required", view={"label": "Is Renewal"}),
                "underwriter": hx.Str(mode="input", default=None, optionality="optional", options_column="name", options_table="table_input_underwriters", view={"label": "Underwriter"}),
                "policy_reference": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Policy Reference"}),
                "facility_reference": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Facility Reference"}),
                "benchmark_class": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Benchmark Class"}),
                "uw_rationale": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Underwriter Rationale"}),
                "trifocus": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Trifocus"}),
                "rating_methodology": hx.Str(mode="input", default="Rater", options=["Rater", "Case Priced"], view={"label": "Rater Priced or Case Priced?"}),
                "is_case_priced": hx.Bool(mode="output", view={"label": "Is Case Priced"}),
                "is_rater_priced": hx.Bool(mode="output", view={"label": "Is Rater Priced"}),
            }),
            "layers": hx.List(mode="input", default_element_count=3, max_element_count=10, view={"label": "Layers"}, children={
                "limit": hx.Float(mode="input", default=None, async_input=["rarc_task"], optionality="optional", options_data="../liability_limits_EEC/list", options_field="limit", view={"label": "Liability Limits EEC", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "excess": hx.Float(mode="input", default=None, async_input=["rarc_task"], optionality="optional", view={"label": "Excess", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "deductible": hx.Float(mode="input", default=None, async_input=["rarc_task"], optionality="optional", options_data="../primary_deductible/list", options_field="deductible", view={"label": "Primary Deductible", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "aggregate_limit": hx.Float(mode="input", default=None, async_input=["rarc_task"], optionality="optional", options_data="../liability_limits_AGG/list", options_field="limit", view={"label": "Liability Limits AGG", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "aggregate_excess": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Aggregate Excess", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "aggregate_deductible": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Aggregate Deductible", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "currency": hx.Str(mode="input", default=None, optionality="optional", options=["ADP", "AFA", "AON", "AOR", "ATS", "AZM", "BEF", "BGL", "BRE", "BUK", "BYB", "BYR", "CSD", "CSK", "CYP", "DDM", "DEM", "ECS", "EEK", "ESP", "FIM", "FRF", "GHC", "GRD", "GWP", "HRK", "IEP", "ITL", "LTL", "LUF", "LVL", "MGF", "MRO", "MTL", "MXP", "MZM", "NIC", "NLG", "PES", "PLZ", "PTE", "ROL", "RUR", "SDD", "SDP", "SIT", "SKK", "SRG", "STD", "SUR", "TRL", "UYP", "VEB", "VEF", "XEU", "YUM", "ZMK", "ZRN", "ZRZ", "ZWD", "ZWR", "AED", "AFN", "ALL", "AMD", "ANG", "AOA", "ARS", "AUD", "AWG", "AZN", "BAM", "BBD", "BDT", "BGN", "BHD", "BIF", "BMD", "BND", "BOB", "BOV", "BRL", "BSD", "BTN", "BWP", "BYN", "BZD", "CAD", "CDF", "CHE", "CHF", "CHW", "CLF", "CLP", "CNY", "COP", "COU", "CRC", "CUC", "CUP", "CVE", "CZK", "DJF", "DKK", "DOP", "DZD", "EGP", "ERN", "ETB", "EUR", "FJD", "FKP", "GBP", "GEL", "GHS", "GIP", "GMD", "GNF", "GTQ", "GYD", "HKD", "HNL", "HTG", "HUF", "IDR", "ILS", "INR", "IQD", "IRR", "ISK", "JMD", "JOD", "JPY", "KES", "KGS", "KHR", "KMF", "KPW", "KRW", "KWD", "KYD", "KZT", "LAK", "LBP", "LKR", "LRD", "LSL", "LYD", "MAD", "MDL", "MGA", "MKD", "MMK", "MNT", "MOP", "MRU", "MUR", "MVR", "MWK", "MXN", "MXV", "MYR", "MZN", "NAD", "NGN", "NIO", "NOK", "NPR", "NZD", "OMR", "PAB", "PEN", "PGK", "PHP", "PKR", "PLN", "PYG", "QAR", "RON", "RSD", "RUB", "RWF", "SAR", "SBD", "SCR", "SDG", "SEK", "SGD", "SHP", "SLE", "SLL", "SOS", "SRD", "SSP", "STN", "SVC", "SYP", "SZL", "THB", "TJS", "TMT", "TND", "TOP", "TRY", "TTD", "TWD", "TZS", "UAH", "UGX", "USD", "USN", "UYI", "UYU", "UYW", "UZS", "VED", "VES", "VND", "VUV", "WST", "XAF", "XAG", "XAU", "XBA", "XBB", "XBC", "XBD", "XCD", "XDR", "XOF", "XPD", "XPF", "XPT", "XSU", "XTS", "XUA", "XXX", "YER", "ZAR", "ZMW", "ZWL"], view={"label": "Currency"}),
                "section_reference": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Section Reference"}),
                "brokerage": hx.Float(mode="input", default=0, async_input=["rarc_task"], optionality="required", view={"label": "Brokerage", "format": {"output": "percent", "mantissa": 1}}),
                "written_line": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Written Line", "format": {"output": "percent", "mantissa": 1}}),
                "premium": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Gross Bound Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "status": hx.Str(mode="input", default=None, optionality="optional", options=["Assessment Pending", "Rating", "Quoted", "Bound", "Post Bind Complete", "Declined", "Not Taken Up"], view={"label": "Status", "options": {"input": {"label": "Status"}, "read_only": {"label": "Deal Status by Renewal Layers", "read_only": True}}}),
                "is_primary_excess": hx.Str(mode="input", default=None, optionality="optional", options=["Primary", "Excess"], view={"label": "Primary or Excess"}),
                "benchmark_premium": hx.Float(mode="output", async_input=["rarc_task"], optionality="optional", view={"label": "Gross Benchmark Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "bpi": hx.Float(mode="output", optionality="optional", view={"label": "BPI", "format": {"output": "percent", "mantissa": 1}}),
                "bpi_pre_uw_adj": hx.Float(mode="output", optionality="optional", view={"label": "BPI (Pre-UW Adjustment)", "format": {"output": "percent", "mantissa": 1}}),
                "model_premium": hx.Float(mode="output", optionality="optional", view={"label": "Gross Model Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "unity_premium": hx.Float(mode="output", optionality="optional", view={"label": "Gross Unity Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "quoted_premium": hx.Float(mode="input", default=0, async_input=["rarc_task"], optionality="required", view={"label": "Gross Quoted Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "technical_premium": hx.Float(mode="output", optionality="optional", view={"label": "Gross Technical Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "technical_premium_pre_uw_adj": hx.Float(mode="output", optionality="optional", view={"label": "Gross Technical Premium (Pre-UW Adjustment)", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "technical_premium_net": hx.Float(mode="output", optionality="optional", view={"label": "Net Technical Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "tpi": hx.Float(mode="output", optionality="optional", view={"label": "TPI", "format": {"output": "percent", "mantissa": 1}}),
                "tpi_pre_uw_adj": hx.Float(mode="output", optionality="optional", view={"label": "TPI (Pre-UW Adjustment)", "format": {"output": "percent", "mantissa": 1}}),
                "pflr_att": hx.Float(mode="output", optionality="optional", view={"label": "Priced-for Loss Ratio (Att)", "format": {"output": "percent", "mantissa": 1}}),
                "pflr_cat": hx.Float(mode="output", optionality="optional", view={"label": "Priced-for Loss Ratio (Cat)", "format": {"output": "percent", "mantissa": 1}}),
                "pflr": hx.Float(mode="output", optionality="optional", view={"label": "Priced-for Loss Ratio", "format": {"output": "percent", "mantissa": 1}}),
                "roc": hx.Float(mode="output", optionality="optional", view={"label": "Return on Capital", "format": {"output": "percent", "mantissa": 1}}),
                "uw_adj_impact": hx.Float(mode="output", optionality="optional", view={"label": "Impact of Underwriting Adjustments", "format": {"output": "percent", "mantissa": 1}}),
                "trifocus": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Trifocus"}),
                "expected_loss_cost": hx.Float(mode="output", optionality="optional", view={"label": "Expected Loss Cost", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "expected_loss_cost_pre_uw_adj": hx.Float(mode="output", optionality="optional", view={"label": "Expected Loss Cost (Pre-UW Ajustment)", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "coverages": hx.Structure(view={"label": "Coverages"}, children={
                    "option": hx.Structure(view={"label": "label"}, children={
                        "limit": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Limit", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "excess": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Excess", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "deductible": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Deductible", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "aggregate_limit": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Aggregate Limit", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "aggregate_excess": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Aggregate Excess", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "aggregate_deductible": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Aggregate Deductible", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "currency": hx.Str(mode="input", default=None, optionality="optional", options=["ADP", "AFA", "AON", "AOR", "ATS", "AZM", "BEF", "BGL", "BRE", "BUK", "BYB", "BYR", "CSD", "CSK", "CYP", "DDM", "DEM", "ECS", "EEK", "ESP", "FIM", "FRF", "GHC", "GRD", "GWP", "HRK", "IEP", "ITL", "LTL", "LUF", "LVL", "MGF", "MRO", "MTL", "MXP", "MZM", "NIC", "NLG", "PES", "PLZ", "PTE", "ROL", "RUR", "SDD", "SDP", "SIT", "SKK", "SRG", "STD", "SUR", "TRL", "UYP", "VEB", "VEF", "XEU", "YUM", "ZMK", "ZRN", "ZRZ", "ZWD", "ZWR", "AED", "AFN", "ALL", "AMD", "ANG", "AOA", "ARS", "AUD", "AWG", "AZN", "BAM", "BBD", "BDT", "BGN", "BHD", "BIF", "BMD", "BND", "BOB", "BOV", "BRL", "BSD", "BTN", "BWP", "BYN", "BZD", "CAD", "CDF", "CHE", "CHF", "CHW", "CLF", "CLP", "CNY", "COP", "COU", "CRC", "CUC", "CUP", "CVE", "CZK", "DJF", "DKK", "DOP", "DZD", "EGP", "ERN", "ETB", "EUR", "FJD", "FKP", "GBP", "GEL", "GHS", "GIP", "GMD", "GNF", "GTQ", "GYD", "HKD", "HNL", "HTG", "HUF", "IDR", "ILS", "INR", "IQD", "IRR", "ISK", "JMD", "JOD", "JPY", "KES", "KGS", "KHR", "KMF", "KPW", "KRW", "KWD", "KYD", "KZT", "LAK", "LBP", "LKR", "LRD", "LSL", "LYD", "MAD", "MDL", "MGA", "MKD", "MMK", "MNT", "MOP", "MRU", "MUR", "MVR", "MWK", "MXN", "MXV", "MYR", "MZN", "NAD", "NGN", "NIO", "NOK", "NPR", "NZD", "OMR", "PAB", "PEN", "PGK", "PHP", "PKR", "PLN", "PYG", "QAR", "RON", "RSD", "RUB", "RWF", "SAR", "SBD", "SCR", "SDG", "SEK", "SGD", "SHP", "SLE", "SLL", "SOS", "SRD", "SSP", "STN", "SVC", "SYP", "SZL", "THB", "TJS", "TMT", "TND", "TOP", "TRY", "TTD", "TWD", "TZS", "UAH", "UGX", "USD", "USN", "UYI", "UYU", "UYW", "UZS", "VED", "VES", "VND", "VUV", "WST", "XAF", "XAG", "XAU", "XBA", "XBB", "XBC", "XBD", "XCD", "XDR", "XOF", "XPD", "XPF", "XPT", "XSU", "XTS", "XUA", "XXX", "YER", "ZAR", "ZMW", "ZWL"], view={"label": "Currency"}),
                        "section_reference": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Section Reference"}),
                        "brokerage": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Brokerage", "format": {"output": "percent", "mantissa": 1}}),
                        "written_line": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Written Line", "format": {"output": "percent", "mantissa": 1}}),
                        "premium": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Gross Bound Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "status": hx.Str(mode="input", default=None, optionality="optional", options=["Assessment Pending", "Rating", "Quoted", "Bound", "Post Bind Complete", "Declined", "Not Taken Up"], view={"label": "Status"}),
                        "benchmark_premium": hx.Float(mode="output", optionality="optional", view={"label": "Gross Benchmark Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "bpi": hx.Float(mode="output", optionality="optional", view={"label": "BPI", "format": {"output": "percent", "mantissa": 1}}),
                        "bpi_pre_uw_adj": hx.Float(mode="output", optionality="optional", view={"label": "BPI (Pre-UW Adjustment)", "format": {"output": "percent", "mantissa": 1}}),
                        "model_premium": hx.Float(mode="output", optionality="optional", view={"label": "Gross Model Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "unity_premium": hx.Float(mode="output", optionality="optional", view={"label": "Gross Unity Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "quoted_premium": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Gross Quoted Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "technical_premium": hx.Float(mode="output", optionality="optional", view={"label": "Gross Technical Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "technical_premium_pre_uw_adj": hx.Float(mode="output", optionality="optional", view={"label": "Gross Technical Premium (Pre-UW Adjustment)", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "technical_premium_net": hx.Float(mode="output", optionality="optional", view={"label": "Net Technical Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "tpi": hx.Float(mode="output", optionality="optional", view={"label": "TPI", "format": {"output": "percent", "mantissa": 1}}),
                        "tpi_pre_uw_adj": hx.Float(mode="output", optionality="optional", view={"label": "TPI (Pre-UW Adjustment)", "format": {"output": "percent", "mantissa": 1}}),
                        "pflr_att": hx.Float(mode="output", optionality="optional", view={"label": "Priced-for Loss Ratio (Att)", "format": {"output": "percent", "mantissa": 1}}),
                        "pflr_cat": hx.Float(mode="output", optionality="optional", view={"label": "Priced-for Loss Ratio (Cat)", "format": {"output": "percent", "mantissa": 1}}),
                        "pflr": hx.Float(mode="output", optionality="optional", view={"label": "Priced-for Loss Ratio", "format": {"output": "percent", "mantissa": 1}}),
                        "roc": hx.Float(mode="output", optionality="optional", view={"label": "Return on Capital", "format": {"output": "percent", "mantissa": 1}}),
                        "uw_adj_impact": hx.Float(mode="output", optionality="optional", view={"label": "Impact of Underwriting Adjustments", "format": {"output": "percent", "mantissa": 1}}),
                    }),
                }),
                "rate_change": hx.Structure(view={"label": "Rate Change"}, children={
                    "exposure_change": hx.Structure(view={"label": "Exposure Change"}, children={
                        "model_calculated": hx.Float(mode="output", async_output=["rarc_task"], view={"label": "Model %", "format": {"output": "percent", "mantissa": 0}}),
                        "uw_selected": hx.Float(mode="override", view={"label": "UW Selected %", "format": {"output": "percent", "mantissa": 0}}),
                        "comments": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Comment"}),
                    }),
                    "risk_characteristics_change": hx.Structure(view={"label": "Risk Characteristics Change"}, children={
                        "model_calculated": hx.Float(mode="output", async_output=["rarc_task"], view={"label": "Model %", "format": {"output": "percent", "mantissa": 0}}),
                        "uw_selected": hx.Float(mode="override", view={"label": "UW Selected %", "format": {"output": "percent", "mantissa": 0}}),
                        "comments": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Comment"}),
                    }),
                    "limit_change": hx.Structure(view={"label": "Limit Change"}, children={
                        "model_calculated": hx.Float(mode="output", async_output=["rarc_task"], view={"label": "Model %", "format": {"output": "percent", "mantissa": 0}}),
                        "uw_selected": hx.Float(mode="override", view={"label": "UW Selected %", "format": {"output": "percent", "mantissa": 0}}),
                        "comments": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Comment"}),
                    }),
                    "deductible_change": hx.Structure(view={"label": "Deductible Change"}, children={
                        "model_calculated": hx.Float(mode="output", async_output=["rarc_task"], view={"label": "Model %", "format": {"output": "percent", "mantissa": 0}}),
                        "uw_selected": hx.Float(mode="override", view={"label": "UW Selected %", "format": {"output": "percent", "mantissa": 0}}),
                        "comments": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Comment"}),
                    }),
                    "terms_conditions_change": hx.Structure(view={"label": "Terms & Conditions Change"}, children={
                        "model_calculated": hx.Float(mode="output", async_output=["rarc_task"], view={"label": "Model %", "format": {"output": "percent", "mantissa": 0}}),
                        "uw_selected": hx.Float(mode="override", view={"label": "UW Selected %", "format": {"output": "percent", "mantissa": 0}}),
                        "comments": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Comment"}),
                    }),
                    "other_change": hx.Structure(view={"label": "Other Change"}, children={
                        "model_calculated": hx.Float(mode="output", async_output=["rarc_task"], view={"label": "Model %", "format": {"output": "percent", "mantissa": 0}}),
                        "uw_selected": hx.Float(mode="override", view={"label": "UW Selected %", "format": {"output": "percent", "mantissa": 0}}),
                        "comments": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Comment"}),
                    }),
                    "brokerage_change": hx.Structure(view={"label": "Brokerage Change"}, children={
                        "model_calculated": hx.Float(mode="output", async_output=["rarc_task"], view={"label": "Model %", "format": {"output": "percent", "mantissa": 0}}),
                        "uw_selected": hx.Float(mode="override", view={"label": "UW Selected %", "format": {"output": "percent", "mantissa": 0}}),
                        "comments": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Comment"}),
                    }),
                    "rate_change": hx.Structure(view={"label": "Risk Adjusted Rate Change"}, children={
                        "model_calculated": hx.Float(mode="output", view={"label": "Model %", "format": {"output": "percent", "mantissa": 0}}),
                        "uw_selected": hx.Float(mode="output", view={"label": "UW Selected %", "format": {"output": "percent", "mantissa": 0}}),
                        "comments": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Comment"}),
                        "lloyds_limit_attachment_point_change": hx.Float(mode="output", view={"label": "Lloyds's Limit Attachment Point Change", "format": {"output": "percent", "mantissa": 0}}),
                        "lloyds_breadth_of_cover_change": hx.Float(mode="output", view={"label": "Lloyds's Breadth of Cover Change", "format": {"output": "percent", "mantissa": 0}}),
                        "other_factors_change": hx.Float(mode="output", view={"label": "Other Factors Change", "format": {"output": "percent", "mantissa": 0}}),
                    }),
                    "rebased_expiring_premium": hx.Float(mode="output", async_output=["rarc_task"], view={"label": "Rebased Expiring Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "expiring_layer": hx.Int(mode="input", default=1, async_input=["expiring_policy_fetch_task", "rarc_task"], options=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], view={"label": "Expiring Layer"}),
                    "premium_policy_term_beazley_share": hx.Structure(view={"label": "Premium - Policy Term (Beazley Share)"}, children={
                        "renewal": hx.Float(mode="output", view={"label": "Renewal", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "expiring": hx.Float(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task"], view={"label": "Expiring", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    }),
                    "premium_policy_term_100pct": hx.Structure(view={"label": "Premium - Policy Term (100% Share)"}, children={
                        "renewal": hx.Float(mode="output", view={"label": "Renewal", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "expiring": hx.Float(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task"], view={"label": "Expiring", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    }),
                    "premium_annualized_beazley_share": hx.Structure(view={"label": "Premium - Annualized (Beazley Share)"}, children={
                        "renewal": hx.Float(mode="output", view={"label": "Renewal", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "expiring": hx.Float(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task"], view={"label": "Expiring", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    }),
                    "premium_annualized_100pct": hx.Structure(view={"label": "Premium - Annualized (100% Share)"}, children={
                        "renewal": hx.Float(mode="output", view={"label": "Renewal", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "expiring": hx.Float(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task"], view={"label": "Expiring", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    }),
                    "expiring_policy_info": hx.Structure(children={
                        "expiring_exposure": hx.Float(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task"]),
                        "expiring_policy_length": hx.Float(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task"]),
                        "expiring_premium": hx.Float(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task"]),
                        "expiring_limit": hx.Float(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task"]),
                        "expiring_deductible": hx.Float(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task"]),
                        "expiring_brokerage": hx.Float(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task"]),
                        "expiring_write_line": hx.Float(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task"]),
                        "expiring_expected_loss": hx.Float(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task"]),
                    }),
                    "total_change": hx.Structure(view={"label": "Total Change dictates change of"}, children={
                        "calculated": hx.Float(mode="output", view={"label": "Model %", "format": {"output": "percent", "mantissa": 0}}),
                        "selected": hx.Float(mode="output", view={"label": "UW Selected %", "format": {"output": "percent", "mantissa": 0}}),
                        "comments": hx.Str(mode="input", default="", view={"label": "Comment"}),
                    }),
                    "simple_rate_change": hx.Float(mode="output", view={"label": "Pure Premium Change / Simple Rate Change", "format": {"output": "percent", "mantissa": 0}}),
                    "risk_adjusted_rate_change": hx.Structure(view={"label": "Underwriter Selected"}, children={
                        "technical": hx.Float(mode="output", view={"label": "Model Risk Adjusted Rate Change", "format": {"output": "percent", "mantissa": 0}}),
                        "technical_net_brokerage": hx.Float(mode="output", view={"format": {"output": "percent", "mantissa": 0}}),
                        "uw_selected": hx.Float(mode="output", view={"label": "UW Selected Risk Adjusted Rate Change", "format": {"output": "percent", "mantissa": 0}}),
                        "uw_selected_net_brokerage": hx.Float(mode="output", view={"label": "UW Selected Risk Adjusted Rate Change", "format": {"output": "percent", "mantissa": 0}}),
                    }),
                    "risk_adjusted_rate_change_case_priced": hx.Structure(view={"label": "Underwriter Selected"}, children={
                        "uw_selected": hx.Float(mode="override", view={"label": "UW Selected Risk Adjusted Rate Change", "format": {"output": "percent", "mantissa": 0}}),
                        "uw_selected_net_brokerage": hx.Float(mode="output", view={"label": "UW Selected Risk Adjusted Rate Change Net Brokerage", "format": {"output": "percent", "mantissa": 0}}),
                        "comments": hx.Str(mode="input", default="", view={"label": "Comment"}),
                    }),
                    "error_message": hx.Str(mode="output"),
                    "temp_storage": hx.Structure(children={
                        "quoted_premium": hx.Float(mode="output", async_output=["rarc_task"]),
                        "benchmark_premium": hx.Float(mode="output", async_output=["rarc_task"]),
                    }),
                }),
                "bpi_case_priced": hx.Float(mode="input", default=0, optionality="required", view={"label": "BPI (Case Priced)", "format": {"output": "percent", "mantissa": 1}}),
                "show_excess": hx.Bool(mode="output"),
                "liability_limits_EEC": hx.Structure(children={
                    "show": hx.Bool(mode="output"),
                    "list": hx.List(mode="output", children={
                        "limit": hx.Int(mode="output"),
                    }),
                }),
                "liability_limits_AGG": hx.Structure(children={
                    "show": hx.Bool(mode="output"),
                    "list": hx.List(mode="output", children={
                        "limit": hx.Int(mode="output"),
                    }),
                }),
                "product_liability_limits_AGG": hx.Int(mode="input", default=None, async_input=["rarc_task"], optionality="optional", options_column="limit", options_table="table_input_products_product_liability_limits", view={"label": "Product Liability Limits AGG", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "personal_advertising_liability_EEC": hx.Structure(children={
                    "show": hx.Bool(mode="output"),
                    "list": hx.List(mode="output", children={
                        "limit": hx.Int(mode="output"),
                    }),
                    "limit": hx.Int(mode="input", default=None, optionality="optional", options_data="../list", options_field="limit", view={"label": "Personal Advertising Liability EEC", "format": {"thousandSeparated": True, "mantissa": 0}}),
                }),
                "defence_outside_limits": hx.Structure(children={
                    "show": hx.Bool(mode="output"),
                    "list": hx.List(mode="output", children={
                        "limit": hx.Int(mode="output"),
                    }),
                    "limit": hx.Int(mode="input", default=None, async_input=["rarc_task"], optionality="optional", options_data="../list", options_field="limit", view={"label": "Defence Outside Limits", "format": {"thousandSeparated": True, "mantissa": 0}}),
                }),
                "general_liability": hx.Structure(children={
                    "limit_staffing": hx.Int(mode="output", view={"label": "General Liability Limits", "format": {"thousandSeparated": True, "mantissa": 0}}),
                }),
                "effective_rate": hx.Float(mode="output", view={"label": "Effective Rate", "format": {"output": "percent", "mantissa": 0}}),
                "primary_deductible": hx.Structure(children={
                    "show": hx.Bool(mode="output"),
                    "list": hx.List(mode="output", children={
                        "deductible": hx.Int(mode="output"),
                    }),
                }),
                "cob": hx.Structure(children={
                    "code_1": hx.Str(mode="input", default=None, optionality="optional", options_column="code", options_table="table_input_cob_codes", view={"label": "COB Code 1"}),
                    "code_2": hx.Str(mode="input", default=None, optionality="optional", options_column="code", options_table="table_input_cob_codes", view={"label": "COB Code 2"}),
                    "code_3": hx.Str(mode="input", default=None, optionality="optional", options_column="code", options_table="table_input_cob_codes", view={"label": "COB Code 3"}),
                    "premium_1": hx.Int(mode="input", default=None, optionality="optional", view={"label": "Percentage Premium 1", "format": {"output": "percent", "mantissa": 0}}),
                    "premium_2": hx.Int(mode="input", default=None, optionality="optional", view={"label": "Percentage Premium 2", "format": {"output": "percent", "mantissa": 0}}),
                    "premium_3": hx.Int(mode="input", default=None, optionality="optional", view={"label": "Percentage Premium 3", "format": {"output": "percent", "mantissa": 0}}),
                }),
                "premium_blueprint": hx.Structure(children={
                    "show": hx.Bool(mode="output"),
                    "list": hx.List(mode="output", children={
                        "limit": hx.Str(mode="output", view={"label": "Limit", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "premium": hx.Int(mode="output", view={"label": "Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    }),
                }),
            }),
            "currencies": hx.Structure(view={"label": "Currencies"}, children={
                "target_currency": hx.Str(mode="input", default=None, optionality="optional", options=["ADP", "AFA", "AON", "AOR", "ATS", "AZM", "BEF", "BGL", "BRE", "BUK", "BYB", "BYR", "CSD", "CSK", "CYP", "DDM", "DEM", "ECS", "EEK", "ESP", "FIM", "FRF", "GHC", "GRD", "GWP", "HRK", "IEP", "ITL", "LTL", "LUF", "LVL", "MGF", "MRO", "MTL", "MXP", "MZM", "NIC", "NLG", "PES", "PLZ", "PTE", "ROL", "RUR", "SDD", "SDP", "SIT", "SKK", "SRG", "STD", "SUR", "TRL", "UYP", "VEB", "VEF", "XEU", "YUM", "ZMK", "ZRN", "ZRZ", "ZWD", "ZWR", "AED", "AFN", "ALL", "AMD", "ANG", "AOA", "ARS", "AUD", "AWG", "AZN", "BAM", "BBD", "BDT", "BGN", "BHD", "BIF", "BMD", "BND", "BOB", "BOV", "BRL", "BSD", "BTN", "BWP", "BYN", "BZD", "CAD", "CDF", "CHE", "CHF", "CHW", "CLF", "CLP", "CNY", "COP", "COU", "CRC", "CUC", "CUP", "CVE", "CZK", "DJF", "DKK", "DOP", "DZD", "EGP", "ERN", "ETB", "EUR", "FJD", "FKP", "GBP", "GEL", "GHS", "GIP", "GMD", "GNF", "GTQ", "GYD", "HKD", "HNL", "HTG", "HUF", "IDR", "ILS", "INR", "IQD", "IRR", "ISK", "JMD", "JOD", "JPY", "KES", "KGS", "KHR", "KMF", "KPW", "KRW", "KWD", "KYD", "KZT", "LAK", "LBP", "LKR", "LRD", "LSL", "LYD", "MAD", "MDL", "MGA", "MKD", "MMK", "MNT", "MOP", "MRU", "MUR", "MVR", "MWK", "MXN", "MXV", "MYR", "MZN", "NAD", "NGN", "NIO", "NOK", "NPR", "NZD", "OMR", "PAB", "PEN", "PGK", "PHP", "PKR", "PLN", "PYG", "QAR", "RON", "RSD", "RUB", "RWF", "SAR", "SBD", "SCR", "SDG", "SEK", "SGD", "SHP", "SLE", "SLL", "SOS", "SRD", "SSP", "STN", "SVC", "SYP", "SZL", "THB", "TJS", "TMT", "TND", "TOP", "TRY", "TTD", "TWD", "TZS", "UAH", "UGX", "USD", "USN", "UYI", "UYU", "UYW", "UZS", "VED", "VES", "VND", "VUV", "WST", "XAF", "XAG", "XAU", "XBA", "XBB", "XBC", "XBD", "XCD", "XDR", "XOF", "XPD", "XPF", "XPT", "XSU", "XTS", "XUA", "XXX", "YER", "ZAR", "ZMW", "ZWL"], view={"label": "Target Currency"}),
                "source_currency": hx.Str(mode="input", default="USD", optionality="optional", options=["ADP", "AFA", "AON", "AOR", "ATS", "AZM", "BEF", "BGL", "BRE", "BUK", "BYB", "BYR", "CSD", "CSK", "CYP", "DDM", "DEM", "ECS", "EEK", "ESP", "FIM", "FRF", "GHC", "GRD", "GWP", "HRK", "IEP", "ITL", "LTL", "LUF", "LVL", "MGF", "MRO", "MTL", "MXP", "MZM", "NIC", "NLG", "PES", "PLZ", "PTE", "ROL", "RUR", "SDD", "SDP", "SIT", "SKK", "SRG", "STD", "SUR", "TRL", "UYP", "VEB", "VEF", "XEU", "YUM", "ZMK", "ZRN", "ZRZ", "ZWD", "ZWR", "AED", "AFN", "ALL", "AMD", "ANG", "AOA", "ARS", "AUD", "AWG", "AZN", "BAM", "BBD", "BDT", "BGN", "BHD", "BIF", "BMD", "BND", "BOB", "BOV", "BRL", "BSD", "BTN", "BWP", "BYN", "BZD", "CAD", "CDF", "CHE", "CHF", "CHW", "CLF", "CLP", "CNY", "COP", "COU", "CRC", "CUC", "CUP", "CVE", "CZK", "DJF", "DKK", "DOP", "DZD", "EGP", "ERN", "ETB", "EUR", "FJD", "FKP", "GBP", "GEL", "GHS", "GIP", "GMD", "GNF", "GTQ", "GYD", "HKD", "HNL", "HTG", "HUF", "IDR", "ILS", "INR", "IQD", "IRR", "ISK", "JMD", "JOD", "JPY", "KES", "KGS", "KHR", "KMF", "KPW", "KRW", "KWD", "KYD", "KZT", "LAK", "LBP", "LKR", "LRD", "LSL", "LYD", "MAD", "MDL", "MGA", "MKD", "MMK", "MNT", "MOP", "MRU", "MUR", "MVR", "MWK", "MXN", "MXV", "MYR", "MZN", "NAD", "NGN", "NIO", "NOK", "NPR", "NZD", "OMR", "PAB", "PEN", "PGK", "PHP", "PKR", "PLN", "PYG", "QAR", "RON", "RSD", "RUB", "RWF", "SAR", "SBD", "SCR", "SDG", "SEK", "SGD", "SHP", "SLE", "SLL", "SOS", "SRD", "SSP", "STN", "SVC", "SYP", "SZL", "THB", "TJS", "TMT", "TND", "TOP", "TRY", "TTD", "TWD", "TZS", "UAH", "UGX", "USD", "USN", "UYI", "UYU", "UYW", "UZS", "VED", "VES", "VND", "VUV", "WST", "XAF", "XAG", "XAU", "XBA", "XBB", "XBC", "XBD", "XCD", "XDR", "XOF", "XPD", "XPF", "XPT", "XSU", "XTS", "XUA", "XXX", "YER", "ZAR", "ZMW", "ZWL"], view={"label": "Source Currency"}),
                "multi_currency_support": hx.Bool(mode="input", default=False, optionality="required", view={"label": "Multi Currency Support"}),
                "rates": hx.List(mode="input", view={"label": "Rates"}, children={
                    "code": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Code"}),
                    "rate": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Rate", "format": {"thousandSeparated": False, "mantissa": 2}}),
                }),
            }),
            "experience_rating": hx.Structure(view={"label": "Experience Rating"}, children={
                "claims_available": hx.Bool(mode="input", default=False, view={"label": "Loss Data Avaialble"}),
                "claims_fgu": hx.Bool(mode="input", default=False, view={"label": "Claims From Ground Up"}),
                "claims_net_of_deductible": hx.Bool(mode="input", default=False, view={"label": "Are Claims net of Deductible"}),
            }),
            "database_id": hx.Int(mode="output", view={"label": "Database ID", "format": {"thousandSeparated": False, "mantissa": 0}}),
            "broker_contact": hx.Str(mode="input", default="", view={"label": "Broker Contact"}),
            "firms_list": hx.Structure(children={
                "firms": hx.List(mode="output", children={
                    "firm_name": hx.Str(mode="output"),
                }),
            }),
            "rate_change": hx.Structure(children={
                "show_layer_1": hx.Bool(mode="output"),
                "show_layer_2": hx.Bool(mode="output"),
                "show_layer_3": hx.Bool(mode="output"),
                "show_layer_4": hx.Bool(mode="output"),
                "show_layer_5": hx.Bool(mode="output"),
                "show_layer_6": hx.Bool(mode="output"),
                "show_layer_7": hx.Bool(mode="output"),
                "show_layer_8": hx.Bool(mode="output"),
                "show_layer_9": hx.Bool(mode="output"),
                "show_layer_10": hx.Bool(mode="output"),
                "expiring_policy_option_id": hx.Int(mode="override", async_input=["expiring_policy_fetch_task", "rarc_task"], view={"label": "Expiring Policy Option", "format": {"thousandSeparated": False}}),
                "has_fetch_not_run": hx.Bool(mode="input", default=True, async_output=["expiring_policy_fetch_task", "rarc_task"]),
                "has_fetch_run": hx.Bool(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task"]),
                "has_rarc_not_run": hx.Bool(mode="input", default=True, async_output=["rarc_task"]),
                "has_rarc_run": hx.Bool(mode="output", async_output=["rarc_task"]),
                "rarc_run_again_message": hx.Str(mode="output"),
                "rarc_message_show": hx.Bool(mode="output"),
                "layer_mapping": hx.Str(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task"]),
            }),
            "account_details": hx.Structure(children={
                "product_type": hx.Str(mode="input", default=None, async_input=["rarc_task"], optionality="optional", options=["Manutech", "Med Mal", "MPL", "Products", "Staffing", "Tech"], view={"label": "Product Type"}),
                "retroactive_years": hx.Structure(children={
                    "retroactive_years_list": hx.List(mode="output", children={
                        "years": hx.Str(mode="output"),
                    }),
                    "years": hx.Str(mode="input", default=None, async_input=["rarc_task"], optionality="optional", options_data="../retroactive_years_list", options_field="years", view={"label": "Retroactive Years"}),
                }),
            }),
            "tooltips": hx.Structure(children={
                "occupation": hx.Str(mode="input", default="Enter the occupation code which best describes the insured"),
                "sub_occupation": hx.Str(mode="input", default="Enter the sub occupation code which best describes the insured"),
                "state": hx.Str(mode="input", default="State or region of the US"),
                "loss_experience": hx.Str(mode="input", default="History of Claims"),
                "underwriter_judgement": hx.Str(mode="input", default="Enter any risk based adjustments here"),
                "underwriter_judgement_justification": hx.Str(mode="input", default="If you have entered anything other than 0 for UW Judgement then please justify it here"),
                "longevity": hx.Str(mode="input", default="Length of time the insured has been in business"),
                "professional_experience": hx.Str(mode="input", default="Average professional experience of the insured's staff"),
                "business_with_written_contract_percentage": hx.Str(mode="input", default="Enter the percentage of business with written contracts"),
                "business_with_written_contract_revenue": hx.Str(mode="input", default="What level of revenue do the insured's clients have"),
            }),
            "rating_factors": hx.Structure(children={
                "show_loss_experience_empty_panel": hx.Bool(mode="output"),
                "show_revenue_type": hx.Bool(mode="output"),
                "loss_experience": hx.Str(mode="input", default=None, async_input=["rarc_task"], optionality="optional", options=["2 or more Claims under 3 years", "No Claims in 3-5 years", "1 Claim under 3 years", "1 Claim 3-5 years", "2 or more Claims 3-5 years", "No Claims in 6-10 years", "No Claims under 3 years", "No Claims in 10+ years"], view={"label": "Loss Experience"}),
                "underwriter_judgement": hx.Float(mode="input", default=None, optionality="optional", view={"label": "UW Judgement (Risk Based)", "format": {"output": "percent", "mantissa": 0}}),
                "underwriter_judgement_justification": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Underwriter Comment"}),
                "longevity": hx.Structure(children={
                    "show": hx.Bool(mode="output"),
                    "years_list": hx.List(mode="output", children={
                        "years": hx.Str(mode="output"),
                    }),
                    "years": hx.Str(mode="input", default=None, async_input=["rarc_task"], optionality="optional", options_data="../years_list", options_field="years", view={"label": "Longevity Factor"}),
                    "factor": hx.Float(mode="output", view={"label": "Credit/Debit", "format": {"output": "percent", "mantissa": 0}}),
                    "med_mal_longevity_label": hx.Str(mode="input", default="Age of business up to"),
                }),
                "professional_experience": hx.Structure(children={
                    "show": hx.Bool(mode="output"),
                    "years_list": hx.List(mode="output", children={
                        "years": hx.Str(mode="output"),
                    }),
                    "years": hx.Str(mode="input", default=None, async_input=["rarc_task"], optionality="optional", options_data="../years_list", options_field="years", view={"label": "Professional Experience"}),
                    "factor": hx.Float(mode="output", view={"label": "Credit/Debit", "format": {"output": "percent", "mantissa": 0}}),
                    "med_mal_professional_experience_label": hx.Str(mode="input", default="Professional Experience up to"),
                }),
                "business_with_written_contract": hx.Structure(children={
                    "show": hx.Bool(mode="output"),
                    "percentage": hx.Float(mode="input", default=None, async_input=["rarc_task"], optionality="optional", view={"label": "Business with Written Contract", "format": {"output": "percent", "mantissa": 0}}),
                    "revenue": hx.Str(mode="input", default=None, async_input=["rarc_task"], optionality="optional", options=["$50M - $500M", "Over $500M", "Less than $50 M", "Individual"], view={"label": "Revenue of Insured's Clients"}),
                }),
                "tiers_list": hx.List(mode="output", children={
                    "tier": hx.Int(mode="output"),
                    "business_description": hx.Str(mode="output"),
                }),
                "types_list": hx.List(mode="output", children={
                    "type": hx.Str(mode="output"),
                }),
                "revenues": hx.List(mode="input", default_element_count=3, children={
                    "hazard_tier": hx.Structure(linked_options_data="../../../tiers_list", linked_options_fields=["tier", "business_description"], children={
                        "tier": hx.Int(mode="input", default=None, async_input=["rarc_task"], optionality="optional", view={"label": "Tier"}),
                        "business_description": hx.Str(mode="input", default=None, async_input=["rarc_task"], optionality="optional", view={"label": "Business Description"}),
                    }),
                    "value": hx.Int(mode="input", default=None, async_input=["rarc_task"], optionality="optional", view={"label": "Value", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "factor": hx.Float(mode="output"),
                    "type": hx.Str(mode="input", default=None, async_input=["rarc_task"], optionality="optional", options_data="../../../types_list", options_field="type", view={"label": "Type"}),
                }),
                "med_mal": hx.Structure(children={
                    "show": hx.Bool(mode="output"),
                    "hide": hx.Bool(mode="output"),
                    "allied_medical": hx.Structure(children={
                        "allied_medical_type": hx.Str(mode="input", default=None, async_input=["rarc_task"], optionality="optional", options_column="allied_medical", options_table="table_allied_medical", view={"label": "Allied Medical Type"}),
                        "exposure_type": hx.Str(mode="output", optionality="optional", view={"label": "Exposure Type"}),
                        "exposure_measure": hx.Float(mode="input", default=None, async_input=["rarc_task"], optionality="optional", view={"label": "Exposure Measure"}),
                        "exposure_factor": hx.Float(mode="output", optionality="optional", view={"label": "Exposure Factor"}),
                    }),
                    "social_services": hx.Structure(children={
                        "social_services_type": hx.Str(mode="input", default=None, async_input=["rarc_task"], optionality="optional", options_column="social_services", options_table="table_input_social_services", view={"label": "Social Services Type"}),
                        "exposure_type": hx.Str(mode="output", optionality="optional", view={"label": "Exposure Type"}),
                        "exposure_measure": hx.Float(mode="input", default=None, async_input=["rarc_task"], optionality="optional", view={"label": "Exposure Measure"}),
                        "exposure_factor": hx.Float(mode="output", optionality="optional", view={"label": "Exposure Factor"}),
                    }),
                    "endorsements": hx.List(mode="input", default_element_count=6, children={
                        "endorsement": hx.Str(mode="input", default=None, optionality="optional", options_column="endorsement", options_table="table_input_endorsements", view={"label": "Endorsement"}),
                        "factor": hx.Float(mode="output", optionality="optional", view={"label": "Exposure Factor", "format": {"output": "percent", "mantissa": 0}}),
                    }),
                }),
                "staffing": hx.Structure(children={
                    "show": hx.Bool(mode="output"),
                    "permanent": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Permanent Staffing", "format": {"output": "percent", "mantissa": 0}}),
                    "peo": hx.Float(mode="input", default=None, optionality="optional", view={"label": "PEO's", "format": {"output": "percent", "mantissa": 0}}),
                    "temporary": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Temporary Staffing", "format": {"output": "percent", "mantissa": 0}}),
                }),
                "tech": hx.Structure(children={
                    "show": hx.Bool(mode="output"),
                    "media_and_advertising": hx.Bool(mode="input", default=False, async_input=["rarc_task"], optionality="required", view={"label": "Media & Advertising"}),
                    "cont_bi_pd": hx.Bool(mode="input", default=False, async_input=["rarc_task"], optionality="required", view={"label": "Cont BI/PD"}),
                    "first_party_privacy": hx.Bool(mode="input", default=False, async_input=["rarc_task"], optionality="required", view={"label": "First Party Privacy"}),
                    "cyber_extortion_only": hx.Bool(mode="input", default=False, async_input=["rarc_task"], optionality="required", view={"label": "Cyber Extortion Only"}),
                }),
                "general_liability": hx.Structure(children={
                    "show": hx.Bool(mode="output"),
                    "value": hx.Bool(mode="input", default=False, async_input=["rarc_task"], optionality="required", view={"label": "General Liability"}),
                    "show_staffing": hx.Bool(mode="output"),
                }),
                "show_staffing_liability_limits_AGG": hx.Bool(mode="output"),
                "show_product_liability_limits_AGG": hx.Bool(mode="output"),
                "staffing_liability_limits_AGG_label": hx.Str(mode="input", default="Staffing Liability Limits AGG"),
                "general_liability_limits_AGG_products_label": hx.Str(mode="input", default="General Liability Limits AGG"),
            }),
            "rationale": hx.Structure(children={
                "knowledge_of_insured": hx.Str(mode="input", default=None, optionality="optional"),
                "portfolio_fit": hx.Str(mode="input", default=None, optionality="optional"),
                "basis_of_risk_selection": hx.Str(mode="input", default=None, optionality="optional"),
                "unusual_or_complex_operations": hx.Str(mode="input", default=None, optionality="optional"),
                "facts_affecting_decision": hx.Str(mode="input", default=None, optionality="optional"),
            }),
        }),
        "model_state": hx.Structure(children={
            "pressed_start_renewal_task": hx.Bool(mode="output", async_output=["start_renewal_task"]),
            "show_landing_page": hx.Bool(mode="output"),
            "show_after_landing_page": hx.Bool(mode="output"),
            "show_rate_change": hx.Bool(mode="output"),
            "landing_page_info": hx.Str(mode="input", default="Click 'Import Expiring Policy Data' in the top right corner then click 'Start Policy'", async_output=["start_renewal_task"], view={"read_only": True}),
        }),
    })
