import pandas as pd
import json

def infer_data_type(dtype):
    """ Helper function to convert dtype to str, int, or float """
    if pd.api.types.is_integer_dtype(dtype):
        return 'int'
    elif pd.api.types.is_float_dtype(dtype):
        return 'float'
    else:
        return 'str'

# Load the Excel file
excel_file = '/workspace/editing/parameter_tables/YOUR_FILE.xlsx' # NOTE: replace 'YOUR_FILE' with the name of your Excel file saved in the parameter_tables folder

# Load the Excel file into a Pandas ExcelFile object
xl = pd.ExcelFile(excel_file)

# Dictionary to hold all schemas
all_schemas = {}

# Loop through all the sheets in the Excel file
for sheet_name in xl.sheet_names:
    # Load the sheet into a Pandas DataFrame
    df = xl.parse(sheet_name)
    
    # Save the DataFrame to CSV, name each file after the sheet
    csv_path = f'/workspace/editing/parameter_tables/{sheet_name}.csv'
    df.to_csv(csv_path, index=False)

    # Generate schema for the current sheet
    schema = {}
    for column in df.columns:
        schema[column] = infer_data_type(df[column].dtype)

    # Add the schema to the overall dictionary
    all_schemas[sheet_name] = schema

# Convert the entire dictionary to JSON and save it
json_schema = json.dumps(all_schemas, indent=4)
with open('/workspace/editing/parameter_tables/parameter_table_schema_autogenerated.json', 'w') as json_file:
    json_file.write(json_schema)

print("All sheets have been saved as CSV files and their schemas stored in 'parameter_table_schema_autogenerated.json'.")
