from libraries.common_data_schema.data_schema.dev_tools.generate_data_schema import GenerateDataSchema

# To perform an automatic data schema generation, simply run the code below (click on the Play button in the top right corner)
gds = GenerateDataSchema(
    file_name="RiskInfo_Mapping_File.csv", # NOTE: change to your mapping file
    coverages={
        "all": {"label": "All"}
        #"cargo_transit": {"label": "Cargo"},
        #"cargo_storage": {"label": "Cargo"},
        #"specie_transit": {"label": "Specie"},
        #"specie_storage": {"label": "Specie"},
        #"conloss_transit": {"label": "Con Loss"},
        #"conloss": {"label": "Con Loss"}
        },
    # NOTE: change to your coverages with the format {"coverage_name": {"label": "Coverage Label"}}
    # col_rd_flag = "Your Column Name"
    # rd_valid_values = "Your 'True' Value(s)"
    # col_name = "Your Column Name",
    # ... NOTE: define the additional parameters if your mapping file has different column names
    )

# This will create (or overwrite) a sch_autogenerated.py file in the data_schema folder
gds.generate_schema_code()


##### --- NOTES ON FIELD VALIDATION --- #####
# Validations are performed on the .csv mapping document to ensure data integrity and correct format. See below for more details.

# 1. Validation of the name column to ensure each entry starts with a letter and may contain numbers or underscores but no spaces. 
# Example of a valid entry: 'product_name'. Example of an invalid entry: 'product name' (contains a space).

# 2. Validation of the mode column to ensure each entry is either 'input', 'output', or 'override'.
# Example of a valid entry: 'input'. Example of an invalid entry: 'editable' (not a recognised mode).

# 3. Validation of the cds_level column to ensure each entry is exactly 'cds' or starts with 'cds/' followed by additional specific path information. 
# This confirms the data's position within the CDS hierarchy. Example of a valid entry: 'cds/layers/coverages'. Example of an invalid entry: 'test/path' (does not start with 'cds' or 'cds/').

# 4. Validation of the cds_path column to ensure each entry starts with a forward slash followed by at least one letter, indicating a valid path within the CDS structure.
# This is meant to represent the relative path of a node within the pre-defined CDS levels. It is therefore complementary to the the cds_level column.
# Example of a valid entry: '/cargo/transit_flag'. Example of an invalid entry: 'cargo/transit_flag' (missing leading forward slash).

# 5. Validation of the node_type column to ensure each entry is one of 'str', 'float', 'bool', 'int', or 'date', indicating the type of data expected in the field.
# Example of a valid entry: 'float'. Example of an invalid entry: 'number' (not one of the recognised types).