raise Exception("""This file is generated

Do not edit manually as all of the changes will be lost.
This is the static version of your Data Schema that will allow easier debugging.
""")

import hx_data_schema as hx


@hx.data_schema
def hx_calculation_legacy_initial_premium():
    return hx.Structure(children={
        "hx_core": hx.Structure(children={
            "inception_date": hx.Date(default="2018-01-01", mode="input", view={"label": "Inception Date"}),
            "expiry_date": hx.Date(default="2018-12-31", mode="input", view={"label": "Expiry Date"}),
            "model_premium": hx.Float(mode="output", view={"label": "Model Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
            "charged_premium": hx.Float(mode="output", view={"label": "Charged Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
            "premium_currency": hx.Str(mode="output", view={"label": "Premium Currency"}),
            "ulr": hx.Float(mode="output", view={"label": "ULR", "format": {"output": "percent", "mantissa": 1}}),
            "class_code": hx.Str(mode="output", view={"label": "Class Code"}),
        }, view={"label": "Hx Core"}),
        "cds": hx.Structure(view={"label": "cds"}, children={
            "key_industry": hx.Structure(view={"label": "Key Industry"}, children={
                "code_type": hx.Str(mode="input", default=None, optionality="optional", options=["NAICS", "SIC_USA", "SIC_UK", "UW Defined"], view={"label": "Industry Code Type"}),
                "code": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Industry Code"}),
                "code_name": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Industry Code Name"}),
            }),
            "exposure": hx.Structure(view={"label": "Exposure"}, children={
                "aggregate": hx.Structure(view={"label": "Aggregate"}, children={
                    "total_schools": hx.Float(mode="output", view={"label": "Total Schools"}),
                    "total_non_ed_est": hx.Float(mode="output", view={"label": "Total Establishments (Non-Ed)"}),
                }),
                "granular": hx.Structure(view={"label": "Granular"}, children={
                    "education": hx.List(mode="input", async_input=["rarc_task"], children={
                        "institution_name": hx.Str(mode="input", default=None, async_input=["rarc_task"], optionality="optional", view={"label": "Name of\nInstitution"}),
                        "num_schools": hx.Int(mode="input", default=None, async_input=["rarc_task"], optionality="optional", validation={"min_value": 0}, view={"label": "Number of\nSchools"}),
                        "country": hx.Str(mode="input", default=None, async_input=["rarc_task"], optionality="optional", options_column="Country", options_table="country_rates", view={"label": "Country"}),
                        "state_code": hx.Str(mode="input", default=None, async_input=["rarc_task"], optionality="optional", options_column="State Code", options_table="lst_state_lookup", view={"label": "State Code"}),
                        "state_name": hx.Str(mode="output", async_input=["rarc_task"], optionality="optional", view={"label": "State Name"}),
                        "city_risk": hx.Str(mode="input", default=None, async_input=["rarc_task"], optionality="optional", options_column="City Risk", options_table="city_risk_factor", view={"label": "City Risk"}),
                        "location": hx.Str(mode="input", default=None, async_input=["rarc_task"], optionality="optional", options_column="Field", options_table="location_factor", view={"label": "Location"}),
                        "school_grade": hx.Str(mode="input", default=None, async_input=["rarc_task"], optionality="optional", options_column="Field", options_table="school_grade_factor", view={"label": "School Grade"}),
                        "school_type": hx.Str(mode="input", default=None, async_input=["rarc_task"], optionality="optional", options_column="Field", options_table="school_type_factor", view={"label": "School Type"}),
                        "boarding_day": hx.Str(mode="input", default_index=0, async_input=["rarc_task"], optionality="optional", options_column="Field", options_table="boarding_day_factor", view={"label": "Boarding /\nDay"}),
                        "num_students": hx.Int(mode="input", default=None, async_input=["rarc_task"], optionality="optional", validation={"min_value": 0}, view={"label": "# Students"}),
                        "num_employees": hx.Int(mode="input", default=None, async_input=["rarc_task"], optionality="optional", view={"label": "# Employees"}),
                        "sex_of_school": hx.Str(mode="input", default_index=0, async_input=["rarc_task"], optionality="optional", options_column="Field", options_table="school_sex_factor", view={"label": "Sex of School"}),
                        "num_req_counselling": hx.Float(mode="output", async_input=["rarc_task"], optionality="optional", view={"label": "# Req'g\nCounselling", "format": {"thousandSeparated": False, "mantissa": 0}}),
                        "factor_city_risk": hx.Float(mode="output", async_input=["rarc_task"], optionality="optional", view={"label": "City Risk\nFactor"}),
                        "rate_multiplier": hx.Float(mode="output", async_input=["rarc_task"], optionality="optional"),
                    }),
                    "non_education": hx.List(mode="input", async_input=["rarc_task"], children={
                        "establishment_name": hx.Str(mode="input", default=None, async_input=["rarc_task"], optionality="optional", view={"label": "Name of Est."}),
                        "sector": hx.Structure(linked_options_columns=["Sector", "SubSector"], linked_options_table="sector_subsector_rates", view={"linked_options_selector": "hierarchical"}, children={
                            "sector": hx.Str(mode="input", default=None, async_input=["rarc_task"], optionality="optional", view={"label": "Sector"}),
                            "sub_sector": hx.Str(mode="input", default=None, async_input=["rarc_task"], optionality="optional", view={"label": "Sub-Sector"}),
                        }),
                        "num_of_est": hx.Int(mode="input", default=None, async_input=["rarc_task"], optionality="optional", validation={"min_value": 0}, view={"label": "Number of Est."}),
                        "country": hx.Str(mode="input", default=None, async_input=["rarc_task"], optionality="optional", options_column="Country", options_table="country_rates", view={"label": "Country"}),
                        "state_code": hx.Str(mode="input", default=None, async_input=["rarc_task"], optionality="optional", options_column="State Code", options_table="lst_state_lookup", view={"label": "State Code"}),
                        "state_name": hx.Str(mode="output", async_input=["rarc_task"], optionality="optional", view={"label": "State Name"}),
                        "city_risk": hx.Str(mode="input", default=None, async_input=["rarc_task"], optionality="optional", options_column="City Risk", options_table="city_risk_factor", view={"label": "City Risk"}),
                        "location": hx.Str(mode="input", default=None, async_input=["rarc_task"], optionality="optional", options_column="Field", options_table="location_factor", view={"label": "Location"}),
                        "footfall_measure": hx.Str(mode="output", async_input=["rarc_task"], view={"label": "Footfall\nMeasure"}),
                        "num_of_staff_per_est": hx.Int(mode="input", default=None, async_input=["rarc_task"], optionality="optional", validation={"min_value": 0}, view={"label": "Number of\nStaff Per Est."}),
                        "footfall_measure_per_est": hx.Float(mode="input", default=None, async_input=["rarc_task"], optionality="optional", view={"label": "Footfall\nMeasure per\nEst. (NOT Staff)", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "east_of_access": hx.Str(mode="input", default=None, async_input=["rarc_task"], optionality="optional", options_column="Ease of Access", options_table="ease_of_access", view={"label": "Ease of\naccess"}),
                        "enclosed_space": hx.Str(mode="input", default=None, async_input=["rarc_task"], optionality="optional", options_column="Enclosed Space", options_table="enclosed_space_factor", view={"label": "Enclosed\nspace"}),
                        "num_of_days": hx.Int(mode="input", default=None, async_input=["rarc_task"], optionality="optional", validation={"min_value": 0}, view={"label": "Number of\ndays (events\nonly)"}),
                        "num_req_counselling": hx.Float(mode="output", async_input=["rarc_task"], optionality="optional", view={"label": "# Req'g Counselling\nPer Event\n(Observers)", "format": {"thousandSeparated": False, "mantissa": 0}}),
                        "footfall_band": hx.Str(mode="output", async_input=["rarc_task"], optionality="optional", view={"label": "Footfall\nBand"}),
                        "factor_city_risk": hx.Float(mode="output", async_input=["rarc_task"], optionality="optional", view={"label": "City Risk\nFactor"}),
                        "rate_multiplier": hx.Float(mode="output", async_input=["rarc_task"], optionality="optional"),
                    }),
                }),
            }),
            "standard_fields": hx.Structure(view={"label": "Standard Fields"}, children={
                "insured_name": hx.Str(mode="input", default=None, allow_custom_value=True, async_input=["start_renewal_task"], optionality="optional", options_column="insured_name", options_table="lst_insured_names", view={"label": "Insured Name"}),
                "broker": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Broker Name"}),
                "expiry_date": hx.Date(mode="output", view={"label": "Expiry Date"}),
                "inception_date": hx.Date(mode="output", view={"label": "Inception Date"}),
                "insured_country": hx.Str(mode="input", default=None, optionality="optional", options=["", "AND", "ARE", "AFG", "ATG", "AIA", "ALB", "ARM", "AGO", "ATA", "ARG", "ASM", "AUT", "AUS", "ABW", "ALA", "AZE", "BIH", "BRB", "BGD", "BEL", "BFA", "BGR", "BHR", "BDI", "BEN", "BLM", "BMU", "BRN", "BOL", "BES", "BRA", "BHS", "BTN", "BVT", "BWA", "BLR", "BLZ", "CAN", "CCK", "COD", "CAF", "COG", "CHE", "CIV", "COK", "CHL", "CMR", "CHN", "COL", "CRI", "CUB", "CPV", "CUW", "CXR", "CYP", "CZE", "DEU", "DJI", "DNK", "DMA", "DOM", "DZA", "ECU", "EST", "EGY", "ESH", "ERI", "ESP", "ETH", "FIN", "FJI", "FLK", "FSM", "FRO", "FRA", "GAB", "GBR", "GRD", "GEO", "GUF", "GGY", "GHA", "GIB", "GRL", "GMB", "GIN", "GLP", "GNQ", "GRC", "SGS", "GTM", "GUM", "GNB", "GUY", "HKG", "HMD", "HND", "HRV", "HTI", "HUN", "IDN", "IRL", "ISR", "IMN", "IND", "IOT", "IRQ", "IRN", "ISL", "ITA", "JEY", "JAM", "JOR", "JPN", "KEN", "KGZ", "KHM", "KIR", "COM", "KNA", "PRK", "KOR", "KWT", "CYM", "KAZ", "LAO", "LBN", "LCA", "LIE", "LKA", "LBR", "LSO", "LTU", "LUX", "LVA", "LBY", "MAR", "MCO", "MDA", "MNE", "MAF", "MDG", "MHL", "MKD", "MLI", "MMR", "MNG", "MAC", "MNP", "MTQ", "MRT", "MSR", "MLT", "MUS", "MDV", "MWI", "MEX", "MYS", "MOZ", "NAM", "NCL", "NER", "NFK", "NGA", "NIC", "NLD", "NOR", "NPL", "NRU", "NIU", "NZL", "OMN", "PAN", "PER", "PYF", "PNG", "PHL", "PAK", "POL", "SPM", "PCN", "PRI", "PSE", "PRT", "PLW", "PRY", "QAT", "REU", "ROU", "SRB", "RUS", "RWA", "SAU", "SLB", "SYC", "SDN", "SWE", "SGP", "SHN", "SVN", "SJM", "SVK", "SLE", "SMR", "SEN", "SOM", "SUR", "SSD", "STP", "SLV", "SXM", "SYR", "SWZ", "TCA", "TCD", "ATF", "TGO", "THA", "TJK", "TKL", "TLS", "TKM", "TUN", "TON", "TUR", "TTO", "TUV", "TWN", "TZA", "UKR", "UGA", "UMI", "USA", "URY", "UZB", "VAT", "VCT", "VEN", "VGB", "VIR", "VNM", "VUT", "WLF", "WSM", "YEM", "MYT", "ZAF", "ZMB", "ZWE", "ATB", "BYS", "CTE", "CSK", "DHY", "ATN", "AFI", "ATF", "DDR", "GEL", "JTN", "MID", "NHB", "PCI", "PCZ", "SKM", "RHO", "PUS", "HVO", "VDR", "WAK", "YMD"], view={"label": "Insured Country"}),
                "insured_postal_code": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Insured Postal Code"}),
                "insured_state_or_province": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Insured State or Province"}),
                "is_admitted_or_surplus": hx.Str(mode="input", default=None, optionality="optional", options=["Admitted", "Surplus"], view={"label": "Is Admitted Or Surplus"}),
                "is_free_trade_zone": hx.Bool(mode="input", default=False, optionality="required", view={"label": "Is Free-Trade Zone"}),
                "is_renewal": hx.Bool(mode="input", default=False, async_output=[{"task": "start_renewal_task", "reset": False}], optionality="required", view={"label": "Is Renewal"}),
                "underwriter": hx.Str(mode="input", default=None, allow_custom_value=True, optionality="optional", options_column="Underwriters", options_table="lst_underwriters", view={"label": "Underwriter"}),
                "policy_reference": hx.Str(mode="input", default=None, async_input=["sql_bi_fetch_task"], optionality="optional", view={"label": "Policy Reference"}),
                "facility_reference": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Facility Reference"}),
                "benchmark_class": hx.Str(mode="output", optionality="optional", view={"label": "Benchmark Class"}),
                "uw_rationale": hx.Str(mode="output", optionality="optional", view={"label": "Underwriter Rationale"}),
                "trifocus": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Trifocus"}),
                "rating_methodology": hx.Str(mode="input", default="Rater", options=["Rater", "Case Priced"], view={"label": "Rater Priced or Case Priced?"}),
                "is_case_priced": hx.Bool(mode="output", view={"label": "Is Case Priced"}),
                "is_rater_priced": hx.Bool(mode="output", view={"label": "Is Rater Priced"}),
            }),
            "layers": hx.List(mode="input", async_input=["rarc_task"], default_element_count=6, max_element_count=6, min_element_count=6, view={"label": "Layers"}, children={
                "limit": hx.Float(mode="input", default=1000000.0, async_input=["rarc_task"], optionality="optional", validation={"min_value": 0}, view={"label": "Limit", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "excess": hx.Float(mode="input", default=None, async_input=["rarc_task"], optionality="optional", validation={"min_value": 0}, view={"label": "Excess", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "deductible": hx.Float(mode="input", default=10000.0, async_input=["rarc_task"], optionality="optional", validation={"min_value": 0}, view={"label": "Deductible", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "aggregate_limit": hx.Float(mode="input", default=1000000.0, async_input=["rarc_task"], optionality="optional", options_data="../agg_limits_list", options_field="values", view={"label": "Agg Limit", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "aggregate_excess": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Aggregate Excess", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "aggregate_deductible": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Aggregate Deductible", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "currency": hx.Str(mode="input", default=None, optionality="optional", options=["ADP", "AFA", "AON", "AOR", "ATS", "AZM", "BEF", "BGL", "BRE", "BUK", "BYB", "BYR", "CSD", "CSK", "CYP", "DDM", "DEM", "ECS", "EEK", "ESP", "FIM", "FRF", "GHC", "GRD", "GWP", "HRK", "IEP", "ITL", "LTL", "LUF", "LVL", "MGF", "MRO", "MTL", "MXP", "MZM", "NIC", "NLG", "PES", "PLZ", "PTE", "ROL", "RUR", "SDD", "SDP", "SIT", "SKK", "SRG", "STD", "SUR", "TRL", "UYP", "VEB", "VEF", "XEU", "YUM", "ZMK", "ZRN", "ZRZ", "ZWD", "ZWR", "AED", "AFN", "ALL", "AMD", "ANG", "AOA", "ARS", "AUD", "AWG", "AZN", "BAM", "BBD", "BDT", "BGN", "BHD", "BIF", "BMD", "BND", "BOB", "BOV", "BRL", "BSD", "BTN", "BWP", "BYN", "BZD", "CAD", "CDF", "CHE", "CHF", "CHW", "CLF", "CLP", "CNY", "COP", "COU", "CRC", "CUC", "CUP", "CVE", "CZK", "DJF", "DKK", "DOP", "DZD", "EGP", "ERN", "ETB", "EUR", "FJD", "FKP", "GBP", "GEL", "GHS", "GIP", "GMD", "GNF", "GTQ", "GYD", "HKD", "HNL", "HTG", "HUF", "IDR", "ILS", "INR", "IQD", "IRR", "ISK", "JMD", "JOD", "JPY", "KES", "KGS", "KHR", "KMF", "KPW", "KRW", "KWD", "KYD", "KZT", "LAK", "LBP", "LKR", "LRD", "LSL", "LYD", "MAD", "MDL", "MGA", "MKD", "MMK", "MNT", "MOP", "MRU", "MUR", "MVR", "MWK", "MXN", "MXV", "MYR", "MZN", "NAD", "NGN", "NIO", "NOK", "NPR", "NZD", "OMR", "PAB", "PEN", "PGK", "PHP", "PKR", "PLN", "PYG", "QAR", "RON", "RSD", "RUB", "RWF", "SAR", "SBD", "SCR", "SDG", "SEK", "SGD", "SHP", "SLE", "SLL", "SOS", "SRD", "SSP", "STN", "SVC", "SYP", "SZL", "THB", "TJS", "TMT", "TND", "TOP", "TRY", "TTD", "TWD", "TZS", "UAH", "UGX", "USD", "USN", "UYI", "UYU", "UYW", "UZS", "VED", "VES", "VND", "VUV", "WST", "XAF", "XAG", "XAU", "XBA", "XBB", "XBC", "XBD", "XCD", "XDR", "XOF", "XPD", "XPF", "XPT", "XSU", "XTS", "XUA", "XXX", "YER", "ZAR", "ZMW", "ZWL"], view={"label": "Currency"}),
                "section_reference": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Section Reference"}),
                "brokerage": hx.Float(mode="input", default=0.2, async_input=["rarc_task"], optionality="required", validation={"min_value": 0, "max_value": 1}, view={"label": "Brokerage", "format": {"output": "percent", "mantissa": 1}}),
                "written_line": hx.Float(mode="input", default=1, optionality="optional", validation={"min_value": 0, "max_value": 1}, view={"label": "Written Line", "format": {"output": "percent", "mantissa": 1}}),
                "premium": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Gross Bound Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "status": hx.Str(mode="input", default="Rating", optionality="optional", options=["Assessment Pending", "Rating", "Quoted", "Bound", "Post Bind Complete", "Declined", "Not Taken Up"], view={"label": "Status", "options": {"input": {"label": "Status"}, "read_only": {"label": "Deal Status by Renewal Layers", "read_only": True}}}),
                "is_primary_excess": hx.Str(mode="input", default=None, optionality="optional", options=["Primary", "Excess"], view={"label": "Primary or Excess"}),
                "benchmark_premium": hx.Float(mode="output", async_input=["rarc_task"], optionality="optional", view={"label": "Benchmark Premium After UW Adj", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "bpi": hx.Float(mode="output", optionality="optional", view={"label": "BPI", "format": {"output": "percent", "mantissa": 1}}),
                "bpi_pre_uw_adj": hx.Float(mode="output", optionality="optional", view={"label": "BPI (Pre-UW Adjustment)", "format": {"output": "percent", "mantissa": 1}}),
                "model_premium": hx.Float(mode="output", optionality="optional", view={"label": "Gross Model Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "unity_premium": hx.Float(mode="output", optionality="optional", view={"label": "Gross Unity Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "quoted_premium": hx.Float(mode="input", default=None, async_input=["rarc_task"], optionality="optional", view={"label": "Gross Quoted Premium", "format": {"thousandSeparated": True, "mantissa": 0}, "options": {"input": {"label": "EPI 100% Line Size"}, "read_only": {"label": "EPI", "read_only": True}}}),
                "technical_premium": hx.Float(mode="output", optionality="optional", view={"label": "Gross Technical Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "technical_premium_pre_uw_adj": hx.Float(mode="output", optionality="optional", view={"label": "Technical Premium Before UW Adj", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "technical_premium_net": hx.Float(mode="output", optionality="optional", view={"label": "Net Technical Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "tpi": hx.Float(mode="output", optionality="optional", view={"label": "TPI", "format": {"output": "percent", "mantissa": 1}}),
                "tpi_pre_uw_adj": hx.Float(mode="output", optionality="optional", view={"label": "TPI (Pre-UW Adjustment)", "format": {"output": "percent", "mantissa": 1}}),
                "pflr_att": hx.Float(mode="output", optionality="optional", view={"label": "Priced-for Loss Ratio (Att)", "format": {"output": "percent", "mantissa": 1}}),
                "pflr_cat": hx.Float(mode="output", optionality="optional", view={"label": "Priced-for Loss Ratio (Cat)", "format": {"output": "percent", "mantissa": 1}}),
                "pflr": hx.Float(mode="output", optionality="optional", view={"label": "Priced-for Loss Ratio", "format": {"output": "percent", "mantissa": 1}}),
                "roc": hx.Float(mode="output", optionality="optional", view={"label": "Return on Capital", "format": {"output": "percent", "mantissa": 1}}),
                "uw_adj_impact": hx.Float(mode="output", optionality="optional", view={"label": "Impact of Underwriting Adjustments", "format": {"output": "percent", "mantissa": 1}}),
                "trifocus": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Trifocus"}),
                "expected_loss_cost": hx.Float(mode="output", optionality="optional", view={"label": "Final Expected Loss", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "expected_loss_cost_pre_uw_adj": hx.Float(mode="output", optionality="optional", view={"label": "Expected Loss Cost (Pre-UW Ajustment)", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "rate_change": hx.Structure(view={"label": "Rate Change"}, children={
                    "exposure_change": hx.Structure(view={"label": "Exposure Change"}, children={
                        "model_calculated": hx.Float(mode="output", async_output=["rarc_task"], view={"label": "Model %", "format": {"output": "percent", "mantissa": 0}}),
                        "uw_selected": hx.Float(mode="override", async_output=["rarc_task", "start_renewal_task"], view={"label": "UW Selected %", "format": {"output": "percent", "mantissa": 0}}),
                        "comments": hx.Str(mode="input", default=None, async_output=["start_renewal_task"], optionality="optional", view={"label": "Comment"}),
                    }),
                    "risk_characteristics_change": hx.Structure(view={"label": "Risk Characteristics Change"}, children={
                        "model_calculated": hx.Float(mode="output", async_output=["rarc_task"], view={"label": "Model %", "format": {"output": "percent", "mantissa": 0}}),
                        "uw_selected": hx.Float(mode="override", async_output=["rarc_task", "start_renewal_task"], view={"label": "UW Selected %", "format": {"output": "percent", "mantissa": 0}}),
                        "comments": hx.Str(mode="input", default=None, async_output=["start_renewal_task"], optionality="optional", view={"label": "Comment"}),
                    }),
                    "limit_change": hx.Structure(view={"label": "Limit Change"}, children={
                        "model_calculated": hx.Float(mode="output", async_output=["rarc_task"], view={"label": "Model %", "format": {"output": "percent", "mantissa": 0}}),
                        "uw_selected": hx.Float(mode="override", async_output=["rarc_task", "start_renewal_task"], view={"label": "UW Selected %", "format": {"output": "percent", "mantissa": 0}}),
                        "comments": hx.Str(mode="input", default=None, async_output=["start_renewal_task"], optionality="optional", view={"label": "Comment"}),
                    }),
                    "deductible_change": hx.Structure(view={"label": "Deductible Change"}, children={
                        "model_calculated": hx.Float(mode="output", async_output=["rarc_task"], view={"label": "Model %", "format": {"output": "percent", "mantissa": 0}}),
                        "uw_selected": hx.Float(mode="override", async_output=["rarc_task", "start_renewal_task"], view={"label": "UW Selected %", "format": {"output": "percent", "mantissa": 0}}),
                        "comments": hx.Str(mode="input", default=None, async_output=["start_renewal_task"], optionality="optional", view={"label": "Comment"}),
                    }),
                    "terms_conditions_change": hx.Structure(view={"label": "Terms & Conditions Change"}, children={
                        "model_calculated": hx.Float(mode="output", async_output=["rarc_task"], view={"label": "Model %", "format": {"output": "percent", "mantissa": 0}}),
                        "uw_selected": hx.Float(mode="override", async_output=["rarc_task", "start_renewal_task"], view={"label": "UW Selected %", "format": {"output": "percent", "mantissa": 0}}),
                        "comments": hx.Str(mode="input", default=None, async_output=["start_renewal_task"], optionality="optional", view={"label": "Comment"}),
                    }),
                    "other_change": hx.Structure(view={"label": "Other Change"}, children={
                        "model_calculated": hx.Float(mode="output", async_output=["rarc_task"], view={"label": "Model %", "format": {"output": "percent", "mantissa": 0}}),
                        "uw_selected": hx.Float(mode="override", async_output=["rarc_task", "start_renewal_task"], view={"label": "UW Selected %", "format": {"output": "percent", "mantissa": 0}}),
                        "comments": hx.Str(mode="input", default=None, async_output=["start_renewal_task"], optionality="optional", view={"label": "Comment"}),
                    }),
                    "brokerage_change": hx.Structure(view={"label": "Brokerage Change"}, children={
                        "model_calculated": hx.Float(mode="output", async_output=["rarc_task"], view={"label": "Model %", "format": {"output": "percent", "mantissa": 0}}),
                        "uw_selected": hx.Float(mode="override", async_output=["rarc_task", "start_renewal_task"], view={"label": "UW Selected %", "format": {"output": "percent", "mantissa": 0}}),
                        "comments": hx.Str(mode="input", default=None, async_output=["start_renewal_task"], optionality="optional", view={"label": "Comment"}),
                    }),
                    "rate_change": hx.Structure(view={"label": "Risk Adjusted Rate Change"}, children={
                        "model_calculated": hx.Float(mode="output", view={"label": "Model %", "format": {"output": "percent", "mantissa": 0}}),
                        "uw_selected": hx.Float(mode="output", view={"label": "UW Selected %", "format": {"output": "percent", "mantissa": 0}}),
                        "comments": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Comment"}),
                        "lloyds_limit_attachment_point_change": hx.Float(mode="output", view={"label": "Lloyds's Limit Attachment Point Change", "format": {"output": "percent", "mantissa": 0}}),
                        "lloyds_breadth_of_cover_change": hx.Float(mode="output", view={"label": "Lloyds's Breadth of Cover Change", "format": {"output": "percent", "mantissa": 0}}),
                        "other_factors_change": hx.Float(mode="output", view={"label": "Other Factors Change", "format": {"output": "percent", "mantissa": 0}}),
                    }),
                    "expiring_layer": hx.Int(mode="input", default=1, optionality="optional", view={"label": "Expiring Layer"}),
                    "rebased_expiring_premium": hx.Float(mode="output", async_output=["rarc_task"], view={"label": "Rebased Expiring Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "premium_policy_term_beazley_share": hx.Structure(view={"label": "Premium - Policy Term (Beazley Share)"}, children={
                        "renewal": hx.Float(mode="output", view={"label": "Renewal", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "expiring": hx.Float(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task", "case_priced_expiry_import"], view={"label": "Expiring", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    }),
                    "premium_policy_term_100pct": hx.Structure(view={"label": "Premium - Policy Term (100% Share)"}, children={
                        "renewal": hx.Float(mode="output", view={"label": "Renewal", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "expiring": hx.Float(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task", "case_priced_expiry_import"], view={"label": "Expiring", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    }),
                    "premium_annualized_beazley_share": hx.Structure(view={"label": "Annualised Premium (Beazley Share)"}, children={
                        "renewal": hx.Float(mode="output", view={"label": "Renewal", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "expiring": hx.Float(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task", "case_priced_expiry_import"], view={"label": "Expiring", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    }),
                    "premium_annualized_100pct": hx.Structure(view={"label": " Annualised Premium (100% Share)"}, children={
                        "renewal": hx.Float(mode="output", view={"label": "Renewal", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "expiring": hx.Float(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task", "case_priced_expiry_import"], view={"label": "Expiring", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    }),
                    "expiring_policy_info": hx.Structure(children={
                        "expiring_exposure": hx.Float(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task"]),
                        "expiring_policy_length": hx.Float(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task"]),
                        "expiring_premium": hx.Float(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task"]),
                        "expiring_limit": hx.Float(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task"]),
                        "expiring_deductible": hx.Float(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task"]),
                        "expiring_brokerage": hx.Float(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task"]),
                        "expiring_written_line": hx.Float(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task"]),
                        "expiring_expected_loss": hx.Float(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task"]),
                        "expiring_bpi": hx.Float(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task", "case_priced_expiry_import"]),
                    }),
                    "simple_rate_change": hx.Float(mode="output", view={"label": "Pure Premium Change / Simple Rate Change", "format": {"output": "percent", "mantissa": 0}}),
                    "risk_adjusted_rate_change": hx.Structure(view={"label": "Underwriter Selected"}, children={
                        "technical": hx.Float(mode="output", view={"label": "Model Risk Adjusted Rate Change", "format": {"output": "percent", "mantissa": 0}}),
                        "technical_net_brokerage": hx.Float(mode="output", view={"format": {"output": "percent", "mantissa": 0}}),
                        "uw_selected": hx.Float(mode="output", view={"label": "UW Selected Risk Adjusted Rate Change", "format": {"output": "percent", "mantissa": 0}}),
                        "uw_selected_net_brokerage": hx.Float(mode="output", view={"label": "UW Selected Risk Adjusted Rate Change", "format": {"output": "percent", "mantissa": 0}}),
                    }),
                    "risk_adjusted_rate_change_case_priced": hx.Structure(view={"label": "Underwriter Selected"}, children={
                        "uw_selected": hx.Float(mode="override", view={"label": "UW Selected Risk Adjusted Rate Change", "format": {"output": "percent", "mantissa": 0}}),
                        "uw_selected_net_brokerage": hx.Float(mode="output", view={"label": "UW Selected Risk Adjusted Rate Change Net Brokerage", "format": {"output": "percent", "mantissa": 0}}),
                        "comments": hx.Str(mode="input", default="", view={"label": "Comment"}),
                    }),
                    "error_message": hx.Str(mode="output"),
                    "temp_storage": hx.Structure(children={
                        "quoted_premium": hx.Float(mode="output", async_output=["rarc_task"]),
                        "benchmark_premium": hx.Float(mode="output", async_output=["rarc_task"]),
                    }),
                }),
                "type": hx.Str(mode="input", default="Deductible", async_input=["rarc_task"], options=["Deductible", "Excess"], view={"label": "Type"}),
                "agg_limits_list": hx.List(mode="output", children={
                    "values": hx.Float(mode="output"),
                }),
                "min_premium": hx.Structure(children={
                    "education": hx.Float(mode="output"),
                    "non_education": hx.Float(mode="output"),
                    "flag": hx.Bool(mode="output"),
                }),
                "expected_loss": hx.Structure(children={
                    "education": hx.Float(mode="output", view={"label": "Education Loss Cost", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "non_education": hx.Float(mode="output", view={"label": "Non-Education Loss Cost", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "exposure_rated": hx.Float(mode="output", view={"label": "Exposure Rated", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "experience_rated": hx.Float(mode="output", view={"label": "Experience Rated", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "experience_weight": hx.Float(mode="output", view={"label": "Experience Weight", "format": {"output": "percent", "mantissa": 0}}),
                    "blended": hx.Float(mode="output", view={"label": "Blended Expected Loss", "format": {"thousandSeparated": True, "mantissa": 0}}),
                }),
                "filter": hx.Bool(mode="output"),
                "label": hx.Str(mode="output"),
                "bpi_case_priced": hx.Float(mode="input", default=0, optionality="required", view={"label": "BPI (Case Priced)", "format": {"output": "percent", "mantissa": 1}}),
                "suggested_epi": hx.Float(mode="output", view={"label": "Suggested EPI", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "alt_limit": hx.Float(mode="override", view={"label": "Alt Limit", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "alt_agg_limit": hx.Float(mode="override", view={"label": "Alt Agg Limit", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "benchmark_premium_annualised": hx.Float(mode="output", async_input=["rarc_task"], view={"label": "Annualised Benchmark Premium (100%)", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "quoted_premium_annualised": hx.Float(mode="output", async_input=["rarc_task"], view={"label": "Annualised Quoted Premium (100%)", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "benchmark_premium_pre_uw_adj": hx.Float(mode="output", view={"label": "Benchmark Premium Before UW Adj", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "bpi_case_priced_view": hx.Float(mode="output", view={"label": "BPI", "format": {"output": "percent", "mantissa": 1}}),
                "quoted_premium_view": hx.Float(mode="output", view={"label": "Gross Quoted Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "written_line_view": hx.Float(mode="output", optionality="optional", view={"label": "Written Line", "format": {"output": "percent", "mantissa": 1}}),
                "brokerage_view": hx.Float(mode="output", optionality="optional", view={"label": "Brokerage (excl. PC's)", "format": {"output": "percent", "mantissa": 1}}),
                "status_view": hx.Str(mode="output", view={"label": "Status"}),
                "section_reference_view": hx.Str(mode="output", view={"label": "Section Reference"}),
                "pflr_pre_uw_adj": hx.Float(mode="output", view={"label": "Priced-for Loss Ratio (Pre-UW Adjustment)", "format": {"output": "percent", "mantissa": 1}}),
                "benchmark_premium_view": hx.Float(mode="output", view={"label": "Gross Benchmark Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
            }),
            "currencies": hx.Structure(view={"label": "Currencies"}, children={
                "target_currency": hx.Str(mode="input", default=None, optionality="optional", options=["ADP", "AFA", "AON", "AOR", "ATS", "AZM", "BEF", "BGL", "BRE", "BUK", "BYB", "BYR", "CSD", "CSK", "CYP", "DDM", "DEM", "ECS", "EEK", "ESP", "FIM", "FRF", "GHC", "GRD", "GWP", "HRK", "IEP", "ITL", "LTL", "LUF", "LVL", "MGF", "MRO", "MTL", "MXP", "MZM", "NIC", "NLG", "PES", "PLZ", "PTE", "ROL", "RUR", "SDD", "SDP", "SIT", "SKK", "SRG", "STD", "SUR", "TRL", "UYP", "VEB", "VEF", "XEU", "YUM", "ZMK", "ZRN", "ZRZ", "ZWD", "ZWR", "AED", "AFN", "ALL", "AMD", "ANG", "AOA", "ARS", "AUD", "AWG", "AZN", "BAM", "BBD", "BDT", "BGN", "BHD", "BIF", "BMD", "BND", "BOB", "BOV", "BRL", "BSD", "BTN", "BWP", "BYN", "BZD", "CAD", "CDF", "CHE", "CHF", "CHW", "CLF", "CLP", "CNY", "COP", "COU", "CRC", "CUC", "CUP", "CVE", "CZK", "DJF", "DKK", "DOP", "DZD", "EGP", "ERN", "ETB", "EUR", "FJD", "FKP", "GBP", "GEL", "GHS", "GIP", "GMD", "GNF", "GTQ", "GYD", "HKD", "HNL", "HTG", "HUF", "IDR", "ILS", "INR", "IQD", "IRR", "ISK", "JMD", "JOD", "JPY", "KES", "KGS", "KHR", "KMF", "KPW", "KRW", "KWD", "KYD", "KZT", "LAK", "LBP", "LKR", "LRD", "LSL", "LYD", "MAD", "MDL", "MGA", "MKD", "MMK", "MNT", "MOP", "MRU", "MUR", "MVR", "MWK", "MXN", "MXV", "MYR", "MZN", "NAD", "NGN", "NIO", "NOK", "NPR", "NZD", "OMR", "PAB", "PEN", "PGK", "PHP", "PKR", "PLN", "PYG", "QAR", "RON", "RSD", "RUB", "RWF", "SAR", "SBD", "SCR", "SDG", "SEK", "SGD", "SHP", "SLE", "SLL", "SOS", "SRD", "SSP", "STN", "SVC", "SYP", "SZL", "THB", "TJS", "TMT", "TND", "TOP", "TRY", "TTD", "TWD", "TZS", "UAH", "UGX", "USD", "USN", "UYI", "UYU", "UYW", "UZS", "VED", "VES", "VND", "VUV", "WST", "XAF", "XAG", "XAU", "XBA", "XBB", "XBC", "XBD", "XCD", "XDR", "XOF", "XPD", "XPF", "XPT", "XSU", "XTS", "XUA", "XXX", "YER", "ZAR", "ZMW", "ZWL"], view={"label": "Target Currency"}),
                "source_currency": hx.Str(mode="input", default="USD", optionality="required", options=["ADP", "AFA", "AON", "AOR", "ATS", "AZM", "BEF", "BGL", "BRE", "BUK", "BYB", "BYR", "CSD", "CSK", "CYP", "DDM", "DEM", "ECS", "EEK", "ESP", "FIM", "FRF", "GHC", "GRD", "GWP", "HRK", "IEP", "ITL", "LTL", "LUF", "LVL", "MGF", "MRO", "MTL", "MXP", "MZM", "NIC", "NLG", "PES", "PLZ", "PTE", "ROL", "RUR", "SDD", "SDP", "SIT", "SKK", "SRG", "STD", "SUR", "TRL", "UYP", "VEB", "VEF", "XEU", "YUM", "ZMK", "ZRN", "ZRZ", "ZWD", "ZWR", "AED", "AFN", "ALL", "AMD", "ANG", "AOA", "ARS", "AUD", "AWG", "AZN", "BAM", "BBD", "BDT", "BGN", "BHD", "BIF", "BMD", "BND", "BOB", "BOV", "BRL", "BSD", "BTN", "BWP", "BYN", "BZD", "CAD", "CDF", "CHE", "CHF", "CHW", "CLF", "CLP", "CNY", "COP", "COU", "CRC", "CUC", "CUP", "CVE", "CZK", "DJF", "DKK", "DOP", "DZD", "EGP", "ERN", "ETB", "EUR", "FJD", "FKP", "GBP", "GEL", "GHS", "GIP", "GMD", "GNF", "GTQ", "GYD", "HKD", "HNL", "HTG", "HUF", "IDR", "ILS", "INR", "IQD", "IRR", "ISK", "JMD", "JOD", "JPY", "KES", "KGS", "KHR", "KMF", "KPW", "KRW", "KWD", "KYD", "KZT", "LAK", "LBP", "LKR", "LRD", "LSL", "LYD", "MAD", "MDL", "MGA", "MKD", "MMK", "MNT", "MOP", "MRU", "MUR", "MVR", "MWK", "MXN", "MXV", "MYR", "MZN", "NAD", "NGN", "NIO", "NOK", "NPR", "NZD", "OMR", "PAB", "PEN", "PGK", "PHP", "PKR", "PLN", "PYG", "QAR", "RON", "RSD", "RUB", "RWF", "SAR", "SBD", "SCR", "SDG", "SEK", "SGD", "SHP", "SLE", "SLL", "SOS", "SRD", "SSP", "STN", "SVC", "SYP", "SZL", "THB", "TJS", "TMT", "TND", "TOP", "TRY", "TTD", "TWD", "TZS", "UAH", "UGX", "USD", "USN", "UYI", "UYU", "UYW", "UZS", "VED", "VES", "VND", "VUV", "WST", "XAF", "XAG", "XAU", "XBA", "XBB", "XBC", "XBD", "XCD", "XDR", "XOF", "XPD", "XPF", "XPT", "XSU", "XTS", "XUA", "XXX", "YER", "ZAR", "ZMW", "ZWL"], view={"label": "Source Currency"}),
                "multi_currency_support": hx.Bool(mode="input", default=False, optionality="required", view={"label": "Multi Currency Support"}),
                "rates": hx.List(mode="input", view={"label": "Rates"}, children={
                    "code": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Code"}),
                    "rate": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Rate", "format": {"thousandSeparated": False, "mantissa": 2}}),
                }),
            }),
            "experience_rating": hx.Structure(view={"label": "Experience Rating"}, children={
                "claims_available": hx.Bool(mode="input", default=False, view={"label": "Loss Data Avaialble"}),
                "claims_fgu": hx.Bool(mode="input", default=False, view={"label": "Claims From Ground Up"}),
                "claims_net_of_deductible": hx.Bool(mode="input", default=False, view={"label": "Are Claims net of Deductible"}),
                "er_calcs": hx.List(mode="input", default_element_count=8, max_element_count=8, min_element_count=8, children={
                    "include": hx.Bool(mode="input", default=True, view={"label": "Include?"}),
                    "yoa": hx.Int(mode="output", view={"label": "YOA", "format": {"thousandSeparated": False, "mantissa": 0}}),
                    "yoa_label": hx.Str(mode="output", view={"label": "YOA"}),
                    "exp_non_ed": hx.Int(mode="input", default=None, async_output=["backfill_exposure"], optionality="optional", validation={"min_value": 0}, view={"label": "Non-Education\nNumber of\nEstablishments", "group": "Exposure", "format": {"thousandSeparated": False, "mantissa": 0}}),
                    "exp_ed": hx.Int(mode="input", default=None, async_output=["backfill_exposure"], optionality="optional", validation={"min_value": 0}, view={"label": "Education\nNumber of\nSchools", "group": "Exposure", "format": {"thousandSeparated": False, "mantissa": 0}}),
                    "sel_exp_base": hx.Int(mode="output", view={"label": "Selected\nExposure\nBase", "group": "Exposure", "format": {"thousandSeparated": False, "mantissa": 0}}),
                    "gnwp": hx.Float(mode="output", view={"label": "GNWP", "group": "Gross Net Premium (USD 000s)", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "rate_change": hx.Float(mode="output", view={"label": "Rate Change", "group": "Gross Net Premium (USD 000s)", "format": {"output": "percent", "mantissa": 0}}),
                    "rate_change_index": hx.Float(mode="output", view={"label": "Rate Change\nIndex", "group": "Gross Net Premium (USD 000s)", "format": {"output": "percent", "mantissa": 0}}),
                    "on_level_premium": hx.Float(mode="output", view={"label": "On-Levelled\nPremium", "group": "Gross Net Premium (USD 000s)", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "attrition_incurred": hx.Float(mode="output", view={"label": "Incurred", "group": "Attritional Projection (USD 000s)", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "attrition_dev_factor": hx.Float(mode="output", view={"label": "Dev\nFactor", "group": "Attritional Projection (USD 000s)", "format": {"output": "percent", "mantissa": 0}}),
                    "attrition_ielr": hx.Float(mode="output", view={"label": "IELR", "group": "Attritional Projection (USD 000s)", "format": {"output": "percent", "mantissa": 0}}),
                    "attrition_ult_claims": hx.Float(mode="output", view={"label": "Ult Claims", "group": "Attritional Projection (USD 000s)", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "attrition_on_level_ulr": hx.Float(mode="output", view={"label": "On-Levelled\nULR", "group": "Attritional Projection (USD 000s)", "format": {"output": "percent", "mantissa": 0}}),
                    "large_incurred": hx.Float(mode="output", view={"label": "Incurred", "group": "Large Loss Projection (USD 000s)", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "large_avg_lr": hx.Float(mode="output", view={"label": "Average\nLL LR", "group": "Large Loss Projection (USD 000s)", "format": {"output": "percent", "mantissa": 1}}),
                    "large_ll_assumption": hx.Float(mode="output", view={"label": "LL\nAssumption", "group": "Large Loss Projection (USD 000s)", "format": {"output": "percent", "mantissa": 1}}),
                    "large_weighted_ll": hx.Float(mode="output", view={"label": "Weighted\nLL", "group": "Large Loss Projection (USD 000s)", "format": {"output": "percent", "mantissa": 1}}),
                    "large_ult_claims": hx.Float(mode="output", view={"label": "Ult Claims", "group": "Large Loss Projection (USD 000s)", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "large_ulr": hx.Float(mode="output", view={"label": "ULR", "group": "Large Loss Projection (USD 000s)", "format": {"output": "percent", "mantissa": 0}}),
                    "cat_incurred": hx.Float(mode="output", view={"label": "Incurred", "group": "Cat Claims Projection (USD 000s)", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "cat_avg": hx.Float(mode="output", view={"label": "Average", "group": "Cat Claims Projection (USD 000s)", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "cat_rms_or_bp": hx.Float(mode="output", view={"label": "BP Implied", "group": "Cat Claims Projection (USD 000s)", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "cat_bp": hx.Float(mode="output", view={"label": "BP Implied", "group": "Total Projection (USD 000s)", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "cat_ult_claims": hx.Float(mode="output", view={"label": "Ult Claims", "group": "Cat Claims Projection (USD 000s)", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "cat_ulr": hx.Float(mode="output", view={"label": "ULR", "group": "Cat Claims Projection (USD 000s)", "format": {"output": "percent", "mantissa": 1}}),
                    "total_att_ll_incurred": hx.Float(mode="output", view={"label": "Attr + LL\nIncurred", "group": "Total Projection (USD 000s)", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "total_att_ll_dev_factor": hx.Float(mode="output", view={"label": "Dev\nFactor", "group": "Total Projection (USD 000s)", "format": {"output": "percent", "mantissa": 0}}),
                    "total_att_ll_ielr": hx.Float(mode="output", view={"label": "IELR", "group": "Total Projection (USD 000s)", "format": {"output": "percent", "mantissa": 0}}),
                    "total_ult_claims": hx.Float(mode="output", view={"label": "Ult Claims", "group": "Total Projection (USD 000s)", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "total_on_level_ulr": hx.Float(mode="output", view={"label": "On-Levelled\nULR", "group": "Total Projection (USD 000s)", "format": {"output": "percent", "mantissa": 0}}),
                    "attrition_ll_ult_claims": hx.Float(mode="output", view={"label": "Attr + LL\nIncurred", "group": "Total Projection (USD 000s)", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "ultimate_claims": hx.Float(mode="output", view={"label": "Ultimate\nClaims", "group": "Ultimate Claims (USD 000s)", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "infl_index": hx.Float(mode="output", view={"label": "Infl Index", "group": "Ultimate Claims (USD 000s)", "format": {"output": "percent", "mantissa": 0}}),
                    "inf_ultimate": hx.Float(mode="output", view={"label": "Inf Ultimate", "group": "Ultimate Claims (USD 000s)", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "user_input_att": hx.Float(mode="input", default=None, optionality="optional", validation={"min_value": 0}, view={"label": "Attritional", "group": "Incurred Claims (USD 000s)", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "user_input_large": hx.Float(mode="input", default=None, optionality="optional", validation={"min_value": 0}, view={"label": "Large", "group": "Incurred Claims (USD 000s)", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "user_input_cat": hx.Float(mode="input", default=None, optionality="optional", validation={"min_value": 0}, view={"label": "CAT", "group": "Incurred Claims (USD 000s)", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "user_input_att_ll_total": hx.Float(mode="input", default=None, optionality="optional", validation={"min_value": 0}, view={"label": "Total", "group": "Incurred Claims (USD 000s)", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "user_input_gnwp": hx.Float(mode="input", default=None, optionality="optional", validation={"min_value": 0}, view={"label": "GNWP", "group": "Gross Net Premium (USD 000s)", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "user_input_rate_change": hx.Float(mode="input", default=None, optionality="optional", validation={"min_value": 0}, view={"label": "Rate Change", "group": "Gross Net Premium (USD 000s)", "format": {"output": "percent", "mantissa": 0}}),
                    "user_input_num_claims": hx.Float(mode="input", default=None, optionality="optional", validation={"min_value": 0}, view={"label": "Number Of\nClaims", "format": {"thousandSeparated": False, "mantissa": 0}}),
                    "user_input_total_paid": hx.Float(mode="input", default=None, optionality="optional", validation={"min_value": 0}, view={"label": "Total\nPaid", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "user_input_num_incidents": hx.Float(mode="input", default=None, optionality="optional", validation={"min_value": 0}, view={"label": "Number of\nIncidents", "group": "Frequency", "format": {"thousandSeparated": False, "mantissa": 0}}),
                    "user_input_num_deaths": hx.Float(mode="input", default=None, optionality="optional", validation={"min_value": 0}, view={"label": "Number of\nDeaths", "group": "Frequency", "format": {"thousandSeparated": False, "mantissa": 0}}),
                    "user_input_num_injuries": hx.Float(mode="input", default=None, optionality="optional", validation={"min_value": 0}, view={"label": "Number of\nInjuries", "group": "Frequency", "format": {"thousandSeparated": False, "mantissa": 0}}),
                    "num_incidents": hx.Float(mode="input", default=None, optionality="optional", validation={"min_value": 0}, view={"label": "Number of\nIncidents", "group": "Frequency", "format": {"thousandSeparated": False, "mantissa": 0}}),
                    "num_deaths": hx.Float(mode="input", default=None, optionality="optional", validation={"min_value": 0}, view={"label": "Number of\nDeaths", "group": "Frequency", "format": {"thousandSeparated": False, "mantissa": 0}}),
                    "num_injuries": hx.Float(mode="input", default=None, optionality="optional", validation={"min_value": 0}, view={"label": "Number of\nInjuries", "group": "Frequency", "format": {"thousandSeparated": False, "mantissa": 0}}),
                    "user_input_incurred_total": hx.Float(mode="input", default=None, optionality="optional", validation={"min_value": 0}, view={"label": "Incurred\nClaims", "group": "Incurred Claims (USD 000s)", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "frequency_ult_claims": hx.Float(mode="output", view={"label": "Ultimate\nClaims", "group": "Ultimate Claims (USD 000s)", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "frequency_infl_index": hx.Float(mode="output", view={"label": "Infl Index", "group": "Ultimate Claims (USD 000s)", "format": {"output": "percent", "mantissa": 0}}),
                    "frequency_inf_ultimate": hx.Float(mode="output", view={"label": "Inf Ultimate\n Claims", "group": "Ultimate Claims (USD 000s)", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "sel_infl_index": hx.Float(mode="output", view={"label": "Infl Index", "group": "Ultimate Claims (USD 000s)", "format": {"output": "percent", "mantissa": 0}}),
                }),
                "curr_yr": hx.Structure(children={
                    "yoa": hx.Int(mode="output", view={"label": "YOA", "format": {"thousandSeparated": False, "mantissa": 0}}),
                    "yoa_label": hx.Str(mode="output", view={"label": "YOA"}),
                    "exp_non_ed": hx.Int(mode="input", default=None, async_input=["backfill_exposure"], optionality="optional", validation={"min_value": 0}, view={"label": "Non-Education\nNumber of\nEstablishments", "group": "Exposure", "format": {"thousandSeparated": False, "mantissa": 0}}),
                    "exp_ed": hx.Int(mode="input", default=None, async_input=["backfill_exposure"], optionality="optional", validation={"min_value": 0}, view={"label": "Education\nNumber of\nSchools", "group": "Exposure", "format": {"thousandSeparated": False, "mantissa": 0}}),
                    "sel_exp_base": hx.Int(mode="output", view={"label": "Selected\nExposure\nBase", "group": "Exposure", "format": {"thousandSeparated": False, "mantissa": 0}}),
                    "rate_change": hx.Float(mode="output", view={"label": "Rate Change", "group": "Gross Net Premium (USD 000s)", "format": {"output": "percent", "mantissa": 0}}),
                    "user_input_rate_change": hx.Float(mode="input", default=None, optionality="optional", validation={"min_value": 0}, view={"label": "Rate Change", "group": "Gross Net Premium (USD 000s)", "format": {"output": "percent", "mantissa": 0}}),
                }),
                "er_totals": hx.Structure(children={
                    "yoa": hx.Str(mode="output"),
                    "gnwp": hx.Float(mode="output", view={"format": {"thousandSeparated": True, "mantissa": 0}}),
                    "exp_non_ed": hx.Float(mode="output", view={"format": {"thousandSeparated": True, "mantissa": 0}}),
                    "exp_ed": hx.Float(mode="output", view={"format": {"thousandSeparated": True, "mantissa": 0}}),
                    "sel_exp_base": hx.Float(mode="output", view={"format": {"thousandSeparated": True, "mantissa": 0}}),
                    "on_level_premium": hx.Float(mode="output", view={"format": {"thousandSeparated": True, "mantissa": 0}}),
                    "attrition_incurred": hx.Float(mode="output", view={"format": {"thousandSeparated": True, "mantissa": 0}}),
                    "attrition_ult_claims": hx.Float(mode="output", view={"format": {"thousandSeparated": True, "mantissa": 0}}),
                    "attrition_on_level_ulr": hx.Float(mode="output", view={"format": {"output": "percent", "mantissa": 0}}),
                    "large_incurred": hx.Float(mode="output", view={"format": {"thousandSeparated": True, "mantissa": 0}}),
                    "large_ult_claims": hx.Float(mode="output", view={"format": {"thousandSeparated": True, "mantissa": 0}}),
                    "large_ulr": hx.Float(mode="output", view={"format": {"output": "percent", "mantissa": 0}}),
                    "cat_incurred": hx.Float(mode="output", view={"format": {"thousandSeparated": True, "mantissa": 0}}),
                    "cat_ult_claims": hx.Float(mode="output", view={"format": {"thousandSeparated": True, "mantissa": 0}}),
                    "cat_ulr": hx.Float(mode="output", view={"format": {"output": "percent", "mantissa": 0}}),
                    "ultimate_claims": hx.Float(mode="output", view={"format": {"thousandSeparated": True, "mantissa": 0}}),
                    "inf_ultimate": hx.Float(mode="output", view={"format": {"thousandSeparated": True, "mantissa": 0}}),
                    "total_att_ll_incurred": hx.Float(mode="output", view={"format": {"thousandSeparated": True, "mantissa": 0}}),
                    "frequency_ult_claims": hx.Float(mode="output", view={"format": {"thousandSeparated": True, "mantissa": 0}}),
                    "frequency_inf_ultimate": hx.Float(mode="output", view={"format": {"thousandSeparated": True, "mantissa": 0}}),
                    "num_incidents": hx.Float(mode="output", view={"format": {"thousandSeparated": True, "mantissa": 0}}),
                    "num_deaths": hx.Float(mode="output", view={"format": {"thousandSeparated": True, "mantissa": 0}}),
                    "num_injuries": hx.Float(mode="output", view={"format": {"thousandSeparated": True, "mantissa": 0}}),
                    "user_input_att": hx.Float(mode="output", view={"format": {"thousandSeparated": True, "mantissa": 0}}),
                    "user_input_large": hx.Float(mode="output", view={"format": {"thousandSeparated": True, "mantissa": 0}}),
                    "user_input_cat": hx.Float(mode="output", view={"format": {"thousandSeparated": True, "mantissa": 0}}),
                    "user_input_att_ll_total": hx.Float(mode="output", view={"format": {"thousandSeparated": True, "mantissa": 0}}),
                    "user_input_gnwp": hx.Float(mode="output", view={"format": {"thousandSeparated": True, "mantissa": 0}}),
                    "user_input_num_incidents": hx.Float(mode="output", view={"format": {"thousandSeparated": True, "mantissa": 0}}),
                    "user_input_num_deaths": hx.Float(mode="output", view={"format": {"thousandSeparated": True, "mantissa": 0}}),
                    "user_input_num_injuries": hx.Float(mode="output", view={"format": {"thousandSeparated": True, "mantissa": 0}}),
                    "user_input_incurred_total": hx.Float(mode="output", view={"format": {"thousandSeparated": True, "mantissa": 0}}),
                }),
                "er_chart_data": hx.List(mode="output", children={
                    "yoa": hx.Float(mode="output"),
                    "exp_non_ed_perc": hx.Float(mode="output"),
                    "exp_ed_perc": hx.Float(mode="output"),
                    "gnwp_perc": hx.Float(mode="output"),
                }),
                "bi_policy_data": hx.List(mode="input", async_output=["sql_bi_fetch_task", "sql_bi_clear"], children={
                    "PolicyReference": hx.Str(mode="input", default=None, async_output=["sql_bi_fetch_task"], optionality="optional", view={"label": "Policy\nReference"}),
                    "SectionReference": hx.Str(mode="input", default=None, async_output=["sql_bi_fetch_task"], optionality="optional", view={"label": "Section\nReference"}),
                    "TriFocusName": hx.Str(mode="input", default=None, async_output=["sql_bi_fetch_task"], optionality="optional", view={"label": "TriFocus\nName"}),
                    "ClassOfBusinessCode": hx.Str(mode="input", default=None, async_output=["sql_bi_fetch_task"], optionality="optional", view={"label": "COB\nCode"}),
                    "StatsCode": hx.Str(mode="input", default=None, async_output=["sql_bi_fetch_task"], optionality="optional", view={"label": "Stats\nCode"}),
                    "YOA": hx.Int(mode="input", default=None, async_output=["sql_bi_fetch_task"], optionality="optional", view={"label": "YOA", "format": {"thousandSeparated": False, "mantissa": 0}}),
                    "SettlementCurrency": hx.Str(mode="input", default=None, async_output=["sql_bi_fetch_task"], optionality="optional", view={"label": "Settlement\nCurrency"}),
                    "ExternalAcquisitionCostMultiplier": hx.Float(mode="input", default=None, async_output=["sql_bi_fetch_task"], optionality="optional", view={"label": "Acquisition\nCost"}),
                    "WrittenOrEstimatedPremium": hx.Float(mode="input", default=None, async_output=["sql_bi_fetch_task"], optionality="optional", view={"label": "Written\nPremium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "RateChangeDivisor": hx.Float(mode="input", default=None, async_output=["sql_bi_fetch_task"], optionality="optional", view={"label": "Rate Change\nDivisor", "format": {"output": "percent", "mantissa": 0}}),
                    "BenchmarkPremium": hx.Float(mode="input", default=None, async_output=["sql_bi_fetch_task"], optionality="optional", view={"label": "Benchmark\nPremium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "TotalWrittenIfNotSignedMultiplier": hx.Float(mode="input", default=None, async_output=["sql_bi_fetch_task"], optionality="optional", view={"label": "Signed\nLine", "format": {"output": "percent", "mantissa": 0}}),
                }),
                "bi_claim_data": hx.List(mode="input", async_output=["sql_bi_fetch_task", "sql_bi_clear"], children={
                    "PolicyReference": hx.Str(mode="input", default=None, async_output=["sql_bi_fetch_task"], optionality="optional", view={"label": "Policy\nReference"}),
                    "SectionReference": hx.Str(mode="input", default=None, async_output=["sql_bi_fetch_task"], optionality="optional", view={"label": "Section\nReference"}),
                    "TriFocusName": hx.Str(mode="input", default=None, async_output=["sql_bi_fetch_task"], optionality="optional", view={"label": "TriFocus\nName"}),
                    "YOA": hx.Int(mode="input", default=None, async_output=["sql_bi_fetch_task"], optionality="optional", view={"label": "YOA", "format": {"thousandSeparated": False, "mantissa": 0}}),
                    "ClaimReference": hx.Str(mode="input", default=None, async_output=["sql_bi_fetch_task"], optionality="optional", view={"label": "Claim\nReference"}),
                    "MarketCatCode": hx.Str(mode="input", default=None, async_output=["sql_bi_fetch_task"], optionality="optional", view={"label": "Market Cat\nCode"}),
                    "BeazleyShareTotalPaidInUSD": hx.Float(mode="input", default=None, async_output=["sql_bi_fetch_task"], optionality="optional", view={"label": "Paid\nUSD", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "BeazleyShareTotalOutstandingInUSD": hx.Float(mode="input", default=None, async_output=["sql_bi_fetch_task"], optionality="optional", view={"label": "Outstanding\nUSD", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "BeazleyShareTotalIncurredInUSD": hx.Float(mode="input", default=None, async_output=["sql_bi_fetch_task"], optionality="optional", view={"label": "Incurred\nUSD", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "SettlementCurrency": hx.Str(mode="input", default=None, async_output=["sql_bi_fetch_task"], optionality="optional", view={"label": "Settlement\nCurrency"}),
                    "SlipOrderTotalIncurred": hx.Float(mode="input", default=None, async_output=["sql_bi_fetch_task"], optionality="optional", view={"label": "Slip Order\nTotal Incurred", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "SignedLineMultiplier": hx.Float(mode="input", default=None, async_output=["sql_bi_fetch_task"], optionality="optional", view={"label": "Signed\nLine", "format": {"output": "percent", "mantissa": 0}}),
                }),
                "cat_rms_or_bp": hx.Float(mode="override", view={"label": "RMS / Business Plan Cat LR", "format": {"output": "percent", "mantissa": 2}}),
                "data_source": hx.Str(mode="input", default_index=0, options=["Import from BI", "User to input data"], view={"label": "Data Source"}),
                "final_burning_cost": hx.Float(mode="output", view={"label": "FINAL SELECTION - BURNING COST", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "credibility_weight": hx.Float(mode="output", view={"label": "Credibility Weight", "format": {"output": "percent", "mantissa": 0}}),
                "cat_event": hx.Str(mode="input", default_index=0, options=["Yes", "No"], view={"label": "CAT Experience in Data"}),
                "experience_data": hx.Str(mode="input", default_index=0, options=["Yes", "No"], view={"label": "Experience Data Available"}),
                "actual_incurred": hx.Str(mode="input", default_index=0, options=["No", "Yes"], view={"label": "Actual Incurred Available"}),
                "exposure_trend": hx.Float(mode="input", default=None, async_input=["backfill_exposure"], optionality="optional", validation={"min_value": 0, "max_value": 1}, view={"label": "Exposure Trend", "format": {"output": "percent", "mantissa": 0}}),
            }),
            "broker_contact": hx.Str(mode="input", default="", view={"label": "Broker Contact"}),
            "rating_factors": hx.Structure(children={
                "bi_and_ee_cover": hx.Bool(mode="input", default=False, async_input=["rarc_task"], view={"label": "BI & EE Cover?"}),
                "seperate_bi_ee_agg_limits": hx.Bool(mode="input", default=False, async_input=["rarc_task"], view={"label": "Seperate BI and EE Agg Limits?"}),
                "bi_tiv": hx.Float(mode="input", default=None, async_input=["rarc_task"], optionality="optional", view={"label": "BI Total Insured Value", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "extensions_covered": hx.Float(mode="input", default=0, async_input=["rarc_task"], options=[0, 0.05, 0.1, 0.15, 0.2, 0.25], view={"label": "Extensions Covered?", "format": {"output": "percent", "mantissa": 0}}),
                "liability_covered": hx.Bool(mode="input", default=True, async_input=["rarc_task"], view={"label": "Liability Covered? "}),
                "risk_preparedness": hx.Str(mode="input", default="Average", async_input=["rarc_task"], options_column="Level", options_table="preparedness_factor", view={"label": "Risk Preparedness"}),
                "security": hx.Str(mode="input", default="Average", async_input=["rarc_task"], options_column="Level", options_table="preparedness_factor", view={"label": "Security"}),
                "crisis_management": hx.Str(mode="input", default="Average", async_input=["rarc_task"], options_column="Level", options_table="preparedness_factor", view={"label": "Crisis Management"}),
                "social_media": hx.Bool(mode="input", default=False, async_input=["rarc_task"], view={"label": "Social Media"}),
                "high_profile_event": hx.Str(mode="input", default_index=0, async_input=["rarc_task"], options_column="High Profile Event", options_table="preparedness_factor_high_profile_event", view={"label": "High Profile Event?"}),
                "base_inflation": hx.Float(mode="output"),
                "social_inflation": hx.Float(mode="output"),
                "policy_term": hx.Float(mode="output"),
                "preparedness_factor_ed": hx.Float(mode="output", async_input=["rarc_task"]),
                "preparedness_factor_non_ed": hx.Float(mode="output", async_input=["rarc_task"]),
            }),
            "ground_up_expected_loss": hx.Structure(children={
                "education": hx.Float(mode="output"),
                "non_education": hx.Float(mode="output"),
                "education_annualised": hx.Float(mode="output", async_input=["rarc_task"]),
                "non_education_annualised": hx.Float(mode="output", async_input=["rarc_task"]),
            }),
            "modifiers": hx.Structure(children={
                "underwriter_adjustment": hx.Float(mode="input", default=None, async_input=["rarc_task"], optionality="optional", validation={"min_value": -0.5, "max_value": 0.5}, view={"label": "Underwriter Adjustment", "format": {"output": "percent", "mantissa": 0}}),
            }),
            "min_premium_base": hx.Structure(children={
                "education": hx.Float(mode="output"),
                "non_education": hx.Float(mode="output"),
            }),
            "uw_rationale": hx.Structure(children={
                "knowledge_of_insured": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Knowledge of the Insured)"}),
                "portfolio_fit": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Portfolio Fit"}),
                "basis_of_risk_selection": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Basis of Risk Selection"}),
                "complex_considerations": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Any Unusual or Complex Considerations"}),
                "facts_affecting_decision": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Any facts which affect Underwriter's decision?"}),
                "comments": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Underwriter Comments"}),
                "extensions_comment": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Extensions Comment"}),
                "is_rationale_required": hx.Bool(mode="output"),
            }),
            "rate_change": hx.Structure(children={
                "expiring_policy_option_id": hx.Int(mode="override", async_input=["expiring_policy_fetch_task", "rarc_task", "case_priced_expiry_import"], view={"label": "Expiring Policy Option", "format": {"thousandSeparated": False}}),
                "has_fetch_not_run": hx.Bool(mode="input", default=True, async_output=["expiring_policy_fetch_task", "rarc_task"]),
                "has_fetch_run": hx.Bool(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task"]),
                "has_rarc_not_run": hx.Bool(mode="input", default=True, async_output=["rarc_task"]),
                "has_rarc_run": hx.Bool(mode="output", async_output=["rarc_task"]),
                "rarc_run_again_message": hx.Str(mode="output"),
                "rarc_message_show": hx.Bool(mode="output"),
                "layer_mapping": hx.Str(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task"]),
            }),
        }),
        "uw_validation": hx.Structure(children={
            "underwriter_warning": hx.Str(mode="output"),
            "show_underwriter_warning": hx.Bool(mode="output"),
        }),
        "model_state": hx.Structure(children={
            "pressed_start_renewal_task": hx.Bool(mode="output", async_output=["start_renewal_task"]),
            "show_landing_page": hx.Bool(mode="output"),
            "show_after_landing_page": hx.Bool(mode="output"),
            "show_rate_change": hx.Bool(mode="output"),
            "landing_page_info": hx.Str(mode="input", default="Click 'Import Expiring Policy Data' in the top right corner then click 'Start Policy'", async_output=["start_renewal_task"], view={"read_only": True}),
            "expiring_policy_option_id": hx.Int(mode="input", default=None, async_output=["start_renewal_task", "sync_expiring_ids"], optionality="optional"),
        }),
        "messages": hx.Structure(children={
            "crime_website": hx.Str(mode="output"),
            "policy_info_note": hx.Str(mode="output"),
            "experience_rating_note": hx.Str(mode="output"),
            "fetch_bi_task_status": hx.Str(mode="output", async_output=["sql_bi_fetch_task", "sql_bi_clear", "backfill_exposure"]),
            "epi_heading": hx.Str(mode="output"),
            "rating_summary_note": hx.Str(mode="output"),
            "min_premium_note": hx.Str(mode="output", view={"label": " "}),
        }),
        "flags": hx.Structure(children={
            "deductible_flag": hx.Bool(mode="output"),
            "excess_flag": hx.Bool(mode="output"),
            "er_source_bi": hx.Bool(mode="output"),
            "er_source_user": hx.Bool(mode="output"),
            "er_cat_yes": hx.Bool(mode="output"),
            "er_cat_no": hx.Bool(mode="output"),
            "er_experience_data": hx.Bool(mode="output"),
            "er_experience_data_no": hx.Bool(mode="output"),
            "er_actual_incurred": hx.Bool(mode="output"),
            "er_actual_incurred_no": hx.Bool(mode="output"),
            "show_bi_claims": hx.Bool(mode="input", default=False, view={"label": "Reveal Underlying BI Data"}),
            "extensions_comment_flag": hx.Bool(mode="output"),
            "validation_count": hx.Float(mode="output"),
        }),
        "subsector_rates_display": hx.List(mode="output", children={
            "Sector": hx.Str(mode="output", view={"label": "Sector"}),
            "SubSector": hx.Str(mode="output", view={"label": "SubSector"}),
            "BaseRate": hx.Float(mode="output", view={"label": "Base Rate\n(Freq Per Est.)", "format": {"output": "percent", "mantissa": 4}}),
            "Relativity": hx.Float(mode="output", view={"label": "Relativity Within\nSector", "format": {"thousandSeparated": False, "mantissa": 4}}),
        }),
        "city_rates_display": hx.List(mode="output", children={
            "State": hx.Str(mode="output", view={"label": "State"}),
            "City": hx.Str(mode="output", view={"label": "City"}),
            "Population": hx.Float(mode="output", view={"label": "Population", "format": {"thousandSeparated": True, "mantissa": 0}}),
            "ViolentCrime": hx.Float(mode="output", view={"label": "Violent\nCrime", "format": {"thousandSeparated": True, "mantissa": 0}}),
            "VCRate": hx.Float(mode="output", view={"label": "VC Rate", "format": {"output": "percent", "mantissa": 2}}),
            "Relativity": hx.Float(mode="output", view={"label": "Relativity", "format": {"thousandSeparated": False, "mantissa": 4}}),
            "CityRisk": hx.Str(mode="output", view={"label": "City\nRisk"}),
        }),
        "bug_report_email": hx.Str(mode="output"),
        "policy_doc": hx.Structure(children={
            "data_dict": hx.Str(mode="output", async_input=["policy_to_excel_task"]),
            "output_file": hx.File(mode="output", async_output=["policy_to_excel_task"], file_name="Policy_Summary.xlsx"),
            "task_data_dict": hx.Str(mode="output", async_output=["policy_to_excel_task"]),
            "show_generate_button": hx.Bool(mode="output"),
            "show_download": hx.Bool(mode="output"),
            "premium_check": hx.Str(mode="output"),
            "show_premium_check": hx.Bool(mode="output"),
        }),
        "bug_report": hx.Structure(children={
            "helper_text": hx.Str(mode="output", optionality="optional"),
            "recipient_email": hx.Str(mode="output", async_input=["send_bug_report_task"], async_output=["new_bug_report_task", {"task": "send_bug_report_task", "reset": False}, "cancel_bug_report_task"], view={"label": "Recipient Email"}),
            "cc_email": hx.Str(mode="output", async_input=["send_bug_report_task"], async_output=["new_bug_report_task", {"task": "send_bug_report_task", "reset": False}, "cancel_bug_report_task"], view={"label": "CC Email"}),
            "subject_line": hx.Str(mode="output", async_input=["send_bug_report_task"], async_output=["new_bug_report_task", {"task": "send_bug_report_task", "reset": False}, "cancel_bug_report_task"], view={"label": "Subject Line"}),
            "summary": hx.Str(mode="input", default="", async_input=["send_bug_report_task"], async_output=["new_bug_report_task", {"task": "send_bug_report_task", "reset": False}, "cancel_bug_report_task"], view={"multiline": True}),
            "email_body": hx.Str(mode="input", default=None, async_input=["send_bug_report_task"], async_output=["new_bug_report_task", {"task": "send_bug_report_task", "reset": False}, "cancel_bug_report_task"], optionality="optional", view={"label": "Details"}),
            "inputs_outputs_file_show": hx.Bool(mode="output", async_output=["new_bug_report_task"]),
            "inputs_outputs_file": hx.File(mode="output", async_output=["generate_bug_report_task", "cancel_bug_report_task", "send_bug_report_task"], file_name="inputs_outputs.json", view={"label": "Input/Outputs File"}),
            "file_helper_text": hx.Str(mode="input", default="**Note: Make sure to press the \"Upload File\" button to attach the file**", view={"options": {"read_only": {"read_only": True}}}),
            "files_shown": hx.Int(mode="input", default=1, async_output=["new_bug_report_task", {"task": "add_additional_file_task", "reset": False}]),
            "screenshot_files": hx.Structure(children={
                "f1": hx.Structure(children={
                    "file": hx.File(mode="input", async_input=["add_additional_file_task", "send_bug_report_task"], async_output=["new_bug_report_task", "cancel_bug_report_task"]),
                    "show_file": hx.Bool(mode="input", default=True, async_output=["new_bug_report_task", {"task": "add_additional_file_task", "reset": False}]),
                    "show_text": hx.Bool(mode="input", default=True, async_output=["new_bug_report_task", {"task": "add_additional_file_task", "reset": False}]),
                }),
                "f2": hx.Structure(children={
                    "file": hx.File(mode="input", async_input=["add_additional_file_task", "send_bug_report_task"], async_output=["new_bug_report_task", "cancel_bug_report_task"]),
                    "show_file": hx.Bool(mode="input", default=False, async_output=["new_bug_report_task", {"task": "add_additional_file_task", "reset": False}]),
                    "show_text": hx.Bool(mode="input", default=False, async_output=["new_bug_report_task", {"task": "add_additional_file_task", "reset": False}]),
                }),
                "f3": hx.Structure(children={
                    "file": hx.File(mode="input", async_input=["add_additional_file_task", "send_bug_report_task"], async_output=["new_bug_report_task", "cancel_bug_report_task"]),
                    "show_file": hx.Bool(mode="input", default=False, async_output=["new_bug_report_task", {"task": "add_additional_file_task", "reset": False}]),
                    "show_text": hx.Bool(mode="input", default=False, async_output=["new_bug_report_task", {"task": "add_additional_file_task", "reset": False}]),
                }),
                "f4": hx.Structure(children={
                    "file": hx.File(mode="input", async_input=["add_additional_file_task", "send_bug_report_task"], async_output=["new_bug_report_task", "cancel_bug_report_task"]),
                    "show_file": hx.Bool(mode="input", default=False, async_output=["new_bug_report_task", {"task": "add_additional_file_task", "reset": False}]),
                    "show_text": hx.Bool(mode="input", default=False, async_output=["new_bug_report_task", {"task": "add_additional_file_task", "reset": False}]),
                }),
                "f5": hx.Structure(children={
                    "file": hx.File(mode="input", async_input=["add_additional_file_task", "send_bug_report_task"], async_output=["new_bug_report_task", "cancel_bug_report_task"]),
                    "show_file": hx.Bool(mode="input", default=False, async_output=["new_bug_report_task", {"task": "add_additional_file_task", "reset": False}]),
                    "show_text": hx.Bool(mode="input", default=False, async_output=["new_bug_report_task", {"task": "add_additional_file_task", "reset": False}]),
                }),
            }),
            "commenced_flag": hx.Bool(mode="output", async_output=["new_bug_report_task", {"task": "send_bug_report_task", "reset": False}, "cancel_bug_report_task"], view={"label": "Commenced"}),
            "inputs_outputs": hx.Str(mode="output", async_input=["generate_bug_report_task", "cancel_bug_report_task", "new_bug_report_task", "send_bug_report_task"], view={"label": "Inputs/Outputs"}),
            "show_email": hx.Bool(mode="input", default=False),
            "model_name": hx.Str(mode="output", async_input=["send_bug_report_task"], async_output=["new_bug_report_task", {"task": "send_bug_report_task", "reset": False}, "cancel_bug_report_task"]),
        }),
    })
