// If changing the max_layers below, you must also update in rate_constants to the same number
const MAX_LAYERS = 6;

const YEARS_TO_CONSIDER_IN_RISK_CODE_COMPOSITION = 9;
const YEARS_TO_CONSIDER_IN_ASSUMED_DEDUCTIONS = YEARS_TO_CONSIDER_IN_RISK_CODE_COMPOSITION;
const YEARS_TO_CONSIDER_IN_PORTFOLIO_PROFILE = 26;
const YEARS_TO_CONSIDER_IN_Inflation = 26
const YEARS_TO_CONSIDER_IN_RATE_CHANGE = 16
const YEARS_TO_CONSIDER_IN_OWN_EXPERIENCE = 16
const MAX_NUM_LOB = 50
const MAX_NUM_RISK_CODES = 50
const NUM_CURVES_IN_CAT = 10
const NUM_SECTION_REFERENCES = 20


export {
  MAX_LAYERS,
  YEARS_TO_CONSIDER_IN_PORTFOLIO_PROFILE,
  YEARS_TO_CONSIDER_IN_RISK_CODE_COMPOSITION,
  YEARS_TO_CONSIDER_IN_ASSUMED_DEDUCTIONS,
  NUM_CURVES_IN_CAT,
  YEARS_TO_CONSIDER_IN_OWN_EXPERIENCE,
  MAX_NUM_LOB,
  YEARS_TO_CONSIDER_IN_Inflation,
  YEARS_TO_CONSIDER_IN_RATE_CHANGE,
  MAX_NUM_RISK_CODES,
  NUM_SECTION_REFERENCES
};
