name: Reusable - All - Model Release Emails

env:
  PATH_MODEL: model
  PATH_SHARED: shared
  PATH_PIPELINE: pipeline

on:
  workflow_call:
    inputs:
      FORM_BODY:
        required: true
        type: string
    secrets:
      READ_GITHUB_REPO_PAT:
        required: true
      EMAIL_AZURE_AD_CLIENTSECRET:
        required: true
    outputs:
      model_version_label:
        value: ${{ jobs.process.outputs.model_version_label }}
      release_note:
        value: ${{ jobs.process.outputs.release_note }}

jobs:
  process:
    runs-on:
      group: ubuntu-arm-runners
    outputs:
      model_version_label: ${{ steps.create-email-content.outputs.model_version_label }}
      release_note: ${{ steps.create-email-content.outputs.release_note }}
    steps:

      - name: Checkout model repository
        id: checkout-model-repository-main
        uses: actions/checkout@v4
        with:
          path: ${{ env.PATH_MODEL }}

      - name: Read model config
        id: read-model-config
        uses: actions/github-script@v7
        with:
          script: 
            const fs = require('fs');
            const jsonString = fs.readFileSync('${{ env.PATH_MODEL }}/.github/workflows/model_config.json', 'utf8');
            var model_config = JSON.parse(jsonString);
            core.setOutput('model_config', model_config);

      - name: Checkout shared repository
        id: checkout-shared-repository
        uses: actions/checkout@v4
        with:
          repository: beazley/poc-hyperexponential.rater.workflows
          ref: main
          token: ${{ secrets.READ_GITHUB_REPO_PAT }}
          path: ${{ env.PATH_SHARED }}

      - name: Read shared config
        id: read-shared-config
        uses: actions/github-script@v7
        with:
          script: 
            const fs = require('fs');
            const jsonString = fs.readFileSync('${{ env.PATH_SHARED }}/.github/workflows/shared_config.json', 'utf8');
            var shared_config = JSON.parse(jsonString);
            core.setOutput('shared_config', shared_config);

      - name: Prepare pipeline
        id: prepare-pipeline
        shell: bash
        run: |
          cp -r ${{ env.PATH_SHARED }}/.github/workflows/pipeline ${{ env.PATH_PIPELINE }}

      - name: Set up python
        id: set-up-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          
      - name: Restore cached virtualenv
        id: restore-cached-virtualenv
        uses: actions/cache/restore@v4
        with:
          key: venv-${{ runner.arch }}-${{ runner.os }}-${{ steps.set-up-python.outputs.python-version }}-${{ hashFiles(format('{0}/requirements.txt', env.PATH_PIPELINE)) }}
          path: .venv

      - name: Set up virtualenv and install dependencies
        id: setup-virtualenv
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install -r ${{ env.PATH_PIPELINE }}/requirements.txt
          echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH
          echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV

      - name: Saved cached virtualenv
        id: save-cached-virtualenv
        if: steps.restore-cached-virtualenv.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          key: venv-${{ runner.arch }}-${{ runner.os }}-${{ steps.set-up-python.outputs.python-version }}-${{ hashFiles(format('{0}/requirements.txt', env.PATH_PIPELINE)) }}
          path: .venv

      # - name: Correct Form Body
      #   id: correct-form-body
      #   uses: actions/github-script@v7
      #   with:
      #     retries: 3
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     script: |
      #       form_body = inputs.FORM_BODY
      #       form_body_corrected = form_body.replace(/'/g, "\\'")
      #       core.setOutput('form_body_corrected', form_body_corrected);

      - name: Issue Forms Body Parser
        id: parse
        uses: zentered/issue-forms-body-parser@93bd9fdcb3679be1889d2006e9c2cf496899402e
        with:
          body: ${{ inputs.FORM_BODY }}

      - name: Temp Notice
        id: temp_notice
        uses: actions/github-script@v7
        env:
          ISSUE_FORM_JSON: ${{ steps.parse.outputs.data }}
        with:
          retries: 3
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueForm = JSON.parse(process.env.ISSUE_FORM_JSON)
            core.notice("FORM_BODY: ${{ issueForm["release-note"].text }}");
            core.notice("-----");
            
      # core.notice("FORM_BODY: ${{ inputs.FORM_BODY }}");      
      # core.notice("release-note: ${{ issueForm["release-note"].text }}");


      - name: Create email content
        id: create-email-content
        uses: actions/github-script@v7
        env:
          ISSUE_FORM_JSON: ${{ steps.parse.outputs.data }}
        with:
          script: |
            const issueForm = JSON.parse(process.env.ISSUE_FORM_JSON)
            const model_config = ${{ steps.read-model-config.outputs.model_config }}
            const shared_config = ${{ steps.read-shared-config.outputs.shared_config }}
            var sender_upn = shared_config["EMAIL_SENDER_UPN"];
            const recipients_developer = [issueForm["developer"].text.replace("<", "").replace(">", "")]
            const recipients_ba_team = model_config["EMAIL_RECIPIENTS_BA_TEAM"] ?? shared_config["EMAIL_RECIPIENTS_BA_TEAM"];
            const recipients_it_team = model_config["EMAIL_RECIPIENTS_IT_TEAM"] ?? shared_config["EMAIL_RECIPIENTS_IT_TEAM"];
            const recipients_rating_support_and_enhancements_team = model_config["EMAIL_RECIPIENTS_RATING_SUPPORT_AND_ENHANCEMENTS_TEAM"] ?? shared_config["EMAIL_RECIPIENTS_RATING_SUPPORT_AND_ENHANCEMENTS_TEAM"];
            const recipients_stakeholders = model_config["EMAIL_RECIPIENTS_STAKEHOLDERS"]
            var recipients = [];
            recipients = recipients.concat(recipients_developer, recipients_ba_team, recipients_it_team, recipients_rating_support_and_enhancements_team, recipients_stakeholders);
            recipients = recipients.filter(n => n);
            var model_version_label;
            var model_version_label_no_v;
            var release_note;
            var subject;
            var body;
            model_version_label = issueForm["model-version-label"].text
            model_version_label_no_v = '' + model_version_label.replace('v', '')
            release_note = issueForm["release-note"].text
            subject = 'PROD Release - ' + issueForm["model-name"].text + ' - ' + model_version_label
            body = [
              'Please be advised that the following model version has been released to PROD',
              '',
              '<b>Model Name:</b> ' + issueForm["model-name"].text,
              '<b>Model Version Id:</b> ' + issueForm["model-version-id"].text,
              '<b>Model Version Label:</b> ' + model_version_label,
              '<b>Developer:</b> ' + issueForm["developer"].text.replace("<", "").replace(">", ""),
              '<b>Release Note:</b> ' + release_note
            ].join('<br>')
            core.setOutput('sender_upn', sender_upn)
            core.setOutput('recipients', recipients)
            core.setOutput('subject', subject)
            core.setOutput('body', body)
            core.setOutput('model_version_label', model_version_label_no_v)
            core.setOutput('release_note', release_note)

      - name: Send email
        id: send-email
        working-directory: ${{ env.PATH_PIPELINE }}
        run: python -u graph_emails.py
        env: 
          EMAIL_UPN: ${{ steps.create-email-content.outputs.sender_upn }}
          EMAIL_AZURE_AD_CLIENTID: ${{ fromJSON(steps.read-shared-config.outputs.shared_config).EMAIL_AZURE_AD_CLIENTID }}
          EMAIL_AZURE_AD_CLIENTSECRET: ${{ secrets.EMAIL_AZURE_AD_CLIENTSECRET }}
          EMAIL_AZURE_AD_TENANTID:  ${{ fromJSON(steps.read-shared-config.outputs.shared_config).EMAIL_AZURE_AD_TENANTID }}
          EMAIL_TO: ${{ steps.create-email-content.outputs.recipients }}
          EMAIL_SUBJECT: ${{ steps.create-email-content.outputs.subject }}
          EMAIL_BODY: ${{ steps.create-email-content.outputs.body }}