nodes = [
"cds/layers/benchmark_premium_100",
"cds/layers/benchmark_premium_uw_view",
"cds/layers/blended_model_net_rate",
"cds/layers/blended_uw_net_rate",
"cds/layers/bound_premium_share",
"cds/layers/bpi_bound_100",
"cds/layers/bpi_quoted_100",
"cds/layers/excess_agg",
"cds/layers/excess_eec",
"cds/layers/expected_loss_cost_net",
"cds/layers/experience_rate",
"cds/layers/experience_weighting",
"cds/layers/exposure_rate",
"cds/layers/exposure_rate_incl_adj",
"cds/layers/gross_rate_per_mill",
"cds/layers/technical_premium_100",
"cds/layers/tpi_bound_100",
"cds/layers/tpi_quoted_100",
"cds/layers/unadjusted_blended_model_net_rate",
"cds/layers/unadjusted_bound_tpi",
"cds/layers/unadjusted_exposure_rate",
"cds/layers/unadjusted_technical_premium",
"cds/layers/uw_experience_weighting",
"cds/layers_addl/benchmark_premium_100",
"cds/layers_addl/benchmark_premium_uw_view",
"cds/layers_addl/blended_model_net_rate",
"cds/layers_addl/blended_uw_net_rate",
"cds/layers_addl/bound_premium_share",
"cds/layers_addl/bpi_bound_100",
"cds/layers_addl/bpi_quoted_100",
"cds/layers_addl/expected_loss_cost_net",
"cds/layers_addl/experience_rate",
"cds/layers_addl/experience_weighting",
"cds/layers_addl/exposure_rate",
"cds/layers_addl/exposure_rate_incl_adj",
"cds/layers_addl/gross_rate_per_mill",
"cds/layers_addl/technical_premium_100",
"cds/layers_addl/tpi_bound_100",
"cds/layers_addl/tpi_quoted_100",
"cds/layers_addl/uw_experience_weighting",

] 

for node in nodes:
    print(f"cds.override_node_properties('{node}', {{\"mode\":\"input\",\"default\":0}})")