import pandas as pd
import json
import os
import re

# Set up mappings from Pandas datatypes to Renew datatypes
mappings = {
    "object": "str",
    "float": "float",
    "int": "int",
    "bool": "bool",
    "date": "date"
    }

parameter_tables_path = "/workspace/editing/parameter_tables"

param_table_output_json = {}

# Loop through the different .csv files in the parameter_tables folder within editing
for subdir, dirs, files in os.walk(os.path.dirname(parameter_tables_path)):
    for file in files:
        filepath = os.path.join(subdir, file)
        if file.endswith(".csv"):
            mapped_types = {}
            parameter_table = pd.read_csv(filepath)

            # Loop through each column in the .csv file and infer from the values within the column
            # which Renew datatype it is i.e. generate the parameter_tables_schema dictionary
            for col in parameter_table.columns:

                # Use str() to turn object to string to be passed as an argument to re.match()
                data_type = str(parameter_table[col].dtype) 
                for mapping in mappings:

                    # If data_type matches one of the keys in mappings, add the column name and mappings key to mapped_types
                    if re.match(mapping, data_type):
                        mapped_types[col] = mappings[mapping]

            param_table_output_json[file[:-4]] = mapped_types

# Output the parameter_tables_schema.json file within this subfolder
with open('/workspace/editing/test_cases/parameter_tables_schema_autogenerated.json', 'w', encoding='utf-8') as f:
    json.dump(param_table_output_json, f, ensure_ascii=False, indent=4)