import hx_data_schema as hx
from libraries.common_data_schema.data_schema.sch_common_data_schema import CommonDataSchema
from data_schema.sch_risk_information import sch_risk_information, sch_dropdowns, sch_private_priced
from data_schema.sch_tpi_calculations import sch_tpi_calculations
from data_schema.sch_exposure_details import sch_exposure_details
from data_schema.sch_pricing import sch_pricing, sch_pricing_modifier_labels
from data_schema.sch_pricing_runoff import sch_pricing_runoff
from data_schema.sch_rate_change import sch_rate_change
from data_schema.sch_rating_summary import sch_rating_summary
from data_schema.sch_admitted import sch_admitted
from data_schema.sch_admitted_excess import sch_admitted_excess
from data_schema.sch_autogenerated import sch_rater_defined
from data_schema.sch_model_state import sch_model_state
from data_schema.sch_historical_freq import sch_historical_freq
from data_schema.sch_rationale import sch_rationale
from libraries.email_notification.data_schema.bug_report_schema import bug_report


def sch_common_data_schema():
    cds = CommonDataSchema()

    sch_risk_information(cds)
    sch_private_priced(cds)
    sch_pricing(cds)
    sch_pricing_runoff(cds)
    sch_tpi_calculations(cds)
    sch_rate_change(cds)
    sch_rating_summary(cds)
    sch_admitted(cds)
    sch_admitted_excess(cds)
    sch_historical_freq(cds)
    sch_rationale(cds)
    
    sch_rater_defined(cds)

    set_child_nodes_to_rarc_task_inputs(cds.get_data_schema(), cds)

    return cds.get_data_schema()

#these are the data schema items used for formatting and don't go into the cds
def sch_non_cds_items():
    return {
        "non_cds": hx.Structure(children={
            **sch_pricing_modifier_labels(),
            **sch_dropdowns()            
        })
    }  

def set_child_nodes_to_rarc_task_inputs(nodes, cds, path=""):
    if path:
        path += "/"

    for node_name, node in nodes.items():
        node_path = path + node_name
        if isinstance(node, hx.Structure):
            set_child_nodes_to_rarc_task_inputs(node.children, cds, path=node_path)
        elif isinstance(node, hx.List):
            set_child_nodes_to_rarc_task_inputs(node.children, cds, path=node_path)
        elif node.mode != "output":
            if node_path in cds._CommonDataSchema__node_overrides:
                if "async_input" in cds._CommonDataSchema__node_overrides[node_path]:
                    cds._CommonDataSchema__node_overrides[node_path]["async_input"] += ["rarc_task"]
                else:
                    cds._CommonDataSchema__node_overrides[node_path]["async_input"] = ["rarc_task"]
            else:
                cds._CommonDataSchema__node_overrides[node_path] = {"async_input": ["rarc_task"]}


@hx.data_schema
def data_schema():
    return hx.Structure(children={
        **sch_common_data_schema(),
        **sch_model_state(),
        **bug_report(),
        **sch_non_cds_items()
    })