import hx_data_schema as hx
from data_schema.sch_utilities import thousands_format, percent_format, integer_format
import data_schema.sch_utilities as utils
import algorithms.rate_constants as const

def sch_pricing(cds):
    cds.extend_node_rater_defined("cds", {
        "dummy_false": hx.Bool(mode="output"),
        "entity_investigation": hx.Bool(mode="input", default=False, view={"label": "Entity Investigation"}), # Can't be autogenerated because need optionality removed
        # Bridge countries
        "bridge_countries": hx.Bool(mode="input", default=False, view={"label": "Bridge Countries?"}), # Can't be auto generated. Premium, Override & Comment are
        "bridge_country": hx.List(mode="input", view={"label": "Bride Countries"}, children={
            "country": hx.Str(mode="input", default=None, optionality="optional", options_column="Country", options_table="ref_bridge_countries", view={"label": "Bridge Country"}),
            "premium": hx.Float(mode="output", view={"label": "Premium", "format": {"thousandSeparated": True, "mantissa": 0}})
        }),

        "is_abc_rater_priced": hx.Bool(mode="output"),
        "is_abc_not_rater_priced": hx.Bool(mode="output"),
        "is_side_a_rater_priced": hx.Bool(mode="output"),
        "is_side_a_not_rater_priced": hx.Bool(mode="output"),

        # Modifiers
        "modifiers": hx.Structure(children={
            "freq_adj_factor": hx.Structure(view={"label": "Subjective Frequency Adjustment Factor"}, children={
                "value": hx.Float(mode="output", view={"label": "Value", "format": {"output": "percent", "mantissa": 2}})
            }),
            "obj_freq_adj_factor": hx.Structure(view={"label": "Objective Frequency Adjustment Factor"}, children={
                "value": hx.Float(mode="output", view={"label": "Value", "format": {"output": "percent", "mantissa": 2}}),
                "info": hx.Str(mode="output", view={"label": "None"}),
            }),  
            "total_freq_adj_factor": hx.Structure(view={"label": "Total Frequency Adjustment Factor"}, children={
                "value": hx.Float(mode="output", view={"label": "Value", "format": {"output": "percent", "mantissa": 2}})
            }),            
            "management_corp_gov": hx.Structure(view={"label": "Management and Corporate Governance"}, children={
                "value": hx.Float(mode="input", default=0, optionality="optional", view={"label": "Value"}),
                "comment": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Comment", "multiline": True}),
                #"comment_plain_text": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Comment", "multiline": True, "read_only":True}),
                "comment_plain_text": hx.Str(mode="output", view={"label": "Comment", "multiline": True}),
                "min": hx.Float(mode="output", view={"label": "Min"}),
                "max": hx.Float(mode="output", view={"label": "Max"}),
                "show_comment": hx.Bool(mode="input", default=False, view={"label": "Show?"}),
            }),
            "business_financial_model_factors": hx.Structure(view={"label": "Business / Financial Model Factors"}, children={
                "value": hx.Float(mode="input", default=0, optionality="optional", view={"label": "Value"}),
                "comment": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Comment", "multiline": True}),
                #"comment_plain_text": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Comment", "multiline": True, "read_only":True}),
                "comment_plain_text": hx.Str(mode="output", view={"label": "Comment", "multiline": True}),
                "min": hx.Float(mode="output", view={"label": "Min"}),
                "max": hx.Float(mode="output", view={"label": "Max"}),
                "show_comment": hx.Bool(mode="input", default=False, view={"label": "Show?"}),
            }),
            "significant_event_factors": hx.Structure(view={"label": "Significant Event Factors"}, children={
                "value": hx.Float(mode="input", default=0, optionality="optional", view={"label": "Value"}),
                "comment": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Comment", "multiline": True}),
                #"comment_plain_text": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Comment", "multiline": True, "read_only":True}),
                "comment_plain_text": hx.Str(mode="output", view={"label": "Comment", "multiline": True}),
                "min": hx.Float(mode="output", view={"label": "Min"}),
                "max": hx.Float(mode="output", view={"label": "Max"}),
                "show_comment": hx.Bool(mode="input", default=False, view={"label": "Show?"}),
            }),
            "stock_market_factors": hx.Structure(view={"label": "Stock Market Factors"}, children={
                "value": hx.Float(mode="input", default=0, optionality="optional", view={"label": "Value"}),
                "comment": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Comment", "multiline": True}),
                #"comment_plain_text": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Comment", "multiline": True, "read_only":True}),
                "comment_plain_text": hx.Str(mode="output", view={"label": "Comment", "multiline": True}),
                "min": hx.Float(mode="output", view={"label": "Min"}),
                "max": hx.Float(mode="output", view={"label": "Max"}),
                "show_comment": hx.Bool(mode="input", default=False, view={"label": "Show?"}),
            }),
            "derivative": hx.Structure(view={"label": "Derivative"}, children={
                "value": hx.Float(mode="input", default=0, optionality="optional", view={"label": "Value"}),
                "comment": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Comment", "multiline": True}),
                #"comment_plain_text": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Comment", "multiline": True, "read_only":True}),
                "comment_plain_text": hx.Str(mode="output", view={"label": "Comment", "multiline": True}),
                "min": hx.Float(mode="output", view={"label": "Min"}),
                "max": hx.Float(mode="output", view={"label": "Max"}),
                "show_comment": hx.Bool(mode="input", default=False, view={"label": "Show?"}),
            }),
            "regulatory": hx.Structure(view={"label": "Regulatory"}, children={
                "value": hx.Float(mode="input", default=0, optionality="optional", view={"label": "Value"}),
                "comment": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Comment", "multiline": True}),
                #"comment_plain_text": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Comment", "multiline": True, "read_only":True}),
                "comment_plain_text": hx.Str(mode="output", view={"label": "Comment", "multiline": True}),
                "min": hx.Float(mode="output", view={"label": "Min"}),
                "max": hx.Float(mode="output", view={"label": "Max"}),
                "show_comment": hx.Bool(mode="input", default=False, view={"label": "Show?"}),
                "old_value": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Value"}),
            }),
            "ma": hx.Structure(view={"label": "M&A"}, children={
                "comment": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Comment", "multiline": True}),
                #"comment_plain_text": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Comment", "multiline": True, "read_only":True}),
                "comment_plain_text": hx.Str(mode="output", view={"label": "Comment", "multiline": True}),
                "info": hx.Str(mode="output", view={"label": "None"}),
                "show_comment": hx.Bool(mode="input", default=False, view={"label": "Show?"}),
                "old_value": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Value"}),
            })
            # "freq_adj_factor": hx.Structure(view={"label": "Frequency Adjustment Factor"}, children={
            #     "value": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Value"}),
            #     "comment": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Comment"}),
            #     "min": hx.Float(mode="output", view={"label": "Min"}),
            #     "max": hx.Float(mode="output", view={"label": "Max"}),
            # }), # Uncomment if want total in table
        })
    })

#### Core technical premium ####
    # Fields for the technical premium for each option to appear at the top of the page
    for i in range(1, const.max_layers + 1):
        path1 = "technical_premium_" + str(i)
        path2 = "show_tech_prem_" + str(i)
        label = "Option " + str(i) + ": Technical Premium"

        cds.extend_node_rater_defined("cds", {
            path1 : hx.Float(mode="output", optionality="optional", view={"label": label, "format": {"thousandSeparated": True, "mantissa": 0}}),
            path2 : hx.Bool(mode="output", optionality="optional")
        })

#### Override to output ####
    cds.override_node_properties("cds/layers/limit", {"mode":"output",'async_input':['generate_tags_cuap', 'generate_tags_twice']})
    cds.override_node_properties("cds/layers/excess", {"mode":"output",'async_input':['generate_tags_cuap', 'generate_tags_twice']})
    cds.override_node_properties("cds/layers/deductible", {"mode":"output",'async_input':['generate_tags_cuap', 'generate_tags_twice']})
    cds.override_node_properties("cds/layers/aggregate_limit", {"mode":"output"})
    cds.override_node_properties("cds/layers/aggregate_excess", {"mode":"output"})
    cds.override_node_properties("cds/layers/aggregate_deductible", {"mode":"output"})
    cds.override_node_properties("cds/layers/premium", {"mode":"output"})
    # Need to add the async input here as it is in one of the rate change buckets
    cds.override_node_properties("cds/layers/brokerage", {"mode":"output", "view": {"format": {"output": "percent", "mantissa": 1}}, 'async_input':['rarc_task']})


    # cds.extend_node_rater_defined("cds/layers/coverages/abc", {
    #     "selected": hx.Bool(mode="input", view={"label":"Selected"})
    # })
    # cds.extend_node_rater_defined("cds/layers/coverages/side_a", {
    #     "selected": hx.Bool(mode="input", view={"label":"Selected"})
    # })

#### Formats, labels and multiline ####
    cds.override_node_properties("cds/frequency/sca_freq_override_comment", {"view": {"multiline": True}})
    
    cds.override_node_properties("cds/layers/coverages/abc/quoted_market_share", {"view": {"format": utils.thousands_format(0)}})
    cds.override_node_properties("cds/layers/coverages/side_a/quoted_market_share", {"view": {"format": utils.thousands_format(0)}})
    cds.override_node_properties("cds/layers/coverages/abc/ma_retention", {"default": 0, "view": {"format": utils.thousands_format(0)}})
    cds.override_node_properties("cds/layers/coverages/abc/at_cost_75", {"view": {"format": utils.thousands_format(0)}})
    cds.override_node_properties("cds/layers/coverages/abc/incl_dimissals_75", {"view": {"format": utils.thousands_format(0)}})
    cds.override_node_properties("cds/layers/coverages/abc/elr", {"view": {"format": {"output": "percent", "mantissa": 1}}})
    cds.override_node_properties("cds/layers/coverages/side_a/elr", {"view": {"format": {"output": "percent", "mantissa": 1}}})

    cds.override_node_properties("cds/layers/coverages/side_a/tower", {"default": 0, "view": {"format": utils.thousands_format(0)},'async_input':['generate_tags_cuap', 'generate_tags_twice']})
    cds.override_node_properties("cds/layers/coverages/side_a/total_excess", {"view": {"format": utils.thousands_format(0)}})
    cds.override_node_properties("cds/layers/coverages/side_a/director_limit", {"default": 0, "view": {"format": utils.thousands_format(0)}})
    cds.override_node_properties("cds/layers/coverages/side_a/brokerage", {"optionality": "optional", "default": 0})

    cds.override_node_properties("cds/layers/coverages/abc/excess",{"default": 0})
    cds.override_node_properties("cds/layers/coverages/abc/deductible",{"default": 0})
    cds.override_node_properties("cds/layers/coverages/abc/brokerage", {"optionality": "optional", "default": 0})

    cds.override_node_properties("cds/layers/ei_limit", {"view": {"format": utils.thousands_format(0)}})
    cds.override_node_properties("cds/layers/ei_price", {"view": {"format": utils.thousands_format(0)}})

    cds.override_node_properties("cds/layers/coverages/abc/premium", {"view": {"label": "Gross Quoted Premium"}})
    cds.override_node_properties("cds/layers/coverages/side_a/premium", {"view": {"label": "Gross Quoted Premium"}})

    cds.override_node_properties("cds/bridge_premium", {"view": {"format": utils.thousands_format(0)}})
    cds.override_node_properties("cds/bridge_comment", {"view": {"multiline": True}})

    cds.override_node_properties("cds/standard_fields/rating_methodology",{"mode": "output", "default": hx.UNDEFINED, "default_index": hx.UNDEFINED, "options": hx.UNDEFINED, "options_table": hx.UNDEFINED, "async_input": ["rarc_task"], "view": {"label": "Public D&O / Private D&O"}})
##### create structure to hold the labels #####
def sch_pricing_modifier_labels():
    return  {
                "modifier_labels": hx.Structure(children={
                "management_corp_gov": hx.Str(mode="output"),
                "business_financial_model_factors": hx.Str(mode="output"),
                "significant_event_factors": hx.Str(mode="output"),
                "stock_market_factors": hx.Str(mode="output"),
                "regulatory": hx.Str(mode="output"),
                "derivative": hx.Str(mode="output")
                })
            }