"""Create a hardcoded all-input copy of data_schema_static.py.

Run this script from the model root or from this folder:

    python data_schema/all_input_schema/generate_hardcoded_all_inputs.py

It writes ``data_schema_static_all_inputs_hardcoded.py`` in the same folder.
The source ``data_schema_static.py`` is left unchanged.

Output value nodes are converted to input value nodes using these defaults:

- hx.Str: default=""
- hx.Bool: default=False
- hx.Int: default=0
- hx.Float: default=0
- hx.Date: default="1970-01-01"

Output List and Triangle nodes are converted to input mode. List and Triangle
nodes do not receive scalar defaults.

The top-level ``hx_core`` section is excluded from conversion and is copied as-is.
"""

from pathlib import Path
import re


FOLDER = Path(__file__).resolve().parent
SOURCE = FOLDER / "data_schema_static.py"
TARGET = FOLDER / "data_schema_static_all_inputs_hardcoded.py"

DEFAULTS_BY_TYPE = {
    "Str": 'default=""',
    "Bool": "default=False",
    "Int": "default=0",
    "Float": "default=0",
    "Date": 'default="1970-01-01"',
}

GENERATED_FILE_GUARD_PATTERN = re.compile(
    r'^raise Exception\("""This file is generated\n\n'
    r'Do not edit manually as all of the changes will be lost\.\n'
    r'This is the static version of your Data Schema that will allow easier debugging\.\n'
    r'"""\)\n\n',
)

OUTPUT_VALUE_NODE_PATTERN = re.compile(
    r'hx\.(?P<node_type>Str|Bool|Int|Float|Date)\(mode="output"'
)

HX_CORE_START_PATTERN = re.compile(r'^\s*"hx_core":\s+hx\.Structure\(')
HX_CORE_END_PATTERN = re.compile(r'^\s*},\s*view=\{"label":\s*"Hx Core"\}\),')


def _convert_output_value_node(match):
    """Convert one output value-node constructor start to input with a default."""
    node_type = match.group("node_type")
    return f'hx.{node_type}(mode="input", {DEFAULTS_BY_TYPE[node_type]}'


def _convert_output_modes(line):
    """Convert output modes in a single schema source line."""
    line = OUTPUT_VALUE_NODE_PATTERN.sub(_convert_output_value_node, line)
    line = line.replace('hx.List(mode="output"', 'hx.List(mode="input"')
    line = line.replace('hx.Triangle(mode="output"', 'hx.Triangle(mode="input"')
    return line


def _convert_output_modes_except_hx_core(source_text):
    """Convert output modes, preserving the top-level hx_core section as-is."""
    converted_lines = []
    in_hx_core = False

    for line in source_text.splitlines(keepends=True):
        if HX_CORE_START_PATTERN.match(line):
            in_hx_core = True
            converted_lines.append(line)
            continue

        if in_hx_core:
            converted_lines.append(line)
            if HX_CORE_END_PATTERN.match(line):
                in_hx_core = False
            continue

        converted_lines.append(_convert_output_modes(line))

    return "".join(converted_lines)


def build_all_input_schema_text(source_text):
    """Return a hardcoded copy of source_text with output nodes changed to input.

    This function performs the conversion in memory. It removes the generated
    file exception guard, converts output value nodes to input nodes with the
    default values above, and converts output List/Triangle nodes to input mode.
    The top-level hx_core section is copied unchanged.
    """
    converted_text = GENERATED_FILE_GUARD_PATTERN.sub("", source_text, count=1)
    converted_text = _convert_output_modes_except_hx_core(converted_text)

    header = (
        '"""Hardcoded all-input copy generated from data_schema_static.py.\n\n'
        'Generated by generate_hardcoded_all_inputs.py.\n'
        'The original data_schema_static.py file is unchanged.\n'
        'The top-level hx_core section is preserved unchanged.\n'
        'Do not use this as the live schema source unless you intentionally want an all-input static schema copy.\n'
        '"""\n\n'
    )
    return header + converted_text


def create_hardcoded_all_input_copy(source_path=SOURCE, target_path=TARGET):
    """Create the hardcoded all-input copy and return the result file path.

    Parameters
    ----------
    source_path:
        Path to the generated ``data_schema_static.py`` source file.
    target_path:
        Path where the hardcoded all-input copy should be written.
    """
    source_path = Path(source_path)
    target_path = Path(target_path)

    source_text = source_path.read_text()
    target_text = build_all_input_schema_text(source_text)

    target_path.write_text(target_text)
    return target_path


def main():
    """Executable entry point."""
    result_path = create_hardcoded_all_input_copy()
    print(result_path)


if __name__ == "__main__":
    main()
