import hx_data_schema as hx
from data_schema.sch_z_utilities import thousands_format
from data_schema.sch_z_utilities import percent_format
from data_schema.sch_z_utilities import integer_format

def sch_experience_rating(cds):
    cds.extend_node_rater_defined(f"cds", {
        "bi_masking": hx.Bool(mode="output"),
        "manual_masking": hx.Bool(mode="output"),
        "detailed_masking" :hx.Bool(mode="output"),
        "fetch_bi_task_status_policy" :hx.Str(mode="output", async_output=["fetch_bi_data_task","bi_intelligence_fetch_task"]),
        "fetch_bi_task_status_claims" :hx.Str(mode="output", async_output=["fetch_bi_data_task","bi_intelligence_fetch_task"]),

        "experience_final_selections_model": hx.Structure(view = {"label":"Model"}, children = {
            "gn_ulr" :hx.Float(mode="output", view = {"label":"ULR (GN)", "format":percent_format(2)}),
            "gn_ulr_expiry" :hx.Float(mode="output", async_output=["expiring_policy_fetch_task", "start_renewal_task"], view = {"label":"ULR (GN) (Expiry)", "format":percent_format(2)}),
            "ly_prem" :hx.Float(mode="output", view = {"label":"ly_prem", "format":thousands_format()}),
            "exp_weight" :hx.Float(mode="output", view = {"label":"Exp. Weight", "format":percent_format(2)}),
        }),
        "experience_final_selections_uw": hx.Structure(view = {"label":"UW Selected"}, children = {
            "gn_ulr" :hx.Float(mode="input", default = 0.0, view = {"label":"ULR (GN)", "format":percent_format(2)}),
            "gn_ulr_expiry" :hx.Float(mode="output", async_output=["expiring_policy_fetch_task", "start_renewal_task"], view = {"label":"ULR (GN) (Expiry)", "format":percent_format(2)}),
            "exp_weight" :hx.Float(mode="output", view = {"label":"Exp. Weight", "format":percent_format(2)}),
        }),

        "experience_lr_summary_list" : hx.List(mode = "output", children = {
            "yoa": hx.Float(mode = "output", view = {"label":"YOA", "format":integer_format()}),
            "gnwp": hx.Float(mode = "output", view = {"label":"GNWP", "format":thousands_format()}),
            "ilr": hx.Float(mode = "output", view = {"label":"ILR", "format":percent_format(2)}),
            "ulr": hx.Float(mode = "output", view = {"label":"ULR", "format":percent_format(2)}),
            "ulr_inf": hx.Float(mode = "output", view = {"label":"ULR Inf / RC", "format":percent_format(2)}),
        }),
        "experience_lr_summary_subtotal_1" : hx.Structure(view = {"label":"Total"},children = {
            "gnwp": hx.Float(mode = "output", view = {"label":"GNWP", "format":thousands_format()}),
            "ilr": hx.Float(mode = "output", view = {"label":"ILR", "format":percent_format(2)}),
            "ulr": hx.Float(mode = "output", view = {"label":"ULR", "format":percent_format(2)}),
            "ulr_inf": hx.Float(mode = "output", view = {"label":"ULR Inf / RC", "format":percent_format(2)}),
        }),
        "experience_lr_summary_subtotal_2" : hx.Structure(view = {"label":"Total excl. last"}, children = {
            "gnwp": hx.Float(mode = "output", view = {"label":"GNWP", "format":thousands_format()}),
            "ilr": hx.Float(mode = "output", view = {"label":"ILR", "format":percent_format(2)}),
            "ulr": hx.Float(mode = "output", view = {"label":"ULR", "format":percent_format(2)}),
            "ulr_inf": hx.Float(mode = "output", view = {"label":"ULR Inf / RC", "format":percent_format(2)}),
        }),
        "experience_top_10_claims_bi" : hx.List(mode = "output", children = {
            "yoa": hx.Float(mode = "output", view = {"label":"YOA", "format":integer_format()}),
            "claim_ref": hx.Str(mode = "output", view = {"label":"Claim Reference"}),
            "outstanding": hx.Float(mode = "output", view = {"label":"O/S", "format":thousands_format()}),
            "incurred": hx.Float(mode = "output", view = {"label":"Incurred", "format":thousands_format()}),
            "description": hx.Str(mode = "output", view = {"label":"Description"}),
        }),
        "experience_gnwp_summary" : hx.List(mode = "output", children = {
            "yoa": hx.Float(mode = "output", view = {"label":"YOA", "format":integer_format()}),
            "gnwp": hx.Float(mode = "output", view = {"label":"GNWP", "format":thousands_format()}),
            "rate_change": hx.Float(mode = "output", view = {"label":"Rate Change", "format":percent_format(2)}),
            "rate_change_index": hx.Float(mode = "output", view = {"label":"Rate Change Index", "format":percent_format(2)}),
            "gnwp_onlvl": hx.Float(mode = "output", view = {"label":"On-Level GWNP", "format":thousands_format()}),
        }),
        "experience_attr_projection" : hx.List(mode = "output", children = {
            "yoa": hx.Float(mode = "output", view = {"label":"YOA", "format":integer_format()}),
            "incurred": hx.Float(mode = "output", view = {"label":"Inc.", "format":thousands_format()}),
            "dev_factor": hx.Float(mode = "output", view = {"label":"Dev\nFactor", "format":percent_format(0)}),
            "ielr": hx.Float(mode = "output", view = {"label":"IELR", "format":percent_format(0)}),
            "ultimate": hx.Float(mode = "output", view = {"label":"Ult. Attr.\nClaims", "format":thousands_format()}),
        }),
        "experience_large_projection" : hx.List(mode = "output", children = {
            "yoa": hx.Float(mode = "output", view = {"label":"YOA", "format":integer_format()}),
            "ll_avg_lr": hx.Float(mode = "output", view = {"label":"Avg. LL LR", "format":percent_format(2)}),
            "ll_assumption": hx.Float(mode = "output", view = {"label":"LL\nAssump.", "format":percent_format(2)}),
            "ll_weighted": hx.Float(mode = "output", view = {"label":"LL\nWeighted", "format":percent_format(2)}),
            "ultimate": hx.Float(mode = "output", view = {"label":"Ult. Lrg.\nClaims", "format":thousands_format()}),
        }),
        "experience_cat_projection" : hx.List(mode = "output", children = {
            "yoa": hx.Float(mode = "output", view = {"label":"YOA", "format":integer_format()}),
            "cat_incurred": hx.Float(mode = "output", view = {"label":"Incurred", "format":thousands_format()}),
            "cat_average": hx.Float(mode = "output", view = {"label":"Avg. Cat", "format":thousands_format()}),
            "cat_rms": hx.Float(mode = "output", view = {"label":"RMS\nImplied", "format":thousands_format()}),
            "ultimate": hx.Float(mode = "output", view = {"label":"Ult. Cat\nClaims", "format":thousands_format()}),
        }),
        "experience_ult_claims" : hx.List(mode = "input",default_element_count=10, children = {
            "yoa": hx.Float(mode = "output", view = {"label":"YOA", "format":integer_format()}),
            "ult_incurred": hx.Float(mode = "output", view = {"label":"Ult.\nIncurred", "format":thousands_format()}),
            "inf_index": hx.Float(mode = "output", view = {"label":"Infl Index", "format":percent_format(0)}),
            "ult_incurred_inf": hx.Float(mode = "output", view = {"label":"Ult. Inc\n(Inf)", "format":thousands_format()}),
            "ulr": hx.Float(mode = "output", view = {"label":"ULR", "format":percent_format(0)}),
            "include": hx.Bool(mode = "input", default = True, view = {"label":"Include?", "format":thousands_format()}),
        }),
        "experience_lr_summaries" : hx.List(mode = "output", children = {
            "yoa": hx.Float(mode = "output", view = {"label":"YOA", "format":integer_format()}),
            "ilr": hx.Float(mode = "output", view = {"label":"ILR", "format":percent_format(2)}),
            "ulr": hx.Float(mode = "output", view = {"label":"ULR", "format":percent_format(2)}),
        }),
        "experience_rms_defaults": hx.Structure(children = {
            "rms_cat_el" : hx.Float(mode = "output", view = {"label": "RMS/Cat EL", "format":thousands_format()}),
            "rms_cat_prem" : hx.Float(mode = "output", view = {"label": "RMS/Cat Prem", "format":thousands_format()}),
            "rms_cat_lr" : hx.Float(mode = "override", view = {"label": "RMS/Cat LR", "format":percent_format(2)}),
        }),
        "experience_gnwp_summary_manual" : hx.List(mode = "input",default_element_count=10, children = {
            "yoa": hx.Float(mode = "output", view = {"label":"YOA", "format":integer_format()}),
            "gnwp": hx.Float(mode = "input",default = 0.0 ,view = {"label":"GNWP", "format":thousands_format()}),
            "rate_change": hx.Float(mode = "input",default=1.0 ,view = {"label":"Rate\nChange", "format":percent_format(2)}),
            "rate_change_index": hx.Float(mode = "output", view = {"label":"Rate Change Index", "format":percent_format(2)}),
            "gnwp_onlvl": hx.Float(mode = "output", view = {"label":"On-Level\nGWNP", "format":thousands_format()}),
        }),
        "experience_attr_projection_manual" : hx.List(mode = "input",default_element_count=10,  children = {
            "yoa": hx.Float(mode = "output", view = {"label":"YOA", "format":integer_format()}),
            "total_incurred": hx.Float(mode = "input",default = 0.0 , view = {"label":"Total Inc", "format":thousands_format()}),
            "large_cat": hx.Float(mode = "input",default = 0.0 ,view = {"label":"Known\nLarge/Cat", "format":thousands_format()}),
            "incurred": hx.Float(mode = "output", view = {"label":"Incurred", "format":thousands_format()}),
            "dev_factor": hx.Float(mode = "output", view = {"label":"Dev Factor", "format":percent_format(2)}),
            "ielr": hx.Float(mode = "output", view = {"label":"IELR", "format":percent_format(2)}),
            "ultimate": hx.Float(mode = "output", view = {"label":"Ult. Attr.\nClaims", "format":thousands_format()}),
        }),
        "experience_large_projection_manual" : hx.List(mode = "input",default_element_count=10,  children = {
            "yoa": hx.Float(mode = "output", view = {"label":"YOA", "format":integer_format()}),
            "ll_assumption": hx.Float(mode = "output", view = {"label":"LL Assump.", "format":percent_format(2)}),
            "ll_uw_view": hx.Float(mode = "input",default = 0.0, view = {"label":"UW View", "format":percent_format(2)}),
            "ll_selected": hx.Float(mode = "output", view = {"label":"Selected", "format":percent_format(2)}),
            "ultimate": hx.Float(mode = "output", view = {"label":"Ult. Lrg.\nClaims", "format":thousands_format()}),
        }),
        "experience_cat_projection_manual" : hx.List(mode = "input",default_element_count=10,  children = {
            "yoa": hx.Float(mode = "output", view = {"label":"YOA", "format":integer_format()}),
            "cat_uw_view": hx.Float(mode = "input",default=0.0, view = {"label":"UW View", "format":percent_format(2)}),
            "cat_bp": hx.Float(mode = "output", view = {"label":"BP Cat", "format":percent_format(2)}),
            "cat_rms": hx.Float(mode = "output", view = {"label":"RMS\nImplied", "format":percent_format(2)}),
            "ultimate": hx.Float(mode = "output", view = {"label":"Ult. Cat\nClaims", "format":thousands_format()}),
        }),
        "experience_ult_claims_manual" : hx.List(mode = "input",default_element_count=10, children = {
            "yoa": hx.Float(mode = "output", view = {"label":"YOA", "format":integer_format()}),
            "ult_incurred": hx.Float(mode = "output", view = {"label":"Ult. Incurred", "format":thousands_format()}),
            "inf_index": hx.Float(mode = "output", view = {"label":"Infl Index", "format":percent_format(0)}),
            "ult_incurred_inf": hx.Float(mode = "output", view = {"label":"Ult. Inc.\nInflated", "format":thousands_format()}),
            "ulr": hx.Float(mode = "output", view = {"label":"ULR", "format":percent_format(0)}),
            "include": hx.Bool(mode = "input",default=True, view = {"label":"Include?", "format":thousands_format()}),
        }),
        "experience_lr_summaries_manual" : hx.List(mode = "output", children = {
            "yoa": hx.Float(mode = "output", view = {"label":"YOA", "format":integer_format()}),
            "ilr": hx.Float(mode = "output", view = {"label":"ILR", "format":percent_format(2)}),
            "ulr": hx.Float(mode = "output", view = {"label":"ULR", "format":percent_format(2)}),
        }),
        "experience_detailed" : hx.Structure(children= {
            "trifocus" : hx.Str(mode="output",view={"label":"Trifocus"}),
            "bp_rc" : hx.Float(mode="output",view={"label":"Business Plan Rate Change","format":percent_format(2)}),
            "infl" : hx.Float(mode="output",view={"label":"Inflation p.a.", "format":percent_format(2)}),
            "ll_threshold" : hx.Float(mode="output",async_input=["fetch_bi_data_task","bi_intelligence_fetch_task"],view={"label":"LL Threshold","format":thousands_format()}),
            "ll_load" : hx.Float(mode="output",view={"label":"Business Plan LL Load","format":percent_format(2)}),
            "cat_load" : hx.Float(mode="output",view={"label":"Business Plan Cat Load", "format":percent_format(2)}),
        }),
        "experience_loss_ratio_summary_chart": hx.List(mode = "output", view = {"label":"LR Summary"}, children = {
            "yoa" : hx.Float(mode="output",view={"label":"Year of Account", "format":integer_format()}),
            "ulr" : hx.Float(mode="output", view={"label": "ULR", "chart": {"series_type": "line", "series_axis": "secondary"}}),
            "ilr" : hx.Float(mode="output", view={"label": "ILR", "chart": {"series_type": "line", "series_axis": "secondary"}}),
            "sel_ulr" : hx.Float(mode="output", view={"label": "Sel. ULR", "chart": {"series_type": "line", "series_axis": "secondary"}}),
            "uw_ulr" : hx.Float(mode="output", view={"label": "UW ULR", "chart": {"series_type": "line", "series_axis": "secondary"}}),
            "gnwp" : hx.Float(mode="output",view={"label":"GNWP", "format":thousands_format()}),
        }),
        "experience_loss_ratio_type_chart": hx.List(mode = "output", view = {"label":"LR Type"}, children = {
            "yoa" : hx.Float(mode="output",view={"label":"Year of Account", "format":integer_format()}),
            "attr_ulr" : hx.Float(mode="output",view={"label":"Attritional ULR", "format":percent_format()}),
            "large_ulr" : hx.Float(mode="output",view={"label":"Large ULR", "format":percent_format()}),
            "cat_ulr" : hx.Float(mode="output",view={"label":"Cat ULR", "format":percent_format()}),
        }),

        "bi_policy_data": hx.List(mode = "output", async_output=["fetch_bi_data_task", "bi_intelligence_fetch_task"], children = {
            "PolicyReference" : hx.Str(mode="output", async_output=["fetch_bi_data_task", "bi_intelligence_fetch_task"]),
            "SectionReference" : hx.Str(mode="output", async_output=["fetch_bi_data_task", "bi_intelligence_fetch_task"]),
            "YOA" : hx.Int(mode="output", async_output=["fetch_bi_data_task", "bi_intelligence_fetch_task"]),
            "CoverageName" : hx.Str(mode="output", async_output=["fetch_bi_data_task", "bi_intelligence_fetch_task"]),
            "TriFocusName" : hx.Str(mode="output", async_output=["fetch_bi_data_task", "bi_intelligence_fetch_task"]),
            "Division" : hx.Str(mode="output", async_output=["fetch_bi_data_task", "bi_intelligence_fetch_task"]),
            "RateChangeDivisor" : hx.Float(mode="output", async_output=["fetch_bi_data_task", "bi_intelligence_fetch_task"]),
            "SettlementCurrency" : hx.Str(mode="output", async_output=["fetch_bi_data_task", "bi_intelligence_fetch_task"]),
            "WrittenOrEstimatPrem" : hx.Float(mode="output", async_output=["fetch_bi_data_task", "bi_intelligence_fetch_task"]),
            "TotalIncurred" : hx.Float(mode="output", async_output=["fetch_bi_data_task", "bi_intelligence_fetch_task"]),
            "RateChangeReformat" : hx.Float(mode="output", async_output=["fetch_bi_data_task", "bi_intelligence_fetch_task"]),
            "WEPOnLevel" : hx.Float(mode="output", async_output=["fetch_bi_data_task", "bi_intelligence_fetch_task"]),
            "Index" : hx.Str(mode="output", async_output=["fetch_bi_data_task", "bi_intelligence_fetch_task"]),
            "TotalWrittenIfNotSignedMultiplier" : hx.Float(mode="output", async_output=["fetch_bi_data_task", "bi_intelligence_fetch_task"]),
            "TotalWEP" : hx.Float(mode="output", async_output=["fetch_bi_data_task", "bi_intelligence_fetch_task"]),
        }),
        "bi_claims_data": hx.List(mode = "output", async_output=["fetch_bi_data_task", "bi_intelligence_fetch_task"], children = {
            "SectionReference" : hx.Str(mode="output", async_output=["fetch_bi_data_task", "bi_intelligence_fetch_task"], view = {"label" : "Section Reference"}),
            "ClaimReference" : hx.Str(mode="output", async_output=["fetch_bi_data_task", "bi_intelligence_fetch_task"], view = {"label" : "Claim Reference"}),
            "TriFocusName" : hx.Str(mode="output", async_output=["fetch_bi_data_task", "bi_intelligence_fetch_task"], view = {"label" : "Trifocus"}),
            "Division" : hx.Str(mode="output", async_output=["fetch_bi_data_task", "bi_intelligence_fetch_task"], view = {"label" : "Division"}),
            "PolicyYOA" : hx.Int(mode="output", async_output=["fetch_bi_data_task", "bi_intelligence_fetch_task"], view = {"label" : "YOA", "format":integer_format(0)}),
            "PolicyReference" : hx.Str(mode="output", async_output=["fetch_bi_data_task", "bi_intelligence_fetch_task"], view = {"label" : "Policy Reference"}),
            "BeazleyCatCode" : hx.Str(mode="output", async_output=["fetch_bi_data_task", "bi_intelligence_fetch_task"], view = {"label" : "Beazley Cat Code"}),
            "BeazleyCat" : hx.Str(mode="output", async_output=["fetch_bi_data_task", "bi_intelligence_fetch_task"], view = {"label" : "Beazley Cat"}),
            "MarketCatCode" : hx.Str(mode="output", async_output=["fetch_bi_data_task", "bi_intelligence_fetch_task"], view = {"label" : "Market Cat Code"}),
            "MarketCat" : hx.Str(mode="output", async_output=["fetch_bi_data_task", "bi_intelligence_fetch_task"], view = {"label" : "Market Cat"}),
            "HasBeazleyCatCode" : hx.Str(mode="output", async_output=["fetch_bi_data_task", "bi_intelligence_fetch_task"], view = {"label" : "Has Beazley Cat Code"}),
            "BeazleyShareTotalIncurredInUSD" : hx.Float(mode="output", async_output=["fetch_bi_data_task", "bi_intelligence_fetch_task"], view = {"label" : "Beazley Share TI (USD)", "format":thousands_format()}),
            "BeazleyShareTotalOutstandingInUSD" : hx.Float(mode="output", async_output=["fetch_bi_data_task", "bi_intelligence_fetch_task"], view = {"label" : "Beazley Share O/S (USD)", "format":thousands_format()}),
            "CauseOfLoss" : hx.Str(mode="output", async_output=["fetch_bi_data_task", "bi_intelligence_fetch_task"], view = {"label" : "Cause of Loss"}),
            "LargeLossIndicator" : hx.Int(mode="output", async_output=["fetch_bi_data_task", "bi_intelligence_fetch_task"], view = {"label" : "Large Loss Indicator"}),
            "Index" : hx.Str(mode="output", async_output=["fetch_bi_data_task", "bi_intelligence_fetch_task"], view = {"label" : "Index"}),
            "SignedLineMultiplier" : hx.Float(mode="output", async_output=["fetch_bi_data_task", "bi_intelligence_fetch_task"], view = {"label" : "Signed Line", "format":percent_format()}),
            "TotalIncurredInUSD" : hx.Float(mode="output", async_output=["fetch_bi_data_task", "bi_intelligence_fetch_task"], view = {"label" : "100% TI (USD)", "format":thousands_format()}),
        })
    })
    
    cds.extend_node_rater_defined(f"cds/experience_rating", {
        "data_source" :hx.Str(mode="input", default = 'BI', options = ["Manual", "BI"], view = {"label":"Source"}),
        "detailed_view" :hx.Bool(mode="input", default = True, view = {"label":"Detailed?"}),
        "policy_ref" :hx.Str(mode="output", view = {"label":"Policy Reference"}),
        "expiring_policy_ref" :hx.Str(mode="output", async_output = ["expiring_policy_fetch_task", "start_renewal_task"], view = {"label":"Expiry Policy Ref"}),
    })
