name: Issue Closed - All - Model Movement

permissions:
  contents: read
  issues: read

on:
  issues:
    types: [closed]

jobs:

  model_movement_emails:
    if: github.event.issue.state_reason == 'completed' && (contains(github.event.issue.labels.*.name, 'hx_model_movement_dev') || contains(github.event.issue.labels.*.name, 'hx_model_movement_prod'))
    uses: beazley/hyperexponential.rater.shared_workflows/.github/workflows/reusable-all-model-movement-emails.yml@main
    with:
      RESULT: "success"
      MOVEMENT_SOURCE: ${{ contains(github.event.issue.labels.*.name, 'hx_model_movement_dev') && 'DEV' || 'PROD' }}
      TITLE: ${{ github.event.issue.title }}
      ISSUE_NUMBER: ${{ github.event.issue.number }}
    secrets:
      READ_GITHUB_REPO_PAT: ${{ secrets.READ_GITHUB_REPO_PAT }}
      EMAIL_AZURE_AD_CLIENTSECRET: ${{ secrets.EMAIL_AZURE_AD_CLIENTSECRET }}

  rejected_model_movement_emails:
    if: github.event.issue.state_reason == 'not_planned' && (contains(github.event.issue.labels.*.name, 'hx_model_movement_dev') || contains(github.event.issue.labels.*.name, 'hx_model_movement_prod'))
    uses: beazley/hyperexponential.rater.shared_workflows/.github/workflows/reusable-all-rejected-model-movement-emails.yml@main
    with:
      MOVEMENT_SOURCE: ${{ contains(github.event.issue.labels.*.name, 'hx_model_movement_dev') && 'DEV' || 'PROD' }}
      TITLE: ${{ github.event.issue.title }}
      ISSUE_NUMBER: ${{ github.event.issue.number }}
    secrets:
      READ_GITHUB_REPO_PAT: ${{ secrets.READ_GITHUB_REPO_PAT }}
      EMAIL_AZURE_AD_CLIENTSECRET: ${{ secrets.EMAIL_AZURE_AD_CLIENTSECRET }}
