name: Manual - All - Commence Datafix

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        description: 'The environment for which the datafix will be applied to.'
        required: true
        type: choice
        options:
        - us-dev
        - us-tst
        - us-pre-prod
        - us-prd
      JIRA_NUMBER:
        default: 'RT-'
        description: 'The JIRA number relating to this datafix.'
        required: true
        type: string
      RELEASE_NOTES:
        description: 'Release notes'
        required: true
        type: string

jobs:

  run_datafix:
    uses: beazley/hyperexponential.rater.shared_workflows/.github/workflows/reusable-all-run_datafix.yml@main
    with:
      ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
      JIRA_NUMBER: ${{ inputs.JIRA_NUMBER }}
      RELEASE_NOTES: ${{ inputs.RELEASE_NOTES }}
    secrets:
      HX_AZURE_AD_CLIENTSECRET: ${{ secrets.HX_AZURE_AD_CLIENTSECRET }}
      READ_GITHUB_REPO_PAT: ${{ secrets.READ_GITHUB_REPO_PAT }}
      SERVICE_NOW_CLIENT_ID: ${{ secrets.SERVICE_NOW_CLIENT_ID }}
      SERVICE_NOW_CLIENT_SECRET: ${{ secrets.SERVICE_NOW_CLIENT_SECRET }}