raise Exception("""This file is generated

Do not edit manually as all of the changes will be lost.
This is the static version of your Data Schema that will allow easier debugging.
""")

import hx_data_schema as hx


@hx.data_schema
def hx_calculation_legacy_initial_premium():
    return hx.Structure(children={
        "hx_core": hx.Structure(children={
            "inception_date": hx.Date(default="2018-01-01", mode="input", view={"label": "Inception Date"}),
            "expiry_date": hx.Date(default="2018-12-31", mode="input", view={"label": "Expiry Date"}),
            "model_premium": hx.Float(mode="output", view={"label": "Model Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
            "charged_premium": hx.Float(mode="output", view={"label": "Charged Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
            "premium_currency": hx.Str(mode="output", view={"label": "Premium Currency"}),
            "ulr": hx.Float(mode="output", view={"label": "ULR", "format": {"output": "percent", "mantissa": 1}}),
            "class_code": hx.Str(mode="output", view={"label": "Class Code"}),
        }, view={"label": "Hx Core"}),
        "cds": hx.Structure(view={"label": "cds"}, children={
            "key_industry": hx.Structure(view={"label": "Key Industry"}, children={
                "code_type": hx.Str(mode="input", default=None, optionality="optional", options=["NAICS", "SIC_USA", "SIC_UK", "UW Defined"], view={"label": "Industry Code Type"}),
                "code": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Industry Code"}),
                "code_name": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Industry Code Name"}),
            }),
            "standard_fields": hx.Structure(view={"label": "Standard Fields"}, children={
                "insured_name": hx.Str(mode="input", default=None, allow_custom_value=True, async_input=["start_renewal_task"], optionality="optional", options_column="insured", options_table="lst_insureds", view={"label": "Insured Name"}),
                "broker": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Broker Name"}),
                "expiry_date": hx.Date(mode="output", view={"label": "Expiry Date"}),
                "inception_date": hx.Date(mode="output", view={"label": "Inception Date"}),
                "insured_country": hx.Str(mode="input", default=None, optionality="optional", options=["", "AND", "ARE", "AFG", "ATG", "AIA", "ALB", "ARM", "AGO", "ATA", "ARG", "ASM", "AUT", "AUS", "ABW", "ALA", "AZE", "BIH", "BRB", "BGD", "BEL", "BFA", "BGR", "BHR", "BDI", "BEN", "BLM", "BMU", "BRN", "BOL", "BES", "BRA", "BHS", "BTN", "BVT", "BWA", "BLR", "BLZ", "CAN", "CCK", "COD", "CAF", "COG", "CHE", "CIV", "COK", "CHL", "CMR", "CHN", "COL", "CRI", "CUB", "CPV", "CUW", "CXR", "CYP", "CZE", "DEU", "DJI", "DNK", "DMA", "DOM", "DZA", "ECU", "EST", "EGY", "ESH", "ERI", "ESP", "ETH", "FIN", "FJI", "FLK", "FSM", "FRO", "FRA", "GAB", "GBR", "GRD", "GEO", "GUF", "GGY", "GHA", "GIB", "GRL", "GMB", "GIN", "GLP", "GNQ", "GRC", "SGS", "GTM", "GUM", "GNB", "GUY", "HKG", "HMD", "HND", "HRV", "HTI", "HUN", "IDN", "IRL", "ISR", "IMN", "IND", "IOT", "IRQ", "IRN", "ISL", "ITA", "JEY", "JAM", "JOR", "JPN", "KEN", "KGZ", "KHM", "KIR", "COM", "KNA", "PRK", "KOR", "KWT", "CYM", "KAZ", "LAO", "LBN", "LCA", "LIE", "LKA", "LBR", "LSO", "LTU", "LUX", "LVA", "LBY", "MAR", "MCO", "MDA", "MNE", "MAF", "MDG", "MHL", "MKD", "MLI", "MMR", "MNG", "MAC", "MNP", "MTQ", "MRT", "MSR", "MLT", "MUS", "MDV", "MWI", "MEX", "MYS", "MOZ", "NAM", "NCL", "NER", "NFK", "NGA", "NIC", "NLD", "NOR", "NPL", "NRU", "NIU", "NZL", "OMN", "PAN", "PER", "PYF", "PNG", "PHL", "PAK", "POL", "SPM", "PCN", "PRI", "PSE", "PRT", "PLW", "PRY", "QAT", "REU", "ROU", "SRB", "RUS", "RWA", "SAU", "SLB", "SYC", "SDN", "SWE", "SGP", "SHN", "SVN", "SJM", "SVK", "SLE", "SMR", "SEN", "SOM", "SUR", "SSD", "STP", "SLV", "SXM", "SYR", "SWZ", "TCA", "TCD", "ATF", "TGO", "THA", "TJK", "TKL", "TLS", "TKM", "TUN", "TON", "TUR", "TTO", "TUV", "TWN", "TZA", "UKR", "UGA", "UMI", "USA", "URY", "UZB", "VAT", "VCT", "VEN", "VGB", "VIR", "VNM", "VUT", "WLF", "WSM", "YEM", "MYT", "ZAF", "ZMB", "ZWE", "ATB", "BYS", "CTE", "CSK", "DHY", "ATN", "AFI", "ATF", "DDR", "GEL", "JTN", "MID", "NHB", "PCI", "PCZ", "SKM", "RHO", "PUS", "HVO", "VDR", "WAK", "YMD"], view={"label": "Insured Country"}),
                "insured_postal_code": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Insured Postal Code"}),
                "insured_state_or_province": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Insured State or Province"}),
                "is_admitted_or_surplus": hx.Str(mode="input", default=None, optionality="optional", options=["Admitted", "Surplus"], view={"label": "Is Admitted Or Surplus"}),
                "is_free_trade_zone": hx.Bool(mode="input", default=False, optionality="required", view={"label": "Is Free-Trade Zone"}),
                "is_renewal": hx.Bool(mode="input", default=False, optionality="required", view={"label": "Is Renewal"}),
                "underwriter": hx.Str(mode="input", default=None, async_input=["generate_uw_doc"], optionality="optional", options_column="underwriter", options_table="lst_underwriters", view={"label": "Underwriter", "options": {"read_only": {"read_only": True}}}),
                "policy_reference": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Policy Reference"}),
                "facility_reference": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Facility Reference"}),
                "benchmark_class": hx.Str(mode="output", optionality="optional", view={"label": "Benchmark Class"}),
                "uw_rationale": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Underwriter Rationale"}),
                "trifocus": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Trifocus"}),
                "rating_methodology": hx.Str(mode="input", default="Rater", options=["Rater", "Case Priced"], view={"label": "Rater Priced or Case Priced?"}),
                "is_case_priced": hx.Bool(mode="output", view={"label": "Is Case Priced"}),
                "is_rater_priced": hx.Bool(mode="output", view={"label": "Is Rater Priced"}),
            }),
            "layers": hx.List(mode="input", max_element_count=10, view={"label": "Layers"}, children={
                "limit": hx.Float(mode="input", default=None, async_input=["generate_uw_doc"], optionality="optional", view={"label": "Limit", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "excess": hx.Float(mode="override", async_input=["generate_uw_doc"], optionality="optional", view={"label": "Excess", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "deductible": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Deductible", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "aggregate_limit": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Aggregate Limit", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "aggregate_excess": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Aggregate Excess", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "aggregate_deductible": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Aggregate Deductible", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "currency": hx.Str(mode="input", default=None, optionality="optional", options=["ADP", "AFA", "AON", "AOR", "ATS", "AZM", "BEF", "BGL", "BRE", "BUK", "BYB", "BYR", "CSD", "CSK", "CYP", "DDM", "DEM", "ECS", "EEK", "ESP", "FIM", "FRF", "GHC", "GRD", "GWP", "HRK", "IEP", "ITL", "LTL", "LUF", "LVL", "MGF", "MRO", "MTL", "MXP", "MZM", "NIC", "NLG", "PES", "PLZ", "PTE", "ROL", "RUR", "SDD", "SDP", "SIT", "SKK", "SRG", "STD", "SUR", "TRL", "UYP", "VEB", "VEF", "XEU", "YUM", "ZMK", "ZRN", "ZRZ", "ZWD", "ZWR", "AED", "AFN", "ALL", "AMD", "ANG", "AOA", "ARS", "AUD", "AWG", "AZN", "BAM", "BBD", "BDT", "BGN", "BHD", "BIF", "BMD", "BND", "BOB", "BOV", "BRL", "BSD", "BTN", "BWP", "BYN", "BZD", "CAD", "CDF", "CHE", "CHF", "CHW", "CLF", "CLP", "CNY", "COP", "COU", "CRC", "CUC", "CUP", "CVE", "CZK", "DJF", "DKK", "DOP", "DZD", "EGP", "ERN", "ETB", "EUR", "FJD", "FKP", "GBP", "GEL", "GHS", "GIP", "GMD", "GNF", "GTQ", "GYD", "HKD", "HNL", "HTG", "HUF", "IDR", "ILS", "INR", "IQD", "IRR", "ISK", "JMD", "JOD", "JPY", "KES", "KGS", "KHR", "KMF", "KPW", "KRW", "KWD", "KYD", "KZT", "LAK", "LBP", "LKR", "LRD", "LSL", "LYD", "MAD", "MDL", "MGA", "MKD", "MMK", "MNT", "MOP", "MRU", "MUR", "MVR", "MWK", "MXN", "MXV", "MYR", "MZN", "NAD", "NGN", "NIO", "NOK", "NPR", "NZD", "OMR", "PAB", "PEN", "PGK", "PHP", "PKR", "PLN", "PYG", "QAR", "RON", "RSD", "RUB", "RWF", "SAR", "SBD", "SCR", "SDG", "SEK", "SGD", "SHP", "SLE", "SLL", "SOS", "SRD", "SSP", "STN", "SVC", "SYP", "SZL", "THB", "TJS", "TMT", "TND", "TOP", "TRY", "TTD", "TWD", "TZS", "UAH", "UGX", "USD", "USN", "UYI", "UYU", "UYW", "UZS", "VED", "VES", "VND", "VUV", "WST", "XAF", "XAG", "XAU", "XBA", "XBB", "XBC", "XBD", "XCD", "XDR", "XOF", "XPD", "XPF", "XPT", "XSU", "XTS", "XUA", "XXX", "YER", "ZAR", "ZMW", "ZWL"], view={"label": "Currency"}),
                "section_reference": hx.Str(mode="input", default=None, async_input=["generate_uw_doc"], optionality="optional", view={"label": "Policy Reference", "options": {"read_only": {"read_only": True}}}),
                "brokerage": hx.Float(mode="output", async_input=["generate_uw_doc"], optionality="optional", view={"label": "Brokerage", "format": {"output": "percent", "mantissa": 1}}),
                "written_line": hx.Float(mode="input", default=1, async_input=["generate_uw_doc"], optionality="required", view={"label": "Q/S", "format": {"output": "percent", "mantissa": 1}, "options": {"read_only": {"read_only": True}}}),
                "premium": hx.Float(mode="input", default=None, async_input=["generate_uw_doc"], optionality="optional", view={"label": "Bound premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "status": hx.Str(mode="input", default=None, async_input=["generate_uw_doc"], optionality="optional", options_column="Status", options_table="table_status", view={"label": "Status", "options": {"input": {"label": "Status"}}}),
                "is_primary_excess": hx.Str(mode="input", default=None, async_input=["generate_uw_doc"], optionality="optional", options=["Primary", "Excess"], view={"label": "Primary or Excess"}),
                "benchmark_premium": hx.Float(mode="output", async_input=["generate_uw_doc"], optionality="optional", view={"label": "Benchmark premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "bpi": hx.Float(mode="output", async_input=["generate_uw_doc"], optionality="optional", view={"label": "BPI%", "format": {"output": "percent", "mantissa": 1}}),
                "bpi_pre_uw_adj": hx.Float(mode="output", optionality="optional", view={"label": "BPI (Pre-UW Adjustment)", "format": {"output": "percent", "mantissa": 1}}),
                "model_premium": hx.Float(mode="output", async_input=["generate_uw_doc"], optionality="optional", view={"label": "Model premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "unity_premium": hx.Float(mode="output", optionality="optional", view={"label": "Gross Unity Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "quoted_premium": hx.Float(mode="input", default=0, async_input=["generate_uw_doc"], optionality="required", view={"label": "Gross Quoted Premium", "format": {"thousandSeparated": True, "mantissa": 0}, "options": {"read_only": {"read_only": True}}}),
                "technical_premium": hx.Float(mode="output", async_input=["generate_uw_doc"], optionality="optional", view={"label": "Technical Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "technical_premium_pre_uw_adj": hx.Float(mode="output", optionality="optional", view={"label": "Gross Technical Premium (Pre-UW Adjustment)", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "technical_premium_net": hx.Float(mode="output", optionality="optional", view={"label": "Net Technical Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "tpi": hx.Float(mode="output", async_input=["generate_uw_doc"], optionality="optional", view={"label": "TPI%", "format": {"output": "percent", "mantissa": 1}}),
                "tpi_pre_uw_adj": hx.Float(mode="output", optionality="optional", view={"label": "TPI (Pre-UW Adjustment)", "format": {"output": "percent", "mantissa": 1}}),
                "pflr_att": hx.Float(mode="output", optionality="optional", view={"label": "Priced-for Loss Ratio (Att)", "format": {"output": "percent", "mantissa": 1}}),
                "pflr_cat": hx.Float(mode="output", optionality="optional", view={"label": "Priced-for Loss Ratio (Cat)", "format": {"output": "percent", "mantissa": 1}}),
                "pflr": hx.Float(mode="output", async_input=["generate_uw_doc"], optionality="optional", view={"label": "Priced-for Loss Ratio", "format": {"output": "percent", "mantissa": 1}}),
                "roc": hx.Float(mode="output", async_input=["generate_uw_doc"], optionality="optional", view={"label": "Return on Capital", "format": {"output": "percent", "mantissa": 1}}),
                "uw_adj_impact": hx.Float(mode="output", async_input=["generate_uw_doc"], optionality="optional", view={"label": "Impact of Underwriting Adjustments", "format": {"output": "percent", "mantissa": 1}}),
                "trifocus": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Trifocus"}),
                "expected_loss_cost": hx.Float(mode="output", async_input=["generate_uw_doc"], optionality="optional", view={"label": "Expected Loss Cost", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "expected_loss_cost_pre_uw_adj": hx.Float(mode="output", optionality="optional", view={"label": "Expected Loss Cost (Pre-UW Ajustment)", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "rate_change": hx.Structure(view={"label": "Rate Change"}, children={
                    "exposure_change": hx.Structure(view={"label": "Exposure Change"}, children={
                        "model_calculated": hx.Float(mode="output", async_output=["rarc_task"], view={"label": "Model %", "format": {"output": "percent", "mantissa": 0}}),
                        "uw_selected": hx.Float(mode="override", view={"label": "UW Selected %", "format": {"output": "percent", "mantissa": 0}}),
                        "comments": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Comment"}),
                    }),
                    "risk_characteristics_change": hx.Structure(view={"label": "Risk Characteristics Change"}, children={
                        "model_calculated": hx.Float(mode="output", async_output=["rarc_task"], view={"label": "Model %", "format": {"output": "percent", "mantissa": 0}}),
                        "uw_selected": hx.Float(mode="override", view={"label": "UW Selected %", "format": {"output": "percent", "mantissa": 0}}),
                        "comments": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Comment"}),
                    }),
                    "limit_change": hx.Structure(view={"label": "Limit Change"}, children={
                        "model_calculated": hx.Float(mode="output", async_output=["rarc_task"], view={"label": "Model %", "format": {"output": "percent", "mantissa": 0}}),
                        "uw_selected": hx.Float(mode="override", view={"label": "UW Selected %", "format": {"output": "percent", "mantissa": 0}}),
                        "comments": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Comment"}),
                    }),
                    "deductible_change": hx.Structure(view={"label": "Deductible Change"}, children={
                        "model_calculated": hx.Float(mode="output", async_output=["rarc_task"], view={"label": "Model %", "format": {"output": "percent", "mantissa": 0}}),
                        "uw_selected": hx.Float(mode="override", view={"label": "UW Selected %", "format": {"output": "percent", "mantissa": 0}}),
                        "comments": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Comment"}),
                    }),
                    "terms_conditions_change": hx.Structure(view={"label": "Terms & Conditions Change"}, children={
                        "model_calculated": hx.Float(mode="output", async_output=["rarc_task"], view={"label": "Model %", "format": {"output": "percent", "mantissa": 0}}),
                        "uw_selected": hx.Float(mode="override", view={"label": "UW Selected %", "format": {"output": "percent", "mantissa": 0}}),
                        "comments": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Comment"}),
                    }),
                    "other_change": hx.Structure(view={"label": "Other Change"}, children={
                        "model_calculated": hx.Float(mode="output", async_output=["rarc_task"], view={"label": "Model %", "format": {"output": "percent", "mantissa": 0}}),
                        "uw_selected": hx.Float(mode="override", view={"label": "UW Selected %", "format": {"output": "percent", "mantissa": 0}}),
                        "comments": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Comment"}),
                    }),
                    "brokerage_change": hx.Structure(view={"label": "Brokerage Change"}, children={
                        "model_calculated": hx.Float(mode="output", async_output=["rarc_task"], view={"label": "Model %", "format": {"output": "percent", "mantissa": 0}}),
                        "uw_selected": hx.Float(mode="override", view={"label": "UW Selected %", "format": {"output": "percent", "mantissa": 0}}),
                        "comments": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Comment"}),
                    }),
                    "rate_change": hx.Structure(view={"label": "Risk Adjusted Rate Change"}, children={
                        "model_calculated": hx.Float(mode="output", view={"label": "Model %", "format": {"output": "percent", "mantissa": 0}}),
                        "uw_selected": hx.Float(mode="output", view={"label": "UW Selected %", "format": {"output": "percent", "mantissa": 0}}),
                        "comments": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Comment"}),
                        "lloyds_limit_attachment_point_change": hx.Float(mode="output", view={"label": "Lloyds's Limit Attachment Point Change", "format": {"output": "percent", "mantissa": 0}}),
                        "lloyds_breadth_of_cover_change": hx.Float(mode="output", view={"label": "Lloyds's Breadth of Cover Change", "format": {"output": "percent", "mantissa": 0}}),
                        "other_factors_change": hx.Float(mode="output", view={"label": "Other Factors Change", "format": {"output": "percent", "mantissa": 0}}),
                    }),
                    "expiring_layer": hx.Int(mode="input", default=1, async_input=["expiring_policy_fetch_task", "rarc_task"], optionality="optional", options=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], view={"label": "Expiring Layer"}),
                    "rebased_expiring_premium": hx.Float(mode="output", async_output=["rarc_task"], view={"label": "Rebased Expiring Premium", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "premium_policy_term_beazley_share": hx.Structure(view={"label": "Premium - Policy Term (Beazley Share)"}, children={
                        "renewal": hx.Float(mode="output", view={"label": "Renewal", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "expiring": hx.Float(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task"], view={"label": "Expiring", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    }),
                    "premium_policy_term_100pct": hx.Structure(view={"label": "Premium - Policy Term (100% Share)"}, children={
                        "renewal": hx.Float(mode="output", view={"label": "Renewal", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "expiring": hx.Float(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task"], view={"label": "Expiring", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    }),
                    "premium_annualized_beazley_share": hx.Structure(view={"label": "Premium - Annualized (Beazley Share)"}, children={
                        "renewal": hx.Float(mode="output", view={"label": "Renewal", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "expiring": hx.Float(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task"], view={"label": "Expiring", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    }),
                    "premium_annualized_100pct": hx.Structure(view={"label": "Premium - Annualized (100% Share)"}, children={
                        "renewal": hx.Float(mode="output", view={"label": "Renewal", "format": {"thousandSeparated": True, "mantissa": 0}}),
                        "expiring": hx.Float(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task"], view={"label": "Expiring", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    }),
                    "expiring_policy_info": hx.Structure(children={
                        "expiring_exposure": hx.Float(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task"]),
                        "expiring_policy_length": hx.Float(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task"]),
                        "expiring_premium": hx.Float(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task"]),
                        "expiring_limit": hx.Float(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task"]),
                        "expiring_deductible": hx.Float(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task"]),
                        "expiring_brokerage": hx.Float(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task"]),
                        "expiring_write_line": hx.Float(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task"]),
                        "expiring_expected_loss": hx.Float(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task"]),
                    }),
                    "total_change": hx.Structure(view={"label": "Total Change dictates change of"}, children={
                        "calculated": hx.Float(mode="output", view={"label": "Model %", "format": {"output": "percent", "mantissa": 0}}),
                        "selected": hx.Float(mode="output", view={"label": "UW Selected %", "format": {"output": "percent", "mantissa": 0}}),
                        "comments": hx.Str(mode="input", default="", view={"label": "Comment"}),
                    }),
                    "simple_rate_change": hx.Float(mode="output", view={"label": "Pure Premium Change / Simple Rate Change", "format": {"output": "percent", "mantissa": 0}}),
                    "risk_adjusted_rate_change": hx.Structure(view={"label": "Underwriter Selected"}, children={
                        "technical": hx.Float(mode="output", view={"label": "Model Risk Adjusted Rate Change", "format": {"output": "percent", "mantissa": 0}}),
                        "technical_net_brokerage": hx.Float(mode="output", view={"format": {"output": "percent", "mantissa": 0}}),
                        "uw_selected": hx.Float(mode="output", view={"label": "UW Selected Risk Adjusted Rate Change", "format": {"output": "percent", "mantissa": 0}}),
                        "uw_selected_net_brokerage": hx.Float(mode="output", view={"label": "UW Selected Risk Adjusted Rate Change", "format": {"output": "percent", "mantissa": 0}}),
                    }),
                    "risk_adjusted_rate_change_case_priced": hx.Structure(view={"label": "Underwriter Selected"}, children={
                        "uw_selected": hx.Float(mode="override", view={"label": "UW Selected Risk Adjusted Rate Change", "format": {"output": "percent", "mantissa": 0}}),
                        "uw_selected_net_brokerage": hx.Float(mode="output", view={"label": "UW Selected Risk Adjusted Rate Change Net Brokerage", "format": {"output": "percent", "mantissa": 0}}),
                        "comments": hx.Str(mode="input", default="", view={"label": "Comment"}),
                    }),
                    "error_message": hx.Str(mode="output"),
                    "temp_storage": hx.Structure(children={
                        "quoted_premium": hx.Float(mode="output", async_output=["rarc_task"]),
                        "benchmark_premium": hx.Float(mode="output", async_output=["rarc_task"]),
                    }),
                }),
                "is_fun_top_up_coverage": hx.Bool(mode="input", default=False, async_input=["generate_uw_doc"], view={"label": "Fundamental Top Up Coverage"}),
                "bpi_case_priced": hx.Float(mode="input", default=0, optionality="required", view={"label": "BPI (Case Priced)", "format": {"output": "percent", "mantissa": 1}}),
                "option_name": hx.Str(mode="input", default=None, async_input=["generate_uw_doc"], optionality="optional", view={"label": "Option name"}),
                "limit_pct": hx.Float(mode="output", async_input=["generate_uw_doc"], view={"label": "Limit %", "format": {"output": "percent", "mantissa": 2}}),
                "excess_pct": hx.Float(mode="override", async_input=["generate_uw_doc"], view={"label": "Excess %", "format": {"output": "percent", "mantissa": 2}}),
                "indicated": hx.Bool(mode="input", default=True, async_input=["generate_uw_doc"], view={"label": "Indicated"}),
                "is_bound": hx.Bool(mode="input", default=False, view={"label": "Bound?"}),
                "model_rol": hx.Float(mode="output", async_input=["generate_uw_doc"], view={"label": "Model ROL", "format": {"output": "percent", "mantissa": 2}}),
                "warnings": hx.Str(mode="output", view={"label": "Warnings"}),
                "pflr_pre_uw_adj": hx.Float(mode="output", optionality="optional", view={"label": "Priced-for Loss Ratio (Pre-UW Adj.)", "format": {"output": "percent", "mantissa": 1}}),
            }),
            "currencies": hx.Structure(view={"label": "Currencies"}, children={
                "target_currency": hx.Str(mode="input", default=None, optionality="optional", options=["ADP", "AFA", "AON", "AOR", "ATS", "AZM", "BEF", "BGL", "BRE", "BUK", "BYB", "BYR", "CSD", "CSK", "CYP", "DDM", "DEM", "ECS", "EEK", "ESP", "FIM", "FRF", "GHC", "GRD", "GWP", "HRK", "IEP", "ITL", "LTL", "LUF", "LVL", "MGF", "MRO", "MTL", "MXP", "MZM", "NIC", "NLG", "PES", "PLZ", "PTE", "ROL", "RUR", "SDD", "SDP", "SIT", "SKK", "SRG", "STD", "SUR", "TRL", "UYP", "VEB", "VEF", "XEU", "YUM", "ZMK", "ZRN", "ZRZ", "ZWD", "ZWR", "AED", "AFN", "ALL", "AMD", "ANG", "AOA", "ARS", "AUD", "AWG", "AZN", "BAM", "BBD", "BDT", "BGN", "BHD", "BIF", "BMD", "BND", "BOB", "BOV", "BRL", "BSD", "BTN", "BWP", "BYN", "BZD", "CAD", "CDF", "CHE", "CHF", "CHW", "CLF", "CLP", "CNY", "COP", "COU", "CRC", "CUC", "CUP", "CVE", "CZK", "DJF", "DKK", "DOP", "DZD", "EGP", "ERN", "ETB", "EUR", "FJD", "FKP", "GBP", "GEL", "GHS", "GIP", "GMD", "GNF", "GTQ", "GYD", "HKD", "HNL", "HTG", "HUF", "IDR", "ILS", "INR", "IQD", "IRR", "ISK", "JMD", "JOD", "JPY", "KES", "KGS", "KHR", "KMF", "KPW", "KRW", "KWD", "KYD", "KZT", "LAK", "LBP", "LKR", "LRD", "LSL", "LYD", "MAD", "MDL", "MGA", "MKD", "MMK", "MNT", "MOP", "MRU", "MUR", "MVR", "MWK", "MXN", "MXV", "MYR", "MZN", "NAD", "NGN", "NIO", "NOK", "NPR", "NZD", "OMR", "PAB", "PEN", "PGK", "PHP", "PKR", "PLN", "PYG", "QAR", "RON", "RSD", "RUB", "RWF", "SAR", "SBD", "SCR", "SDG", "SEK", "SGD", "SHP", "SLE", "SLL", "SOS", "SRD", "SSP", "STN", "SVC", "SYP", "SZL", "THB", "TJS", "TMT", "TND", "TOP", "TRY", "TTD", "TWD", "TZS", "UAH", "UGX", "USD", "USN", "UYI", "UYU", "UYW", "UZS", "VED", "VES", "VND", "VUV", "WST", "XAF", "XAG", "XAU", "XBA", "XBB", "XBC", "XBD", "XCD", "XDR", "XOF", "XPD", "XPF", "XPT", "XSU", "XTS", "XUA", "XXX", "YER", "ZAR", "ZMW", "ZWL"], view={"label": "Target Currency"}),
                "source_currency": hx.Str(mode="input", default="USD", async_input=["generate_uw_doc"], optionality="optional", options=["ADP", "AFA", "AON", "AOR", "ATS", "AZM", "BEF", "BGL", "BRE", "BUK", "BYB", "BYR", "CSD", "CSK", "CYP", "DDM", "DEM", "ECS", "EEK", "ESP", "FIM", "FRF", "GHC", "GRD", "GWP", "HRK", "IEP", "ITL", "LTL", "LUF", "LVL", "MGF", "MRO", "MTL", "MXP", "MZM", "NIC", "NLG", "PES", "PLZ", "PTE", "ROL", "RUR", "SDD", "SDP", "SIT", "SKK", "SRG", "STD", "SUR", "TRL", "UYP", "VEB", "VEF", "XEU", "YUM", "ZMK", "ZRN", "ZRZ", "ZWD", "ZWR", "AED", "AFN", "ALL", "AMD", "ANG", "AOA", "ARS", "AUD", "AWG", "AZN", "BAM", "BBD", "BDT", "BGN", "BHD", "BIF", "BMD", "BND", "BOB", "BOV", "BRL", "BSD", "BTN", "BWP", "BYN", "BZD", "CAD", "CDF", "CHE", "CHF", "CHW", "CLF", "CLP", "CNY", "COP", "COU", "CRC", "CUC", "CUP", "CVE", "CZK", "DJF", "DKK", "DOP", "DZD", "EGP", "ERN", "ETB", "EUR", "FJD", "FKP", "GBP", "GEL", "GHS", "GIP", "GMD", "GNF", "GTQ", "GYD", "HKD", "HNL", "HTG", "HUF", "IDR", "ILS", "INR", "IQD", "IRR", "ISK", "JMD", "JOD", "JPY", "KES", "KGS", "KHR", "KMF", "KPW", "KRW", "KWD", "KYD", "KZT", "LAK", "LBP", "LKR", "LRD", "LSL", "LYD", "MAD", "MDL", "MGA", "MKD", "MMK", "MNT", "MOP", "MRU", "MUR", "MVR", "MWK", "MXN", "MXV", "MYR", "MZN", "NAD", "NGN", "NIO", "NOK", "NPR", "NZD", "OMR", "PAB", "PEN", "PGK", "PHP", "PKR", "PLN", "PYG", "QAR", "RON", "RSD", "RUB", "RWF", "SAR", "SBD", "SCR", "SDG", "SEK", "SGD", "SHP", "SLE", "SLL", "SOS", "SRD", "SSP", "STN", "SVC", "SYP", "SZL", "THB", "TJS", "TMT", "TND", "TOP", "TRY", "TTD", "TWD", "TZS", "UAH", "UGX", "USD", "USN", "UYI", "UYU", "UYW", "UZS", "VED", "VES", "VND", "VUV", "WST", "XAF", "XAG", "XAU", "XBA", "XBB", "XBC", "XBD", "XCD", "XDR", "XOF", "XPD", "XPF", "XPT", "XSU", "XTS", "XUA", "XXX", "YER", "ZAR", "ZMW", "ZWL"], view={"label": "Source Currency", "options": {"read_only": {"read_only": True}}}),
                "multi_currency_support": hx.Bool(mode="input", default=False, optionality="required", view={"label": "Multi Currency Support"}),
                "rates": hx.List(mode="input", view={"label": "Rates"}, children={
                    "code": hx.Str(mode="input", default=None, optionality="optional", view={"label": "Code"}),
                    "rate": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Rate", "format": {"thousandSeparated": False, "mantissa": 2}}),
                }),
            }),
            "experience_rating": hx.Structure(view={"label": "Experience Rating"}, children={
                "claims_available": hx.Bool(mode="input", default=False, view={"label": "Loss Data Avaialble"}),
                "claims_fgu": hx.Bool(mode="input", default=False, view={"label": "Claims From Ground Up"}),
                "claims_net_of_deductible": hx.Bool(mode="input", default=False, view={"label": "Are Claims net of Deductible"}),
            }),
            "database_id": hx.Int(mode="output", view={"label": "Database ID", "format": {"thousandSeparated": False, "mantissa": 0}}),
            "broker_contact": hx.Str(mode="input", default="", view={"label": "Broker Contact"}),
            "rate_change": hx.Structure(children={
                "show_layer_1": hx.Bool(mode="output"),
                "show_layer_2": hx.Bool(mode="output"),
                "show_layer_3": hx.Bool(mode="output"),
                "show_layer_4": hx.Bool(mode="output"),
                "show_layer_5": hx.Bool(mode="output"),
                "show_layer_6": hx.Bool(mode="output"),
                "show_layer_7": hx.Bool(mode="output"),
                "show_layer_8": hx.Bool(mode="output"),
                "show_layer_9": hx.Bool(mode="output"),
                "show_layer_10": hx.Bool(mode="output"),
                "expiring_policy_option_id": hx.Int(mode="override", async_input=["expiring_policy_fetch_task", "rarc_task"], view={"label": "Expiring Policy Option", "format": {"thousandSeparated": False}}),
                "has_fetch_not_run": hx.Bool(mode="input", default=True, async_output=["expiring_policy_fetch_task", "rarc_task"]),
                "has_fetch_run": hx.Bool(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task"]),
                "has_rarc_not_run": hx.Bool(mode="input", default=True, async_output=["rarc_task"]),
                "has_rarc_run": hx.Bool(mode="output", async_output=["rarc_task"]),
                "rarc_run_again_message": hx.Str(mode="output"),
                "rarc_message_show": hx.Bool(mode="output"),
                "layer_mapping": hx.Str(mode="output", async_output=["expiring_policy_fetch_task", "rarc_task"]),
            }),
            "term": hx.Float(mode="output", async_input=["generate_uw_doc"], view={"label": "Policy Period (years)", "format": {"thousandSeparated": False, "mantissa": 2}, "options": {"read_only": {"label": " "}}}),
            "policy_info": hx.Structure(children={
                "fundamental_top_up_flag": hx.Bool(mode="input", default=False, async_input=["generate_uw_doc"], view={"label": "Does this polciy include Fundamental Top Up Coverage?"}),
                "project_name": hx.Str(mode="input", default=None, async_input=["generate_uw_doc"], optionality="optional", view={"label": "Project Name"}),
                "target_name": hx.Str(mode="input", default=None, async_input=["generate_uw_doc"], optionality="optional", view={"label": "Target Company (Name)"}),
                "transaction_value": hx.Float(mode="input", default=0, async_input=["generate_uw_doc"], optionality="optional", view={"label": "Transaction Value"}),
                "total_limit": hx.Float(mode="input", default=0, async_input=["generate_uw_doc"], optionality="optional", view={"label": "Total Limit Purchased Source Currency"}),
                "total_limit_percentage": hx.Float(mode="output", async_input=["generate_uw_doc"], view={"label": "Total limit purchased %", "format": {"output": "percent", "mantissa": 2}, "options": {"read_only": {"label": " "}}}),
                "brokerage": hx.Float(mode="input", default=0.15, async_input=["generate_uw_doc"], optionality="optional", view={"label": "Brokerage", "format": {"output": "percent", "mantissa": 1}}),
                "policyholder": hx.Str(mode="input", default="Buyer", async_input=["generate_uw_doc"], optionality="required", options=["Buyer", "Seller"], view={"label": "Policy Purchased by"}),
                "buyer_name": hx.Str(mode="input", default=None, async_input=["generate_uw_doc"], optionality="optional", view={"label": "Buyer (name)"}),
                "buyer_lawyer": hx.Str(mode="input", default=None, async_input=["generate_uw_doc"], optionality="optional", view={"label": "Lawyer (buyer)"}),
                "seller_name": hx.Str(mode="input", default=None, async_input=["generate_uw_doc"], optionality="optional", view={"label": "Seller (name)"}),
                "seller_lawyer": hx.Str(mode="input", default=None, async_input=["generate_uw_doc"], optionality="optional", view={"label": "Lawyer (seller)"}),
                "uw_expenses_flag": hx.Bool(mode="input", default=False, async_input=["generate_uw_doc"], view={"label": "Include UW Expenses"}),
                "uw_expenses": hx.Float(mode="input", default=None, async_input=["generate_uw_doc"], optionality="optional", view={"label": "Underwriting Expenses"}),
                "distressed_business_flag": hx.Bool(mode="input", default=False, async_input=["generate_uw_doc"], view={"label": "Distressed Business"}),
            }),
            "rating_factors": hx.Structure(children={
                "freq": hx.Structure(children={
                    "target": hx.Structure(view={"label": "Target"}, children={
                        "jurisdiction": hx.Str(mode="input", default=None, async_input=["generate_uw_doc"], optionality="optional", options_column="location", options_table="table_country_factor", view={"label": "Jurisdiction", "multiline": True}),
                        "industry": hx.Str(mode="input", default=None, async_input=["generate_uw_doc"], optionality="optional", options_column="industry list", options_table="table_industry", view={"label": "Industry", "multiline": True}),
                        "business_nature": hx.Str(mode="input", default=None, async_input=["generate_uw_doc"], optionality="optional", view={"label": "Nature of Business"}),
                        "ihs_enforcement": hx.Str(mode="output", view={"label": "IHS Contract Enforcement"}),
                    }),
                    "buyer": hx.Structure(view={"label": "Buyer"}, children={
                        "jurisdiction": hx.Str(mode="input", default=None, async_input=["generate_uw_doc"], optionality="optional", options_column="location", options_table="table_country_factor", view={"label": "Jurisdiction", "multiline": True}),
                        "industry": hx.Str(mode="input", default=None, async_input=["generate_uw_doc"], optionality="optional", options_column="industry list", options_table="table_industry", view={"label": "Industry", "multiline": True}),
                        "business_nature": hx.Str(mode="input", default=None, async_input=["generate_uw_doc"], optionality="optional", view={"label": "Nature of Business"}),
                        "ihs_enforcement": hx.Str(mode="output", view={"label": "IHS Contract Enforcement"}),
                    }),
                    "default_score": hx.Float(mode="output", async_input=["generate_uw_doc"], view={"label": "Default Score", "format": {"output": "percent", "mantissa": 2}}),
                    "freq_adjustment": hx.Float(mode="input", default=0, async_input=["generate_uw_doc"], optionality="optional", view={"label": "Adjustment", "format": {"output": "percent", "mantissa": 2}}),
                    "freq_adjusted": hx.Float(mode="output", async_input=["generate_uw_doc"], view={"label": "Adjusted frequency", "format": {"output": "percent", "mantissa": 2}}),
                    "freq_adjusted_pre_uw": hx.Float(mode="output", async_input=["generate_uw_doc"], view={"label": "Adjusted frequency (Pre-UW Adj)", "format": {"output": "percent", "mantissa": 2}}),
                }),
                "sev": hx.Structure(children={
                    "due_diligence": hx.Structure(view={"label": "Due Diligence"}, children={
                        "coverage_flag": hx.Bool(mode="input", default=True, async_input=["generate_uw_doc"], view={"label": "Covered?"}),
                        "severity_assessment": hx.Str(mode="input", default="Medium", async_input=["generate_uw_doc"], optionality="required", options_column="severity", options_table="table_severity_parameters", view={"label": "Severity assessment"}),
                        "adjustment": hx.Float(mode="input", default=0, async_input=["generate_uw_doc"], optionality="optional", view={"label": "Adjustment", "format": {"output": "percent", "mantissa": 2}}),
                        "comment": hx.Str(mode="input", default=None, async_input=["generate_uw_doc"], optionality="optional", view={"label": "Comment"}),
                    }),
                    "disclosure": hx.Structure(view={"label": "Disclosure"}, children={
                        "coverage_flag": hx.Bool(mode="input", default=True, async_input=["generate_uw_doc"], view={"label": "Covered?"}),
                        "severity_assessment": hx.Str(mode="input", default="Medium", async_input=["generate_uw_doc"], optionality="required", options_column="severity", options_table="table_severity_parameters", view={"label": "Severity assessment"}),
                        "adjustment": hx.Float(mode="input", default=0, async_input=["generate_uw_doc"], optionality="optional", view={"label": "Adjustment", "format": {"output": "percent", "mantissa": 2}}),
                        "comment": hx.Str(mode="input", default=None, async_input=["generate_uw_doc"], optionality="optional", view={"label": "Comment"}),
                    }),
                    "general_warranties": hx.Structure(view={"label": "General Warranties"}, children={
                        "coverage_flag": hx.Bool(mode="input", default=True, async_input=["generate_uw_doc"], view={"label": "Covered?"}),
                        "severity_assessment": hx.Str(mode="input", default="Medium", async_input=["generate_uw_doc"], optionality="required", options_column="severity", options_table="table_severity_parameters", view={"label": "Severity assessment"}),
                        "adjustment": hx.Float(mode="input", default=0, async_input=["generate_uw_doc"], optionality="optional", view={"label": "Adjustment", "format": {"output": "percent", "mantissa": 2}}),
                        "comment": hx.Str(mode="input", default=None, async_input=["generate_uw_doc"], optionality="optional", view={"label": "Comment"}),
                        "term": hx.Float(mode="input", default=None, async_input=["generate_uw_doc"], optionality="optional", view={"label": "Term (years)"}),
                        "term_modifier": hx.Float(mode="input", default=0, async_input=["generate_uw_doc"], optionality="optional", view={"label": "Term modifier"}),
                    }),
                    "tax_warranties": hx.Structure(view={"label": "Tax Warranties/Deed"}, children={
                        "coverage_flag": hx.Bool(mode="input", default=True, async_input=["generate_uw_doc"], view={"label": "Covered?"}),
                        "severity_assessment": hx.Str(mode="input", default="Medium", async_input=["generate_uw_doc"], optionality="required", options_column="severity", options_table="table_severity_parameters", view={"label": "Severity assessment"}),
                        "adjustment": hx.Float(mode="input", default=0, async_input=["generate_uw_doc"], optionality="optional", view={"label": "Adjustment", "format": {"output": "percent", "mantissa": 2}}),
                        "comment": hx.Str(mode="input", default=None, async_input=["generate_uw_doc"], optionality="optional", view={"label": "Comment"}),
                        "term": hx.Float(mode="input", default=None, async_input=["generate_uw_doc"], optionality="optional", view={"label": "Term (years)"}),
                        "term_modifier": hx.Float(mode="input", default=0, async_input=["generate_uw_doc"], optionality="optional", view={"label": "Term modifier"}),
                    }),
                    "modified_score": hx.Float(mode="output", async_input=["generate_uw_doc"], view={"label": "Modified Score"}),
                    "modified_score_pre_uw": hx.Float(mode="output", async_input=["generate_uw_doc"], view={"label": "Modified Score (Pre-UW Adj)"}),
                    "div_flag": hx.Bool(mode="input", default=False, async_input=["generate_uw_doc"], view={"label": "Include DIV"}),
                    "volatility": hx.Str(mode="input", default="Medium", async_input=["generate_uw_doc"], options_column="volatility", options_table="table_volatility", view={"label": "Volatility"}),
                    "multiple": hx.Float(mode="input", default=None, async_input=["generate_uw_doc"], optionality="optional", view={"label": "Multiple"}),
                }),
                "fun_top_up": hx.Structure(view={"label": "Fundamental Top Up"}, children={
                    "base_rate": hx.Float(mode="output", async_input=["generate_uw_doc"], view={"label": "Base Rate", "format": {"output": "percent", "mantissa": 2}}),
                    "adjustment": hx.Float(mode="input", default=0, async_input=["generate_uw_doc"], optionality="optional", view={"label": "Adjustment", "format": {"output": "percent", "mantissa": 2}}),
                    "term": hx.Float(mode="input", default=None, async_input=["generate_uw_doc"], optionality="optional", view={"label": "Term (years)"}),
                    "comment": hx.Str(mode="input", default=None, async_input=["generate_uw_doc"], optionality="optional", view={"label": "Comment"}),
                }),
            }),
            "blend_option": hx.Structure(children={
                "option_names_list": hx.List(mode="output", view={"label": "List of Options Entered"}, children={
                    "option_name": hx.Str(mode="output", view={"label": "Option Name"}),
                }),
                "instruction": hx.Str(mode="output", view={"label": "", "multiline": True}),
                "option_1": hx.Structure(view={"label": "Option 1"}, children={
                    "option_name": hx.Str(mode="input", default=None, optionality="optional", options_data="../../option_names_list", options_field="option_name", view={"label": "Option Name"}),
                    "weight": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Weight %", "format": {"output": "percent", "mantissa": 2}}),
                    "weight_excess": hx.Float(mode="output", view={"label": "Weight Excess", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "model_rol": hx.Float(mode="output", view={"label": "ROL", "format": {"output": "percent", "mantissa": 2}}),
                }),
                "option_2": hx.Structure(view={"label": "Option 2"}, children={
                    "option_name": hx.Str(mode="input", default=None, optionality="optional", options_data="../../option_names_list", options_field="option_name", view={"label": "Option Name"}),
                    "weight": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Weight %", "format": {"output": "percent", "mantissa": 2}}),
                    "weight_excess": hx.Float(mode="output", view={"label": "Weight Excess", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "model_rol": hx.Float(mode="output", view={"label": "ROL", "format": {"output": "percent", "mantissa": 2}}),
                }),
                "option_3": hx.Structure(view={"label": "Option 3"}, children={
                    "option_name": hx.Str(mode="input", default=None, optionality="optional", options_data="../../option_names_list", options_field="option_name", view={"label": "Option Name"}),
                    "weight": hx.Float(mode="input", default=None, optionality="optional", view={"label": "Weight %", "format": {"output": "percent", "mantissa": 2}}),
                    "weight_excess": hx.Float(mode="output", view={"label": "Weight Excess", "format": {"thousandSeparated": True, "mantissa": 0}}),
                    "model_rol": hx.Float(mode="output", view={"label": "ROL", "format": {"output": "percent", "mantissa": 2}}),
                }),
                "option_name": hx.Str(mode="output", view={"label": "Option name"}),
                "limit": hx.Float(mode="output", view={"label": "Limit", "format": {"thousandSeparated": True, "mantissa": 2}}),
                "limit_pct": hx.Float(mode="output", view={"label": "Limit %", "format": {"output": "percent", "mantissa": 2}}),
                "excess": hx.Float(mode="output", view={"label": "Dropdown Excess", "format": {"thousandSeparated": True, "mantissa": 2}}),
                "excess_pct": hx.Float(mode="output", view={"label": "Initial Excess %", "format": {"output": "percent", "mantissa": 2}}),
                "indicated": hx.Bool(mode="output", view={"label": "Indicated"}),
                "date": hx.Date(mode="output", view={"label": "Date"}),
                "quota_share": hx.Bool(mode="output"),
                "is_bound": hx.Bool(mode="output", view={"label": "Bound?"}),
                "quoted_premium": hx.Float(mode="output", view={"label": "Bound Premium", "format": {"thousandSeparated": True, "mantissa": 2}}),
            }),
            "rationale": hx.Structure(children={
                "transaction_description": hx.Str(mode="input", default=None, async_input=["generate_uw_doc"], optionality="optional", view={"label": "Transaction Description and Summary of Target"}),
                "knowledge_of_insured": hx.Str(mode="input", default=None, async_input=["generate_uw_doc"], optionality="optional", view={"label": "Knowledge of the Insured - List of DD Reports"}),
                "reasons_for_writing_risk": hx.Str(mode="input", default=None, async_input=["generate_uw_doc"], optionality="optional", view={"label": "Reasons for writing the Risk"}),
                "complex_considerations": hx.Str(mode="input", default=None, async_input=["generate_uw_doc"], optionality="optional", view={"label": "Unusual Or Complex Aspects of the Risk"}),
                "exclusions_and_carve_outs": hx.Str(mode="input", default=None, async_input=["generate_uw_doc"], optionality="optional", view={"label": "Exclusions and Carve Outs"}),
            }),
            "eso": hx.Structure(children={
                "premium_total": hx.Float(mode="override", async_input=["generate_uw_doc"], view={"label": "Premium", "info": "This is Beazley's share, calculated based on the QS from the Rating Summary tab. It applies only to the options selected from the table above.", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "limit_total": hx.Float(mode="override", async_input=["generate_uw_doc"], view={"label": "Limit", "info": "This is Beazley's share, calculated based on the QS from the Rating Summary tab. It applies only to the options selected from the table above.", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "label": hx.Str(mode="output", view={"label": "Option"}),
                "term": hx.Str(mode="override", async_input=["generate_uw_doc"], view={"label": "Term", "info": "Based on severity selections for General Warranties and Tax Warranties/Deed in the Exposure Details tab.", "format": {"thousandSeparated": True, "mantissa": 0}}),
                "additional_term_info": hx.Str(mode="input", default=None, async_input=["generate_uw_doc"], optionality="optional", view={"label": "Term"}),
                "over_lining": hx.Str(mode="input", default="N/A", async_input=["generate_uw_doc"], optionality="optional", view={"label": "Over Lining (Total Exposure)"}),
                "cob": hx.Str(mode="input", default="N/A", async_input=["generate_uw_doc"], optionality="optional", view={"label": "Unauthorised COB or MOP"}),
                "authorising_comments": hx.Str(mode="input", default=None, async_input=["generate_uw_doc"], optionality="optional", view={"label": "Amount Authorising/Further Comments"}),
                "authorising_comments_info": hx.Str(mode="output", async_input=["generate_uw_doc"], view={"label": "None"}),
                "section_references": hx.Str(mode="output", async_input=["generate_uw_doc"], view={"label": "Selected Policy References"}),
                "bind_date": hx.Date(mode="input", default=None, async_input=["generate_uw_doc"], optionality="optional", view={"label": "Bind Date"}),
                "approving_uw": hx.Str(mode="input", default=None, async_input=["generate_uw_doc"], optionality="optional", view={"label": "Approving Underwriter's Limit of Authority:"}),
                "authorisation_date": hx.Date(mode="input", default=None, async_input=["generate_uw_doc"], optionality="optional", view={"label": "Date of Authorisation"}),
                "info": hx.Str(mode="output", async_input=["generate_uw_doc"], view={"label": "None"}),
                "document": hx.File(mode="output", async_output=["generate_uw_doc"], file_name="eso_doc.docx", view={"label": "Document"}),
                "options": hx.Structure(children={
                    "coverage": hx.Structure(children={
                        "option_0": hx.Str(mode="output"),
                        "option_1": hx.Str(mode="output"),
                        "option_2": hx.Str(mode="output"),
                        "option_3": hx.Str(mode="output"),
                        "option_4": hx.Str(mode="output"),
                        "option_5": hx.Str(mode="output"),
                        "option_6": hx.Str(mode="output"),
                        "option_7": hx.Str(mode="output"),
                        "option_8": hx.Str(mode="output"),
                        "option_9": hx.Str(mode="output"),
                        "label": hx.Str(mode="output", view={"label": "Option"}),
                    }),
                    "include_option": hx.Structure(children={
                        "option_0": hx.Bool(mode="input", default=True),
                        "option_1": hx.Bool(mode="input", default=True),
                        "option_2": hx.Bool(mode="input", default=True),
                        "option_3": hx.Bool(mode="input", default=True),
                        "option_4": hx.Bool(mode="input", default=True),
                        "option_5": hx.Bool(mode="input", default=True),
                        "option_6": hx.Bool(mode="input", default=True),
                        "option_7": hx.Bool(mode="input", default=True),
                        "option_8": hx.Bool(mode="input", default=True),
                        "option_9": hx.Bool(mode="input", default=True),
                        "label": hx.Str(mode="output", view={"label": "Include in Totals?"}),
                    }),
                    "show_hide": hx.Structure(children={
                        "option_0": hx.Bool(mode="output"),
                        "option_1": hx.Bool(mode="output"),
                        "option_2": hx.Bool(mode="output"),
                        "option_3": hx.Bool(mode="output"),
                        "option_4": hx.Bool(mode="output"),
                        "option_5": hx.Bool(mode="output"),
                        "option_6": hx.Bool(mode="output"),
                        "option_7": hx.Bool(mode="output"),
                        "option_8": hx.Bool(mode="output"),
                        "option_9": hx.Bool(mode="output"),
                    }),
                }),
            }),
        }),
        "model_state": hx.Structure(children={
            "pressed_start_renewal_task": hx.Bool(mode="output", async_output=["start_renewal_task"]),
            "show_landing_page": hx.Bool(mode="output"),
            "show_after_landing_page": hx.Bool(mode="output"),
            "show_rate_change": hx.Bool(mode="output"),
            "landing_page_info": hx.Str(mode="input", default="Click 'Import Expiring Policy Data' in the top right corner then click 'Start Policy'", async_output=["start_renewal_task"], view={"read_only": True}),
        }),
        "bug_report_email": hx.Str(mode="output"),
        "bug_report": hx.Structure(children={
            "helper_text": hx.Str(mode="output", optionality="optional"),
            "recipient_email": hx.Str(mode="output", async_input=["send_bug_report_task"], async_output=["new_bug_report_task", {"task": "send_bug_report_task", "reset": False}, "cancel_bug_report_task"], view={"label": "Recipient Email"}),
            "cc_email": hx.Str(mode="output", async_input=["send_bug_report_task"], async_output=["new_bug_report_task", {"task": "send_bug_report_task", "reset": False}, "cancel_bug_report_task"], view={"label": "CC Email"}),
            "subject_line": hx.Str(mode="output", async_input=["send_bug_report_task"], async_output=["new_bug_report_task", {"task": "send_bug_report_task", "reset": False}, "cancel_bug_report_task"], view={"label": "Subject Line"}),
            "summary": hx.Str(mode="input", default="", async_input=["send_bug_report_task"], async_output=["new_bug_report_task", {"task": "send_bug_report_task", "reset": False}, "cancel_bug_report_task"], view={"multiline": True}),
            "email_body": hx.Str(mode="input", default=None, async_input=["send_bug_report_task"], async_output=["new_bug_report_task", {"task": "send_bug_report_task", "reset": False}, "cancel_bug_report_task"], optionality="optional", view={"label": "Details"}),
            "inputs_outputs_file_show": hx.Bool(mode="output", async_output=["new_bug_report_task"]),
            "inputs_outputs_file": hx.File(mode="output", async_output=["generate_bug_report_task", "cancel_bug_report_task", "send_bug_report_task"], file_name="inputs_outputs.json", view={"label": "Input/Outputs File"}),
            "file_helper_text": hx.Str(mode="input", default="**Note: Make sure to press the \"Upload File\" button to attach the file**", view={"options": {"read_only": {"read_only": True}}}),
            "files_shown": hx.Int(mode="input", default=1, async_output=["new_bug_report_task", {"task": "add_additional_file_task", "reset": False}]),
            "screenshot_files": hx.Structure(children={
                "f1": hx.Structure(children={
                    "file": hx.File(mode="input", async_input=["add_additional_file_task", "send_bug_report_task"], async_output=["new_bug_report_task", "cancel_bug_report_task"]),
                    "show_file": hx.Bool(mode="input", default=True, async_output=["new_bug_report_task", {"task": "add_additional_file_task", "reset": False}]),
                    "show_text": hx.Bool(mode="input", default=True, async_output=["new_bug_report_task", {"task": "add_additional_file_task", "reset": False}]),
                }),
                "f2": hx.Structure(children={
                    "file": hx.File(mode="input", async_input=["add_additional_file_task", "send_bug_report_task"], async_output=["new_bug_report_task", "cancel_bug_report_task"]),
                    "show_file": hx.Bool(mode="input", default=False, async_output=["new_bug_report_task", {"task": "add_additional_file_task", "reset": False}]),
                    "show_text": hx.Bool(mode="input", default=False, async_output=["new_bug_report_task", {"task": "add_additional_file_task", "reset": False}]),
                }),
                "f3": hx.Structure(children={
                    "file": hx.File(mode="input", async_input=["add_additional_file_task", "send_bug_report_task"], async_output=["new_bug_report_task", "cancel_bug_report_task"]),
                    "show_file": hx.Bool(mode="input", default=False, async_output=["new_bug_report_task", {"task": "add_additional_file_task", "reset": False}]),
                    "show_text": hx.Bool(mode="input", default=False, async_output=["new_bug_report_task", {"task": "add_additional_file_task", "reset": False}]),
                }),
                "f4": hx.Structure(children={
                    "file": hx.File(mode="input", async_input=["add_additional_file_task", "send_bug_report_task"], async_output=["new_bug_report_task", "cancel_bug_report_task"]),
                    "show_file": hx.Bool(mode="input", default=False, async_output=["new_bug_report_task", {"task": "add_additional_file_task", "reset": False}]),
                    "show_text": hx.Bool(mode="input", default=False, async_output=["new_bug_report_task", {"task": "add_additional_file_task", "reset": False}]),
                }),
                "f5": hx.Structure(children={
                    "file": hx.File(mode="input", async_input=["add_additional_file_task", "send_bug_report_task"], async_output=["new_bug_report_task", "cancel_bug_report_task"]),
                    "show_file": hx.Bool(mode="input", default=False, async_output=["new_bug_report_task", {"task": "add_additional_file_task", "reset": False}]),
                    "show_text": hx.Bool(mode="input", default=False, async_output=["new_bug_report_task", {"task": "add_additional_file_task", "reset": False}]),
                }),
            }),
            "commenced_flag": hx.Bool(mode="output", async_output=["new_bug_report_task", {"task": "send_bug_report_task", "reset": False}, "cancel_bug_report_task"], view={"label": "Commenced"}),
            "inputs_outputs": hx.Str(mode="output", async_input=["generate_bug_report_task", "cancel_bug_report_task", "new_bug_report_task", "send_bug_report_task"], view={"label": "Inputs/Outputs"}),
            "show_email": hx.Bool(mode="input", default=False),
            "model_name": hx.Str(mode="output", async_input=["send_bug_report_task"], async_output=["new_bug_report_task", {"task": "send_bug_report_task", "reset": False}, "cancel_bug_report_task"]),
        }),
        "policy_doc": hx.Structure(children={
            "data_dict": hx.Str(mode="output", async_input=["generate_uw_doc"]),
            "output_file_doc": hx.File(mode="output", async_output=["generate_uw_doc"], file_name="Policy_Summary.docx"),
            "task_data_dict": hx.Str(mode="output", async_output=["generate_uw_doc"]),
            "show_generate_button": hx.Bool(mode="output"),
            "show_download": hx.Bool(mode="output"),
            "premium_check": hx.Str(mode="output"),
            "show_premium_check": hx.Bool(mode="output"),
        }),
    })
